export const IDIOMS = [
  // ── BODY ───────────────────────────────────────────────────────────────────
  { id:'b1',  idiom:'break a leg',                     meaning:'good luck',                                      serbian:'sretno',                               category:'body',     level:'A2', example:'Break a leg on your exam today!',                                               origin:'Old theatre superstition — wishing bad luck was thought to bring good luck',              tags:['luck','theatre','informal'] },
  { id:'b2',  idiom:'cost an arm and a leg',            meaning:'be very expensive',                              serbian:'koštati bogatstvo',                     category:'body',     level:'A2', example:'That new phone costs an arm and a leg.',                                        origin:'From the idea that losing limbs is the greatest sacrifice',                              tags:['money','price','informal'] },
  { id:'b3',  idiom:'keep an eye on',                  meaning:'watch carefully or monitor',                     serbian:'paziti na / imati na oku',              category:'body',     level:'A2', example:'Can you keep an eye on my bag while I go to the bathroom?',                    origin:'Refers to using one\'s eyes to watch over something',                                    tags:['watch','care','monitor'] },
  { id:'b4',  idiom:'turn a blind eye',                meaning:'deliberately ignore something wrong',            serbian:'zatvoriti oči pred nečim',             category:'body',     level:'B1', example:'The manager turned a blind eye to the employees\' late arrivals.',              origin:'Said to originate from Admiral Nelson at Battle of Copenhagen, ignoring orders',          tags:['ignore','dishonesty','formal'] },
  { id:'b5',  idiom:'get something off your chest',    meaning:'tell someone something that has been worrying you', serbian:'skinuti kamen sa srca',             category:'body',     level:'B1', example:'I need to get something off my chest — I\'ve been lying to you.',              origin:'Chest as the seat of emotions in old beliefs',                                           tags:['feelings','confession','informal'] },
  { id:'b6',  idiom:'have a heart of gold',            meaning:'be very kind and generous',                      serbian:'imati zlatno srce',                    category:'body',     level:'A2', example:'My grandmother has a heart of gold — she helps everyone.',                     origin:'Gold as symbol of purity and goodness',                                                 tags:['kindness','personality','positive'] },
  { id:'b7',  idiom:'bite off more than you can chew', meaning:'take on more than you can handle',               serbian:'uhvatiti se u koštac s previše',       category:'body',     level:'B1', example:'He bit off more than he could chew when he took three jobs at once.',          origin:'Literally taking too large a bite of food',                                              tags:['overcommit','work','warning'] },
  { id:'b8',  idiom:'pull someone\'s leg',             meaning:'joke or tease someone',                          serbian:'zezati nekoga',                        category:'body',     level:'A2', example:'Are you serious or are you pulling my leg?',                                   origin:'Possibly from tripping someone as a joke',                                               tags:['joke','tease','informal'] },
  { id:'b9',  idiom:'face the music',                  meaning:'accept the consequences of your actions',        serbian:'suočiti se s posljedicama',            category:'body',     level:'B1', example:'He made a mistake and now he has to face the music.',                          origin:'From military punishment — facing the band while being dismissed',                       tags:['consequences','responsibility','serious'] },
  { id:'b10', idiom:'lend an ear',                     meaning:'listen carefully to someone',                    serbian:'poslušati nekoga',                     category:'body',     level:'B1', example:'Could you lend me an ear? I have a problem.',                                 origin:'From Shakespeare\'s Julius Caesar — "Lend me your ears"',                                tags:['listen','help','formal'] },
  { id:'b11', idiom:'a slap in the face',              meaning:'an insult or rejection that shocks you',         serbian:'šamar / udarac u obraz',              category:'body',     level:'B2', example:'Not getting a promotion was a slap in the face.',                              origin:'Literal slap as an insult',                                                              tags:['insult','rejection','negative'] },
  { id:'b12', idiom:'keep your chin up',               meaning:'stay positive in a difficult situation',         serbian:'drži glavu gore',                      category:'body',     level:'A2', example:'Keep your chin up — things will get better.',                                  origin:'Holding chin up is a sign of confidence and courage',                                    tags:['encouragement','positivity','informal'] },
  { id:'b13', idiom:'have butterflies in your stomach',meaning:'feel nervous or anxious',                        serbian:'imati leptiriće u stomaku',            category:'body',     level:'A2', example:'I always have butterflies in my stomach before a job interview.',              origin:'The physical sensation of anxiety in the stomach',                                       tags:['nervous','anxiety','feelings'] },
  { id:'b14', idiom:'in over your head',               meaning:'involved in something too difficult',            serbian:'previše duboko u nečemu',              category:'body',     level:'B1', example:'She took on the project but was quickly in over her head.',                    origin:'Literally being in water too deep to stand',                                             tags:['difficulty','overwhelm','warning'] },
  { id:'b15', idiom:'see eye to eye',                  meaning:'agree with someone',                             serbian:'biti na istoj liniji / složiti se',    category:'body',     level:'B1', example:'We don\'t always see eye to eye but we respect each other.',                  origin:'Looking at the same level implies agreement',                                            tags:['agree','relationship','communication'] },
  { id:'b16', idiom:'bite the bullet',                 meaning:'endure a painful situation bravely',             serbian:'stisnuti zube i izdržati',             category:'body',     level:'B1', example:'I hate going to the dentist but I\'ll bite the bullet.',                     origin:'Soldiers biting bullets during surgery without anaesthesia',                             tags:['endure','brave','difficult'] },
  { id:'b17', idiom:'keep your fingers crossed',       meaning:'hope for good luck',                             serbian:'držati fige / palčeve',                category:'body',     level:'A2', example:'Keep your fingers crossed for me — I have my driving test today.',           origin:'Making a cross with fingers as a good luck charm',                                       tags:['luck','hope','informal'] },
  { id:'b18', idiom:'have two left feet',              meaning:'be very clumsy or bad at dancing',               serbian:'biti nespretnog kretanja',             category:'body',     level:'B1', example:'Don\'t ask me to dance — I have two left feet!',                             origin:'Having two left feet means inability to coordinate',                                     tags:['clumsy','dancing','funny'] },
  { id:'b19', idiom:'shoulder the blame',              meaning:'accept responsibility for something wrong',      serbian:'preuzeti odgovornost / krivnju',       category:'body',     level:'B2', example:'He shouldered the blame for the team\'s failure.',                           origin:'Carrying a burden on your shoulders',                                                    tags:['responsibility','blame','serious'] },
  { id:'b20', idiom:'a gut feeling',                   meaning:'a strong instinct or intuition',                 serbian:'osjećaj iz utrobe / šesto čulo',       category:'body',     level:'B1', example:'I had a gut feeling something was wrong.',                                    origin:'Physical sensation of instinct in the stomach',                                          tags:['instinct','feeling','intuition'] },

  // ── ANIMAL ─────────────────────────────────────────────────────────────────
  { id:'a1',  idiom:'let the cat out of the bag',      meaning:'accidentally reveal a secret',                   serbian:'odati tajnu',                          category:'animal',   level:'A2', example:'She let the cat out of the bag about the surprise party.',                   origin:'From medieval markets where merchants put cats instead of pigs in bags',                 tags:['secret','reveal','mistake'] },
  { id:'a2',  idiom:'it\'s raining cats and dogs',     meaning:'it is raining very heavily',                     serbian:'lije kao iz kabla',                    category:'animal',   level:'A2', example:'Take an umbrella — it\'s raining cats and dogs outside.',                   origin:'Old Norse mythology — cats symbolised rain, dogs symbolised wind',                       tags:['weather','rain','informal'] },
  { id:'a3',  idiom:'kill two birds with one stone',   meaning:'achieve two things with one action',             serbian:'ubiti dvije muhe jednim udarcem',      category:'animal',   level:'A2', example:'I\'ll visit my friend and pick up the parcel — killing two birds with one stone.', origin:'Literal stone throwing to kill two birds at once',                          tags:['efficiency','smart','informal'] },
  { id:'a4',  idiom:'the elephant in the room',        meaning:'an obvious problem nobody wants to discuss',     serbian:'slon u sobi / tabu tema',             category:'animal',   level:'B1', example:'Nobody mentioned his drinking — it was the elephant in the room.',            origin:'An elephant in a room would be impossible to ignore but uncomfortable to address',       tags:['problem','avoidance','serious'] },
  { id:'a5',  idiom:'hold your horses',                meaning:'slow down or wait a moment',                     serbian:'polako / ne žuri',                    category:'animal',   level:'A2', example:'Hold your horses! Let me explain before you make a decision.',               origin:'From riding — pulling back on horse reins to stop',                                      tags:['wait','calm','informal'] },
  { id:'a6',  idiom:'bite the hand that feeds you',    meaning:'harm someone who helps you',                     serbian:'pljuvati u bunar iz kojeg piješ',      category:'animal',   level:'B2', example:'Criticising your employer publicly is biting the hand that feeds you.',        origin:'Dogs that bite their owners after being fed',                                            tags:['betrayal','ingratitude','serious'] },
  { id:'a7',  idiom:'a wolf in sheep\'s clothing',     meaning:'someone dangerous who appears harmless',         serbian:'vuk u jagnjeće kože',                 category:'animal',   level:'B1', example:'Be careful of him — he seems kind but he\'s a wolf in sheep\'s clothing.',   origin:'Biblical — Matthew 7:15',                                                                tags:['deception','danger','warning'] },
  { id:'a8',  idiom:'the straw that broke the camel\'s back', meaning:'the final problem that causes a breakdown', serbian:'kap koja je prelila čašu',          category:'animal',   level:'B2', example:'His comment was the straw that broke the camel\'s back.',                     origin:'A camel can carry much weight, but one final straw breaks it',                           tags:['limit','breaking point','serious'] },
  { id:'a9',  idiom:'once in a blue moon',             meaning:'very rarely',                                    serbian:'jednom u sto godina',                  category:'animal',   level:'A2', example:'I only eat fast food once in a blue moon.',                                  origin:'A blue moon is the rare second full moon in a month',                                    tags:['rare','frequency','informal'] },
  { id:'a10', idiom:'barking up the wrong tree',       meaning:'pursuing the wrong course of action',            serbian:'ići pogrešnim tragom',                category:'animal',   level:'B1', example:'If you think I took your pen, you\'re barking up the wrong tree.',           origin:'A dog barking at a tree where the prey has already escaped',                             tags:['mistake','wrong','informal'] },
  { id:'a11', idiom:'let sleeping dogs lie',           meaning:'avoid bringing up old problems',                 serbian:'ne buditi uspavane lavove',           category:'animal',   level:'B1', example:'Don\'t mention the argument — let sleeping dogs lie.',                      origin:'Disturbing a sleeping dog might make it aggressive',                                     tags:['avoid','past','warning'] },
  { id:'a12', idiom:'cry wolf',                        meaning:'raise false alarms repeatedly',                  serbian:'lažno uzbunjivati',                   category:'animal',   level:'B1', example:'She cried wolf so often that nobody believed her when it was real.',         origin:'Aesop\'s fable of the shepherd boy who falsely cried wolf',                             tags:['lie','alarm','trust'] },
  { id:'a13', idiom:'straight from the horse\'s mouth',meaning:'directly from the original source',              serbian:'iz prve ruke / iz prve usta',          category:'animal',   level:'B1', example:'I heard it straight from the horse\'s mouth — the boss is leaving.',         origin:'Checking a horse\'s teeth to determine its age reliably',                               tags:['source','direct','reliable'] },
  { id:'a14', idiom:'a dark horse',                   meaning:'an unknown person who does better than expected', serbian:'autsajder koji iznenadi',              category:'animal',   level:'B2', example:'Nobody expected her to win — she was a complete dark horse.',                origin:'Horse racing — an unknown horse that unexpectedly wins',                                 tags:['surprise','competition','sport'] },
  { id:'a15', idiom:'kill the golden goose',           meaning:'destroy a source of profit through greed',       serbian:'ubiti koku koja nosi zlatna jaja',     category:'animal',   level:'B2', example:'Raising prices that much would kill the golden goose.',                      origin:'Aesop\'s fable of the goose that laid golden eggs',                                     tags:['greed','business','warning'] },
  { id:'a16', idiom:'smell a rat',                    meaning:'suspect that something is wrong',                 serbian:'osjetiti da nešto nije u redu',        category:'animal',   level:'B1', example:'When she didn\'t show up, I smelled a rat.',                                 origin:'Rats have a distinctive smell and were associated with danger',                          tags:['suspicion','doubt','informal'] },
  { id:'a17', idiom:'the lion\'s share',              meaning:'the largest part of something',                   serbian:'lavovski udio',                        category:'animal',   level:'B1', example:'The CEO took the lion\'s share of the bonus.',                               origin:'Aesop\'s fable where the lion took most of the shared prey',                            tags:['portion','unfair','amount'] },
  { id:'a18', idiom:'take the bull by the horns',     meaning:'deal with a difficult situation directly',        serbian:'uhvatiti bika za rogove',              category:'animal',   level:'B1', example:'She decided to take the bull by the horns and confront him.',                origin:'Rodeo — grabbing a charging bull\'s horns to stop it',                                  tags:['brave','direct','problem'] },
  { id:'a19', idiom:'have a bee in your bonnet',      meaning:'be obsessed with an idea',                        serbian:'imati fiksnu ideju',                   category:'animal',   level:'B2', example:'He has a bee in his bonnet about conspiracy theories.',                      origin:'A bee trapped in a hat would make constant buzzing noise',                              tags:['obsession','fixation','informal'] },
  { id:'a20', idiom:'a fish out of water',            meaning:'someone in an unfamiliar and uncomfortable situation', serbian:'biti riba na suhom',             category:'animal',   level:'B1', example:'At the formal dinner, she felt like a fish out of water.',                   origin:'A fish cannot survive or function outside water',                                        tags:['uncomfortable','unfamiliar','feelings'] },

  // ── COLOR ──────────────────────────────────────────────────────────────────
  { id:'c1',  idiom:'out of the blue',                meaning:'unexpectedly and suddenly',                       serbian:'iz vedra neba',                        category:'color',    level:'A2', example:'Out of the blue, she received a job offer from New York.',                   origin:'A bolt of lightning from a clear blue sky — unexpected',                                 tags:['unexpected','sudden','informal'] },
  { id:'c2',  idiom:'green with envy',                meaning:'feeling very jealous',                            serbian:'zelen od zavisti',                     category:'color',    level:'A2', example:'She was green with envy when she saw his new car.',                         origin:'Green was historically associated with jealousy and sickness',                           tags:['jealous','feelings','negative'] },
  { id:'c3',  idiom:'in the red',                     meaning:'in debt or losing money',                         serbian:'u minusu',                             category:'color',    level:'B1', example:'The company has been in the red for three years.',                           origin:'Accountants wrote losses in red ink',                                                    tags:['money','debt','business'] },
  { id:'c4',  idiom:'in the black',                   meaning:'profitable, not in debt',                         serbian:'u plusu / u dobitku',                  category:'color',    level:'B1', example:'After difficult years, the business is finally in the black.',                origin:'Accountants wrote profits in black ink',                                                 tags:['money','profit','business'] },
  { id:'c5',  idiom:'catch someone red-handed',       meaning:'catch someone in the act of doing something wrong', serbian:'uhvatiti na djelu',                 category:'color',    level:'B1', example:'They caught the thief red-handed with the stolen goods.',                   origin:'From blood on hands after a crime',                                                      tags:['crime','caught','justice'] },
  { id:'c6',  idiom:'a grey area',                    meaning:'a situation that is unclear or uncertain',        serbian:'siva zona',                            category:'color',    level:'B1', example:'Whether that is legal is a grey area.',                                     origin:'Grey is between black (wrong) and white (right)',                                        tags:['unclear','uncertain','moral'] },
  { id:'c7',  idiom:'show your true colours',         meaning:'reveal your real character, usually negative',    serbian:'pokazati pravo lice',                  category:'color',    level:'B1', example:'He showed his true colours when things got difficult.',                     origin:'Ships used to fly false flags and reveal true flag in battle',                           tags:['reveal','character','negative'] },
  { id:'c8',  idiom:'give someone the green light',   meaning:'give permission to proceed',                      serbian:'dati zeleno svjetlo',                  category:'color',    level:'A2', example:'The manager gave the green light to start the project.',                    origin:'Traffic lights — green means go',                                                        tags:['permission','proceed','work'] },
  { id:'c9',  idiom:'born with a silver spoon',       meaning:'born into a wealthy family',                      serbian:'roditi se u imućnoj obitelji',          category:'color',    level:'B1', example:'She was born with a silver spoon — her family is very rich.',                origin:'Wealthy families gave silver spoons as christening gifts',                               tags:['wealth','privilege','background'] },
  { id:'c10', idiom:'a golden opportunity',           meaning:'a very good chance that should not be missed',   serbian:'zlatna prilika',                       category:'color',    level:'A2', example:'This job offer is a golden opportunity — don\'t miss it.',                  origin:'Gold as symbol of something extremely valuable',                                         tags:['opportunity','chance','positive'] },
  { id:'c11', idiom:'tickled pink',                   meaning:'very pleased or amused',                          serbian:'biti jako zadovoljan / sretan',        category:'color',    level:'B1', example:'She was tickled pink when she got the promotion.',                          origin:'Pink cheeks from laughing or excitement',                                                tags:['happy','pleased','informal'] },
  { id:'c12', idiom:'have a black thumb',             meaning:'be bad at growing plants',                        serbian:'ubijati biljke',                       category:'color',    level:'B1', example:'Don\'t ask me to water your plants — I have a black thumb.',                 origin:'Opposite of "green thumb" — naturally good at gardening',                               tags:['gardening','skill','negative'] },
  { id:'c13', idiom:'a white lie',                    meaning:'a harmless lie told to avoid hurting feelings',   serbian:'bijela laž',                          category:'color',    level:'A2', example:'I told a white lie — said her dress looked great.',                         origin:'White traditionally symbolises purity and innocence',                                    tags:['lie','kindness','ethics'] },
  { id:'c14', idiom:'paint the town red',             meaning:'go out and celebrate wildly',                     serbian:'proslaviti se / provesti se divlje',   category:'color',    level:'B1', example:'It\'s his birthday — let\'s paint the town red!',                           origin:'Possibly from an old American story about a destructive party',                          tags:['celebrate','party','fun'] },
  { id:'c15', idiom:'in a grey area',                 meaning:'in a situation that is morally or legally unclear', serbian:'u sivoj zoni',                      category:'color',    level:'B1', example:'The tax arrangement was in a grey area legally.',                            origin:'Grey as the colour between black and white',                                             tags:['unclear','legal','moral'] },

  // ── BUSINESS ───────────────────────────────────────────────────────────────
  { id:'biz1',  idiom:'back to the drawing board',    meaning:'start over after a failure',                      serbian:'krenuti od nule',                      category:'business', level:'B1', example:'The plan failed completely — it\'s back to the drawing board.',               origin:'Literal drawing board where architects and designers plan',                              tags:['failure','restart','work'] },
  { id:'biz2',  idiom:'think outside the box',        meaning:'think creatively and differently',                 serbian:'razmišljati izvan okvira',            category:'business', level:'B1', example:'We need to think outside the box to solve this problem.',                    origin:'From a puzzle where the solution requires drawing lines outside a 3×3 box',             tags:['creative','innovation','work'] },
  { id:'biz3',  idiom:'touch base',                   meaning:'briefly contact someone to check in',             serbian:'stupiti u kontakt',                    category:'business', level:'B1', example:'I\'ll touch base with you next week to see how things are going.',           origin:'From baseball — touching base to be safe',                                               tags:['contact','communication','work'] },
  { id:'biz4',  idiom:'get the ball rolling',         meaning:'start something moving or happening',             serbian:'pokrenuti stvari',                     category:'business', level:'B1', example:'Let\'s get the ball rolling on this project.',                               origin:'From ball sports — getting the ball moving starts the game',                             tags:['start','begin','work'] },
  { id:'biz5',  idiom:'on the same page',             meaning:'in agreement and understanding',                   serbian:'biti na istoj valnoj duljini',         category:'business', level:'B1', example:'Before we start, let\'s make sure we\'re all on the same page.',            origin:'Literally reading the same page of a document',                                          tags:['agree','communication','work'] },
  { id:'biz6',  idiom:'go the extra mile',            meaning:'make more effort than required',                   serbian:'dati sve od sebe i više',             category:'business', level:'B1', example:'She always goes the extra mile for her customers.',                          origin:'Biblical — being forced to carry a pack one mile, choosing to go two',                   tags:['effort','dedication','positive'] },
  { id:'biz7',  idiom:'hit the ground running',       meaning:'start quickly and energetically',                  serbian:'krenuti puno parom',                   category:'business', level:'B2', example:'She hit the ground running in her new role.',                                origin:'Military — parachuting into action and running immediately on landing',                   tags:['start','energy','work'] },
  { id:'biz8',  idiom:'low-hanging fruit',            meaning:'the easiest goals to achieve first',               serbian:'najlakši ciljevi',                    category:'business', level:'B2', example:'Let\'s pick the low-hanging fruit before tackling bigger problems.',          origin:'Fruit at the bottom of a tree — easiest to reach',                                       tags:['easy','strategy','work'] },
  { id:'biz9',  idiom:'move the goalposts',           meaning:'change the rules or expectations unfairly',        serbian:'pomicati ciljeve',                     category:'business', level:'B2', example:'They keep moving the goalposts — I can never satisfy them.',                 origin:'Literally moving football goalposts to make scoring impossible',                         tags:['unfair','change','frustration'] },
  { id:'biz10', idiom:'a ballpark figure',            meaning:'a rough estimate',                                  serbian:'okvirna brojka',                      category:'business', level:'B1', example:'Give me a ballpark figure for the cost.',                                    origin:'From baseball — a rough estimate of crowd size in a ballpark',                          tags:['estimate','number','informal'] },
  { id:'biz11', idiom:'burn bridges',                 meaning:'permanently damage a relationship',                serbian:'spaljivati mostove',                   category:'business', level:'B1', example:'Don\'t burn bridges when you leave a job.',                                  origin:'Burning bridges cuts off retreat and future connection',                                 tags:['relationship','warning','permanent'] },
  { id:'biz12', idiom:'call it a day',                meaning:'stop working for the day',                         serbian:'završiti za danas',                    category:'business', level:'A2', example:'I\'m exhausted — let\'s call it a day.',                                    origin:'Deciding the working day is over',                                                       tags:['finish','work','informal'] },
  { id:'biz13', idiom:'cut corners',                  meaning:'do something with less effort or cost to save time', serbian:'ići linijom manjeg otpora',         category:'business', level:'B1', example:'They cut corners on safety to save money.',                                  origin:'Taking the shortest path by cutting around corners',                                     tags:['shortcuts','quality','warning'] },
  { id:'biz14', idiom:'in the pipeline',              meaning:'being planned or developed',                        serbian:'u planu / u pripremi',               category:'business', level:'B1', example:'We have several new products in the pipeline.',                             origin:'Oil pipelines — things being prepared for delivery',                                     tags:['plan','future','work'] },
  { id:'biz15', idiom:'raise the bar',                meaning:'set higher standards',                              serbian:'podignuti ljestvicu',                 category:'business', level:'B1', example:'This product launch has raised the bar for the industry.',                  origin:'High jump — raising the bar makes it harder to clear',                                  tags:['standards','improvement','positive'] },
  { id:'biz16', idiom:'the bottom line',              meaning:'the most important point or final result',          serbian:'suština / krajnji rezultat',          category:'business', level:'B1', example:'The bottom line is that we need to cut costs.',                             origin:'The final line in financial accounts showing profit or loss',                            tags:['important','finance','conclusion'] },
  { id:'biz17', idiom:'take something offline',       meaning:'discuss something privately, not in the meeting',  serbian:'razgovarati nasamo',                  category:'business', level:'B2', example:'Let\'s take this discussion offline after the meeting.',                     origin:'Moving from public online discussion to private conversation',                           tags:['private','meeting','work'] },
  { id:'biz18', idiom:'a level playing field',        meaning:'a situation where everyone has equal opportunity',  serbian:'ravnopravni uvjeti',                  category:'business', level:'B2', example:'We need a level playing field for all competitors.',                        origin:'Sports field that is flat — not giving any team an advantage',                           tags:['fair','equal','competition'] },
  { id:'biz19', idiom:'cut to the chase',             meaning:'get to the point without wasting time',             serbian:'prijeći na stvar',                    category:'business', level:'B1', example:'Let\'s cut to the chase — do you want the job or not?',                   origin:'Old films often cut from scenes to action chase sequences',                              tags:['direct','time','communication'] },
  { id:'biz20', idiom:'step up to the plate',         meaning:'accept responsibility for a challenge',             serbian:'prihvatiti izazov / odgovornost',     category:'business', level:'B2', example:'When the manager left, she stepped up to the plate.',                       origin:'Baseball — stepping up to home plate to bat',                                            tags:['responsibility','challenge','brave'] },

  // ── FOOD ───────────────────────────────────────────────────────────────────
  { id:'f1',  idiom:'a piece of cake',                meaning:'something very easy to do',                       serbian:'mačji kašalj',                         category:'food',     level:'A2', example:'The exam was a piece of cake — I finished in 20 minutes.',                  origin:'Cakes were given as prizes in 19th century competitions — easy to win',                  tags:['easy','informal','positive'] },
  { id:'f2',  idiom:'spill the beans',                meaning:'reveal secret information',                        serbian:'odati tajnu / progovoriti',            category:'food',     level:'A2', example:'Someone spilled the beans about the surprise party.',                       origin:'Ancient Greek voting with beans — spilling them revealed the vote',                       tags:['secret','reveal','informal'] },
  { id:'f3',  idiom:'not my cup of tea',              meaning:'not something you enjoy or like',                   serbian:'nije moja stvar',                     category:'food',     level:'A2', example:'Horror films are not really my cup of tea.',                                origin:'British tea culture — tea being central to British preferences',                          tags:['preference','dislike','informal'] },
  { id:'f4',  idiom:'in a nutshell',                  meaning:'in a very brief summary',                          serbian:'ukratko / u kratkim crtama',          category:'food',     level:'B1', example:'In a nutshell, the project failed because of poor planning.',                 origin:'Shakespeare — a nutshell as the smallest possible container',                            tags:['summary','brief','formal'] },
  { id:'f5',  idiom:'have your cake and eat it too',  meaning:'want two incompatible things at the same time',   serbian:'i jesti i imati kolač',               category:'food',     level:'B1', example:'You can\'t have your cake and eat it too — choose one.',                    origin:'Once you eat a cake, you no longer have it',                                             tags:['greedy','impossible','choice'] },
  { id:'f6',  idiom:'sell like hot cakes',            meaning:'sell very quickly and in large numbers',           serbian:'ići kao halva',                        category:'food',     level:'B1', example:'Her new book is selling like hot cakes.',                                   origin:'Hot cakes sold quickly at fairs and markets',                                            tags:['popular','sales','positive'] },
  { id:'f7',  idiom:'bread and butter',               meaning:'the basic or most important part of something',    serbian:'osnova / kruh i maslac',              category:'food',     level:'B1', example:'Teaching is my bread and butter — it pays the bills.',                      origin:'Bread and butter as the most basic food staple',                                         tags:['basic','important','work'] },
  { id:'f8',  idiom:'a tough nut to crack',           meaning:'a difficult problem or person to deal with',       serbian:'tvrd orah',                            category:'food',     level:'B1', example:'Getting him to agree will be a tough nut to crack.',                       origin:'Some nuts have very hard shells and are difficult to open',                              tags:['difficult','challenge','problem'] },
  { id:'f9',  idiom:'the icing on the cake',          meaning:'an extra good thing added to something already good', serbian:'šlag na tortu',                    category:'food',     level:'B1', example:'Winning the award was the icing on the cake.',                              origin:'Icing makes an already good cake even better',                                           tags:['extra','positive','bonus'] },
  { id:'f10', idiom:'go bananas',                     meaning:'go crazy or become very excited or angry',          serbian:'poludjeti / izgubiti živce',          category:'food',     level:'A2', example:'The fans went bananas when their team scored.',                            origin:'Bananas associated with monkeys who act erratically',                                    tags:['crazy','excited','informal'] },
  { id:'f11', idiom:'cry over spilled milk',          meaning:'be upset about something that cannot be changed',  serbian:'plakati za prolijenim mlijekom',       category:'food',     level:'B1', example:'Don\'t cry over spilled milk — focus on what you can do.',                 origin:'Literally crying over milk that has been spilled — cannot be recovered',                 tags:['past','regret','accept'] },
  { id:'f12', idiom:'full of beans',                  meaning:'very lively and enthusiastic',                     serbian:'pun energije / živahan',              category:'food',     level:'B1', example:'She was full of beans at the meeting despite working all night.',           origin:'Beans as a source of energy and vitality',                                               tags:['energy','enthusiasm','positive'] },
  { id:'f13', idiom:'take something with a pinch of salt', meaning:'not fully believe something',                 serbian:'uzeti s rezervom',                    category:'food',     level:'B1', example:'Take what he says with a pinch of salt — he exaggerates.',                  origin:'Salt was used to make bad food palatable — lessening the impact',                        tags:['doubt','sceptical','advice'] },
  { id:'f14', idiom:'bite off more than you can chew', meaning:'take on more responsibility than you can handle', serbian:'zagristi više nego što možeš prožvakati', category:'food', level:'B1', example:'I bit off more than I could chew taking on that project alone.',            origin:'Literally taking too large a bite of food',                                              tags:['overcommit','work','warning'] },
  { id:'f15', idiom:'butter someone up',              meaning:'flatter someone to get what you want',             serbian:'mazati med oko usta',                  category:'food',     level:'B1', example:'He was buttering up the boss all week before asking for a raise.',           origin:'Offering butter (a luxury) as flattery',                                                 tags:['flattery','manipulation','informal'] },

  // ── SLANG ──────────────────────────────────────────────────────────────────
  { id:'s1',  idiom:'no cap',                         meaning:'no lie, seriously, I\'m not exaggerating',        serbian:'ozbiljno / bez laži',                  category:'slang',    level:'A2', example:'That concert was the best I\'ve ever seen, no cap.',                        origin:'"Cap" means lie in slang — "no cap" means no lie',                                       tags:['serious','truth','gen-z'] },
  { id:'s2',  idiom:'it hits different',              meaning:'it feels better or more meaningful than usual',   serbian:'drugačije / posebno djeluje',          category:'slang',    level:'A2', example:'Listening to this song at night just hits different.',                       origin:'Something affects you differently than expected',                                        tags:['feelings','experience','gen-z'] },
  { id:'s3',  idiom:'lowkey',                         meaning:'quietly, in a low-key way, or secretly',          serbian:'tiho / pomalo / diskretno',            category:'slang',    level:'A2', example:'I\'m lowkey obsessed with this new series.',                                 origin:'Low key = not dramatic or public',                                                       tags:['quiet','secret','gen-z'] },
  { id:'s4',  idiom:'highkey',                        meaning:'very much, openly, definitely',                   serbian:'jako / otvoreno / definitivno',        category:'slang',    level:'A2', example:'I highkey need a holiday right now.',                                       origin:'Opposite of lowkey — openly and intensely',                                              tags:['intense','open','gen-z'] },
  { id:'s5',  idiom:'slay',                           meaning:'do something impressively or look amazing',       serbian:'biti sjajan / izgledati super',        category:'slang',    level:'A2', example:'She absolutely slayed that presentation.',                                  origin:'From drag culture — slaying means winning or looking incredible',                        tags:['impress','amazing','gen-z'] },
  { id:'s6',  idiom:'it\'s giving',                  meaning:'it resembles or has the vibe of something',        serbian:'daje vibes / podsjeća na',            category:'slang',    level:'A2', example:'This café is giving Paris vibes.',                                          origin:'From drag culture — "giving the impression of"',                                         tags:['vibe','feeling','gen-z'] },
  { id:'s7',  idiom:'ate (that)',                     meaning:'did something perfectly, nailed it',              serbian:'savršeno odradio / i(s)pekao',        category:'slang',    level:'B1', example:'She totally ate that performance.',                                          origin:'From "ate and left no crumbs" — consumed everything perfectly',                          tags:['perfect','impressed','gen-z'] },
  { id:'s8',  idiom:'the tea',                        meaning:'the gossip or the truth about something',         serbian:'tračevi / prava priča',               category:'slang',    level:'A2', example:'Spill the tea — what happened at the party?',                               origin:'From "T" meaning truth in drag culture',                                                 tags:['gossip','truth','gen-z'] },
  { id:'s9',  idiom:'vibe check',                     meaning:'checking if the atmosphere or mood is good',      serbian:'provjera atmosfere',                   category:'slang',    level:'A2', example:'Vibe check — is everyone feeling good about this?',                       origin:'Checking the vibrational energy of a situation',                                         tags:['mood','atmosphere','gen-z'] },
  { id:'s10', idiom:'rent free',                      meaning:'something occupying your thoughts constantly',    serbian:'živi u tvojoj glavi besplatno',        category:'slang',    level:'B1', example:'That song has been living in my head rent free for days.',                   origin:'Living somewhere rent free — taking up space without paying',                            tags:['thoughts','obsession','funny'] },
  { id:'s11', idiom:'that\'s a W',                   meaning:'that\'s a win or success',                         serbian:'to je pobjeda / uspjeh',              category:'slang',    level:'A2', example:'You got the job? That\'s a huge W!',                                       origin:'W = Win in gaming culture',                                                              tags:['success','positive','gaming'] },
  { id:'s12', idiom:'that\'s an L',                  meaning:'that\'s a loss or failure',                        serbian:'to je gubitak / neuspjeh',            category:'slang',    level:'A2', example:'Missing that flight was a massive L.',                                    origin:'L = Loss in gaming culture',                                                             tags:['failure','negative','gaming'] },
  { id:'s13', idiom:'understood the assignment',      meaning:'did exactly what was needed perfectly',           serbian:'shvatio/la zadatak savršeno',         category:'slang',    level:'B1', example:'Her outfit for the gala? She understood the assignment.',                   origin:'Academic metaphor — understanding what was required',                                    tags:['perfect','impressed','gen-z'] },
  { id:'s14', idiom:'red flag',                       meaning:'a warning sign in a person or situation',         serbian:'crvena zastavica / znak upozorenja',   category:'slang',    level:'A2', example:'He cancelled three times in a row — that\'s a red flag.',                 origin:'Red flags as warning signals',                                                           tags:['warning','relationship','dating'] },
  { id:'s15', idiom:'green flag',                     meaning:'a positive sign in a person or situation',        serbian:'zelena zastavica / pozitivan znak',    category:'slang',    level:'A2', example:'He remembers your favourite food — total green flag.',                     origin:'Green flags as positive signals',                                                        tags:['positive','relationship','dating'] },
  { id:'s16', idiom:'main character energy',          meaning:'acting like you\'re the hero of your own story',  serbian:'energija glavnog lika',               category:'slang',    level:'B1', example:'She walked in with full main character energy.',                           origin:'From film/TV — the main character always gets the best moments',                         tags:['confidence','attitude','gen-z'] },
  { id:'s17', idiom:'touch grass',                    meaning:'go outside and experience real life',              serbian:'izaći van / odvojiti se od ekrana',    category:'slang',    level:'B1', example:'You\'ve been gaming for 12 hours — go touch grass.',                       origin:'Literally touching grass — experiencing nature instead of screens',                      tags:['outside','screen','funny'] },
  { id:'s18', idiom:'gaslighting',                    meaning:'manipulating someone into questioning their reality', serbian:'gaslighting / manipulacija',       category:'slang',    level:'B2', example:'He denied saying it even though she recorded him — total gaslighting.',     origin:'From the 1944 film "Gaslight" — a husband manipulates his wife',                        tags:['manipulation','psychology','serious'] },
  { id:'s19', idiom:'the audacity',                   meaning:'shocking nerve or boldness',                       serbian:'drskost / drzovitost',               category:'slang',    level:'B1', example:'She didn\'t apologise and asked for a raise? The audacity!',                origin:'Audacity meaning bold impudence',                                                        tags:['shocked','behaviour','informal'] },
  { id:'s20', idiom:'catch flights not feelings',     meaning:'focus on travel and fun, not romantic feelings',   serbian:'letjeti, ne zaljubljivati se',         category:'slang',    level:'B1', example:'She\'s not looking for a relationship — catch flights not feelings.',       origin:'Social media travel culture',                                                            tags:['relationship','travel','gen-z'] },

  // ── GENERAL ────────────────────────────────────────────────────────────────
  { id:'g1',  idiom:'under the weather',              meaning:'feeling slightly ill',                             serbian:'malo bolesno / nije mi dobro',         category:'general',  level:'A2', example:'I\'m feeling a bit under the weather today.',                              origin:'Sailors who felt ill were sent below deck — under the weather side of the ship',         tags:['sick','health','informal'] },
  { id:'g2',  idiom:'hit the nail on the head',       meaning:'describe exactly what is true or correct',        serbian:'pogoditi pravo u cilj',               category:'general',  level:'B1', example:'You hit the nail on the head with your analysis.',                          origin:'Literally hitting a nail precisely on its head',                                         tags:['correct','accurate','positive'] },
  { id:'g3',  idiom:'better late than never',         meaning:'it is better to do something late than not at all', serbian:'bolje ikad nego nikad',             category:'general',  level:'A2', example:'He finally apologised — better late than never.',                         origin:'Ancient proverb — doing something late is better than not doing it',                     tags:['time','late','proverb'] },
  { id:'g4',  idiom:'bite the dust',                  meaning:'fail, die, or be defeated',                       serbian:'zagristi prašinu / doživjeti neuspjeh', category:'general', level:'B1', example:'Another tech startup bites the dust.',                                    origin:'Cowboys falling from horses — face hitting the dusty ground',                            tags:['fail','end','informal'] },
  { id:'g5',  idiom:'beat around the bush',           meaning:'avoid saying something directly',                  serbian:'ići okolo / ne reći direktno',        category:'general',  level:'B1', example:'Stop beating around the bush — just tell me the truth.',                  origin:'Hunters beating bushes to flush out birds before direct hunting',                        tags:['indirect','communication','annoying'] },
  { id:'g6',  idiom:'actions speak louder than words', meaning:'what you do is more important than what you say', serbian:'djela govore glasnije od riječi',     category:'general',  level:'A2', example:'He promises to change but actions speak louder than words.',               origin:'Ancient proverb emphasising deeds over promises',                                        tags:['truth','proverb','wisdom'] },
  { id:'g7',  idiom:'curiosity killed the cat',       meaning:'being too curious can lead to trouble',            serbian:'znatiželja ubija mačku',              category:'general',  level:'B1', example:'I know you want to know but curiosity killed the cat.',                   origin:'Originally "care killed the cat" — warning against excessive worry',                    tags:['warning','curiosity','proverb'] },
  { id:'g8',  idiom:'every cloud has a silver lining', meaning:'every bad situation has something positive',      serbian:'svako zlo za neko dobro',             category:'general',  level:'A2', example:'I lost the job but got a better one — every cloud has a silver lining.',  origin:'Clouds with sunlight behind them have bright silver edges',                              tags:['positive','optimism','comfort'] },
  { id:'g9',  idiom:'the ball is in your court',      meaning:'it is your turn to take action or make a decision', serbian:'lopta je na tvojoj strani',          category:'general',  level:'B1', example:'I\'ve done my part — the ball is in your court now.',                     origin:'Tennis — the ball is literally in your side of the court',                              tags:['decision','responsibility','action'] },
  { id:'g10', idiom:'break the ice',                  meaning:'do or say something to make a situation less awkward', serbian:'probiti led',                    category:'general',  level:'A2', example:'He told a joke to break the ice at the start of the meeting.',            origin:'Icebreaker ships break ice to open passages — creating an opening',                      tags:['social','awkward','informal'] },
]

export const IDIOM_CATEGORIES = [
  { id: 'all',      label: 'All',      color: '#3b82f6' },
  { id: 'body',     label: 'Body',     color: '#ef4444' },
  { id: 'animal',   label: 'Animal',   color: '#f97316' },
  { id: 'color',    label: 'Color',    color: '#8b5cf6' },
  { id: 'business', label: 'Business', color: '#3b82f6' },
  { id: 'food',     label: 'Food',     color: '#f59e0b' },
  { id: 'slang',    label: 'Slang',    color: '#ec4899' },
  { id: 'general',  label: 'General',  color: '#10b981' },
]

export const CATEGORY_COLOR = {
  body: '#ef4444', animal: '#f97316', color: '#8b5cf6',
  business: '#3b82f6', food: '#f59e0b', slang: '#ec4899', general: '#10b981',
}

export function getIdiomOfDay() {
  const dayIdx = Math.floor(Date.now() / 86400000)
  return IDIOMS[dayIdx % IDIOMS.length]
}

export function findIdiomsForWord(word) {
  if (!word) return []
  const w = word.toLowerCase()
  return IDIOMS.filter(i => i.idiom.toLowerCase().split(/\s+/).includes(w))
}
