export const VERB_LEVELS = ['A1', 'A2', 'B1', 'B2'];

export const PHRASAL_CATEGORIES = ['general', 'movement', 'communication', 'relationships', 'work'];

export const IRREGULAR_VERBS = [
  // A1 verbs (28)
  {
    base: 'be',
    past: 'was/were',
    participle: 'been',
    serbian: 'biti',
    level: 'A1',
    example: 'I am very happy today.',
    pastExample: 'She was tired after the long journey.',
    participleExample: 'He has been a teacher for ten years.',
  },
  {
    base: 'have',
    past: 'had',
    participle: 'had',
    serbian: 'imati',
    level: 'A1',
    example: 'I have two brothers.',
    pastExample: 'She had a great idea yesterday.',
    participleExample: 'They have had many problems this week.',
  },
  {
    base: 'do',
    past: 'did',
    participle: 'done',
    serbian: 'raditi',
    level: 'A1',
    example: 'I do my homework every evening.',
    pastExample: 'He did the dishes after dinner.',
    participleExample: 'She has done an excellent job.',
  },
  {
    base: 'go',
    past: 'went',
    participle: 'gone',
    serbian: 'ići',
    level: 'A1',
    example: 'We go to school every day.',
    pastExample: 'They went to the beach last weekend.',
    participleExample: 'She has gone to the store.',
  },
  {
    base: 'say',
    past: 'said',
    participle: 'said',
    serbian: 'reći',
    level: 'A1',
    example: 'I say hello to my neighbours.',
    pastExample: 'He said something important at the meeting.',
    participleExample: 'She has said everything she wanted.',
  },
  {
    base: 'get',
    past: 'got',
    participle: 'got',
    serbian: 'dobiti',
    level: 'A1',
    example: 'I get up early every morning.',
    pastExample: 'She got a letter from her friend.',
    participleExample: 'He has got a new job.',
  },
  {
    base: 'make',
    past: 'made',
    participle: 'made',
    serbian: 'napraviti',
    level: 'A1',
    example: 'I make breakfast every morning.',
    pastExample: 'She made a delicious cake yesterday.',
    participleExample: 'He has made a big mistake.',
  },
  {
    base: 'know',
    past: 'knew',
    participle: 'known',
    serbian: 'znati',
    level: 'A1',
    example: 'I know how to cook pasta.',
    pastExample: 'She knew the answer immediately.',
    participleExample: 'He has known her since childhood.',
  },
  {
    base: 'think',
    past: 'thought',
    participle: 'thought',
    serbian: 'misliti',
    level: 'A1',
    example: 'I think this is a great idea.',
    pastExample: 'She thought about the problem all night.',
    participleExample: 'He has thought of a solution.',
  },
  {
    base: 'take',
    past: 'took',
    participle: 'taken',
    serbian: 'uzeti',
    level: 'A1',
    example: 'I take the bus to work.',
    pastExample: 'She took her umbrella because it was raining.',
    participleExample: 'He has taken the wrong road.',
  },
  {
    base: 'see',
    past: 'saw',
    participle: 'seen',
    serbian: 'vidjeti',
    level: 'A1',
    example: 'I see the mountains from my window.',
    pastExample: 'She saw a beautiful sunset yesterday.',
    participleExample: 'Have you seen the new film?',
  },
  {
    base: 'come',
    past: 'came',
    participle: 'come',
    serbian: 'doći',
    level: 'A1',
    example: 'They come to visit us every summer.',
    pastExample: 'She came home late last night.',
    participleExample: 'He has come a long way to be here.',
  },
  {
    base: 'give',
    past: 'gave',
    participle: 'given',
    serbian: 'dati',
    level: 'A1',
    example: 'I give my friend a call every week.',
    pastExample: 'She gave him a birthday present.',
    participleExample: 'He has given us all the information we need.',
  },
  {
    base: 'find',
    past: 'found',
    participle: 'found',
    serbian: 'pronaći',
    level: 'A1',
    example: 'I find this lesson very interesting.',
    pastExample: 'She found her keys under the sofa.',
    participleExample: 'He has found a great solution to the problem.',
  },
  {
    base: 'tell',
    past: 'told',
    participle: 'told',
    serbian: 'reći/pričati',
    level: 'A1',
    example: 'I tell my children a story every night.',
    pastExample: 'She told me the truth about what happened.',
    participleExample: 'He has told everyone about the news.',
  },
  {
    base: 'buy',
    past: 'bought',
    participle: 'bought',
    serbian: 'kupiti',
    level: 'A1',
    example: 'I buy fresh vegetables at the market.',
    pastExample: 'She bought a new dress for the party.',
    participleExample: 'He has bought a new car this year.',
  },
  {
    base: 'eat',
    past: 'ate',
    participle: 'eaten',
    serbian: 'jesti',
    level: 'A1',
    example: 'I eat breakfast at seven o\'clock.',
    pastExample: 'She ate a sandwich for lunch.',
    participleExample: 'He has eaten all the cake.',
  },
  {
    base: 'drink',
    past: 'drank',
    participle: 'drunk',
    serbian: 'piti',
    level: 'A1',
    example: 'I drink two cups of coffee every morning.',
    pastExample: 'She drank a glass of water after the run.',
    participleExample: 'He has drunk too much coffee today.',
  },
  {
    base: 'write',
    past: 'wrote',
    participle: 'written',
    serbian: 'pisati',
    level: 'A1',
    example: 'I write in my journal every evening.',
    pastExample: 'She wrote a long email to her friend.',
    participleExample: 'He has written three novels so far.',
  },
  {
    base: 'read',
    past: 'read',
    participle: 'read',
    serbian: 'čitati',
    level: 'A1',
    example: 'I read a book before bed every night.',
    pastExample: 'She read the instructions carefully.',
    participleExample: 'He has read all the books on that shelf.',
  },
  {
    base: 'run',
    past: 'ran',
    participle: 'run',
    serbian: 'trčati',
    level: 'A1',
    example: 'I run in the park every morning.',
    pastExample: 'She ran five kilometres yesterday.',
    participleExample: 'He has run in many marathons.',
  },
  {
    base: 'swim',
    past: 'swam',
    participle: 'swum',
    serbian: 'plivati',
    level: 'A1',
    example: 'I swim in the sea every summer.',
    pastExample: 'She swam across the lake last weekend.',
    participleExample: 'He has swum competitively since he was a child.',
  },
  {
    base: 'drive',
    past: 'drove',
    participle: 'driven',
    serbian: 'voziti',
    level: 'A1',
    example: 'I drive to work every day.',
    pastExample: 'She drove all night to reach the city.',
    participleExample: 'He has driven that car for ten years.',
  },
  {
    base: 'fly',
    past: 'flew',
    participle: 'flown',
    serbian: 'letjeti',
    level: 'A1',
    example: 'Birds fly south in the winter.',
    pastExample: 'She flew to Paris for the weekend.',
    participleExample: 'He has flown over a hundred times for work.',
  },
  {
    base: 'break',
    past: 'broke',
    participle: 'broken',
    serbian: 'slomiti',
    level: 'A1',
    example: 'Be careful not to break the glass.',
    pastExample: 'She broke her arm during the fall.',
    participleExample: 'Someone has broken the window.',
  },
  {
    base: 'speak',
    past: 'spoke',
    participle: 'spoken',
    serbian: 'govoriti',
    level: 'A1',
    example: 'I speak English and Spanish.',
    pastExample: 'She spoke to the manager about the problem.',
    participleExample: 'He has spoken at many conferences.',
  },
  {
    base: 'meet',
    past: 'met',
    participle: 'met',
    serbian: 'upoznati',
    level: 'A1',
    example: 'I meet my friends on Fridays.',
    pastExample: 'She met her husband at university.',
    participleExample: 'They have met before at a conference.',
  },
  {
    base: 'leave',
    past: 'left',
    participle: 'left',
    serbian: 'otići/ostaviti',
    level: 'A1',
    example: 'I leave the house at eight every morning.',
    pastExample: 'She left her bag on the bus.',
    participleExample: 'He has left already, I am afraid.',
  },

  // A2 verbs (30)
  {
    base: 'bring',
    past: 'brought',
    participle: 'brought',
    serbian: 'donijeti',
    level: 'A2',
    example: 'I bring my lunch to work every day.',
    pastExample: 'She brought flowers to the hospital.',
    participleExample: 'He has brought good news from the office.',
  },
  {
    base: 'build',
    past: 'built',
    participle: 'built',
    serbian: 'izgraditi',
    level: 'A2',
    example: 'They build houses in this neighbourhood.',
    pastExample: 'She built a sandcastle on the beach.',
    participleExample: 'He has built a successful career over the years.',
  },
  {
    base: 'burn',
    past: 'burnt',
    participle: 'burnt',
    serbian: 'gorjeti',
    level: 'A2',
    example: 'The candles burn all evening.',
    pastExample: 'She burnt the toast this morning.',
    participleExample: 'The old barn has burnt to the ground.',
  },
  {
    base: 'catch',
    past: 'caught',
    participle: 'caught',
    serbian: 'uhvatiti',
    level: 'A2',
    example: 'I catch the early train every day.',
    pastExample: 'She caught a cold last week.',
    participleExample: 'He has caught the thief red-handed.',
  },
  {
    base: 'choose',
    past: 'chose',
    participle: 'chosen',
    serbian: 'odabrati',
    level: 'A2',
    example: 'I choose carefully what I eat.',
    pastExample: 'She chose the blue dress for the party.',
    participleExample: 'He has chosen a different career path.',
  },
  {
    base: 'cut',
    past: 'cut',
    participle: 'cut',
    serbian: 'rezati',
    level: 'A2',
    example: 'I cut the vegetables before cooking.',
    pastExample: 'She cut her finger while chopping onions.',
    participleExample: 'He has cut the paper into small pieces.',
  },
  {
    base: 'draw',
    past: 'drew',
    participle: 'drawn',
    serbian: 'crtati',
    level: 'A2',
    example: 'I draw in my sketchbook every week.',
    pastExample: 'She drew a beautiful portrait of her friend.',
    participleExample: 'He has drawn the same scene several times.',
  },
  {
    base: 'dream',
    past: 'dreamt',
    participle: 'dreamt',
    serbian: 'sanjati',
    level: 'A2',
    example: 'I often dream about travelling the world.',
    pastExample: 'She dreamt about her old school last night.',
    participleExample: 'He has dreamt of becoming a pilot since he was young.',
  },
  {
    base: 'fall',
    past: 'fell',
    participle: 'fallen',
    serbian: 'pasti',
    level: 'A2',
    example: 'Leaves fall from the trees in autumn.',
    pastExample: 'She fell off her bike and hurt her knee.',
    participleExample: 'The price of petrol has fallen this month.',
  },
  {
    base: 'feel',
    past: 'felt',
    participle: 'felt',
    serbian: 'osjećati',
    level: 'A2',
    example: 'I feel great after a good night\'s sleep.',
    pastExample: 'She felt nervous before the presentation.',
    participleExample: 'He has felt much better since starting the treatment.',
  },
  {
    base: 'fight',
    past: 'fought',
    participle: 'fought',
    serbian: 'boriti se',
    level: 'A2',
    example: 'They fight for justice every day.',
    pastExample: 'She fought hard to keep her job.',
    participleExample: 'He has fought in many legal battles.',
  },
  {
    base: 'forget',
    past: 'forgot',
    participle: 'forgotten',
    serbian: 'zaboraviti',
    level: 'A2',
    example: 'I forget names very easily.',
    pastExample: 'She forgot her umbrella at the office.',
    participleExample: 'He has forgotten where he put his keys.',
  },
  {
    base: 'grow',
    past: 'grew',
    participle: 'grown',
    serbian: 'rasti',
    level: 'A2',
    example: 'Plants grow faster in the summer.',
    pastExample: 'She grew vegetables in her garden last year.',
    participleExample: 'The company has grown significantly this year.',
  },
  {
    base: 'hang',
    past: 'hung',
    participle: 'hung',
    serbian: 'vješati',
    level: 'A2',
    example: 'I hang my coat on the door.',
    pastExample: 'She hung the picture on the living room wall.',
    participleExample: 'He has hung new curtains in every room.',
  },
  {
    base: 'hear',
    past: 'heard',
    participle: 'heard',
    serbian: 'čuti',
    level: 'A2',
    example: 'I hear music coming from the next room.',
    pastExample: 'She heard a strange noise outside the window.',
    participleExample: 'Have you heard the latest news?',
  },
  {
    base: 'hide',
    past: 'hid',
    participle: 'hidden',
    serbian: 'sakriti',
    level: 'A2',
    example: 'The children love to hide in the garden.',
    pastExample: 'She hid the present under the bed.',
    participleExample: 'He has hidden the documents in a safe place.',
  },
  {
    base: 'hit',
    past: 'hit',
    participle: 'hit',
    serbian: 'udariti',
    level: 'A2',
    example: 'She hits the ball very hard.',
    pastExample: 'He hit his head on the low ceiling.',
    participleExample: 'The storm has hit the coastal town.',
  },
  {
    base: 'hold',
    past: 'held',
    participle: 'held',
    serbian: 'držati',
    level: 'A2',
    example: 'I hold the door open for others.',
    pastExample: 'She held her baby tightly.',
    participleExample: 'The company has held its annual conference.',
  },
  {
    base: 'hurt',
    past: 'hurt',
    participle: 'hurt',
    serbian: 'povrijediti',
    level: 'A2',
    example: 'It hurts when I walk on this foot.',
    pastExample: 'She hurt her ankle during football practice.',
    participleExample: 'He has hurt his back lifting heavy boxes.',
  },
  {
    base: 'keep',
    past: 'kept',
    participle: 'kept',
    serbian: 'čuvati',
    level: 'A2',
    example: 'I keep a diary to record my thoughts.',
    pastExample: 'She kept all the letters from her grandmother.',
    participleExample: 'He has kept his promise to help them.',
  },
  {
    base: 'learn',
    past: 'learnt',
    participle: 'learnt',
    serbian: 'naučiti',
    level: 'A2',
    example: 'I learn something new every day.',
    pastExample: 'She learnt to play the piano as a child.',
    participleExample: 'He has learnt a great deal from this experience.',
  },
  {
    base: 'lead',
    past: 'led',
    participle: 'led',
    serbian: 'voditi',
    level: 'A2',
    example: 'She leads the team with great confidence.',
    pastExample: 'He led the expedition through the mountains.',
    participleExample: 'She has led the department for three years.',
  },
  {
    base: 'lose',
    past: 'lost',
    participle: 'lost',
    serbian: 'izgubiti',
    level: 'A2',
    example: 'I always lose my glasses.',
    pastExample: 'She lost her wallet on the train.',
    participleExample: 'He has lost his confidence after the failure.',
  },
  {
    base: 'mean',
    past: 'meant',
    participle: 'meant',
    serbian: 'značiti',
    level: 'A2',
    example: 'This word means something different in British English.',
    pastExample: 'She meant to call you but forgot.',
    participleExample: 'What has he meant by that strange comment?',
  },
  {
    base: 'pay',
    past: 'paid',
    participle: 'paid',
    serbian: 'platiti',
    level: 'A2',
    example: 'I pay my bills online every month.',
    pastExample: 'She paid for the meal at the restaurant.',
    participleExample: 'He has paid off all his debts.',
  },
  {
    base: 'put',
    past: 'put',
    participle: 'put',
    serbian: 'staviti',
    level: 'A2',
    example: 'I put my keys on the table when I come home.',
    pastExample: 'She put the book back on the shelf.',
    participleExample: 'He has put a lot of effort into this project.',
  },
  {
    base: 'ride',
    past: 'rode',
    participle: 'ridden',
    serbian: 'jahati/voziti',
    level: 'A2',
    example: 'I ride my bike to the university.',
    pastExample: 'She rode a horse for the first time last summer.',
    participleExample: 'He has ridden motorcycles since he was eighteen.',
  },
  {
    base: 'ring',
    past: 'rang',
    participle: 'rung',
    serbian: 'zvoniti',
    level: 'A2',
    example: 'The bells ring every Sunday morning.',
    pastExample: 'She rang the doorbell and waited.',
    participleExample: 'The alarm has rung three times already.',
  },
  {
    base: 'rise',
    past: 'rose',
    participle: 'risen',
    serbian: 'ustati/rasti',
    level: 'A2',
    example: 'The sun rises in the east every morning.',
    pastExample: 'The temperature rose sharply during the afternoon.',
    participleExample: 'Prices have risen significantly this year.',
  },
  {
    base: 'sell',
    past: 'sold',
    participle: 'sold',
    serbian: 'prodati',
    level: 'A2',
    example: 'They sell fresh fruit at the local market.',
    pastExample: 'She sold her old car last month.',
    participleExample: 'He has sold hundreds of paintings over his career.',
  },

  // B1 verbs (30)
  {
    base: 'send',
    past: 'sent',
    participle: 'sent',
    serbian: 'poslati',
    level: 'B1',
    example: 'I send emails to clients every morning.',
    pastExample: 'She sent a package to her parents overseas.',
    participleExample: 'He has sent the report to the director.',
  },
  {
    base: 'set',
    past: 'set',
    participle: 'set',
    serbian: 'postaviti',
    level: 'B1',
    example: 'I set my alarm for six in the morning.',
    pastExample: 'She set the table for dinner.',
    participleExample: 'He has set a new world record.',
  },
  {
    base: 'shake',
    past: 'shook',
    participle: 'shaken',
    serbian: 'tresti',
    level: 'B1',
    example: 'I shake the bottle before drinking.',
    pastExample: 'She shook his hand firmly at the meeting.',
    participleExample: 'The earthquake has shaken the entire region.',
  },
  {
    base: 'shine',
    past: 'shone',
    participle: 'shone',
    serbian: 'sjajiti',
    level: 'B1',
    example: 'The sun shines brightly in the afternoon.',
    pastExample: 'Her eyes shone with excitement.',
    participleExample: 'The stars have shone all night long.',
  },
  {
    base: 'shoot',
    past: 'shot',
    participle: 'shot',
    serbian: 'pucati',
    level: 'B1',
    example: 'The hunters shoot at targets during practice.',
    pastExample: 'She shot a stunning photo at sunrise.',
    participleExample: 'The film has been shot in over twenty countries.',
  },
  {
    base: 'show',
    past: 'showed',
    participle: 'shown',
    serbian: 'pokazati',
    level: 'B1',
    example: 'I show my students how to solve problems.',
    pastExample: 'She showed me around the new office.',
    participleExample: 'He has shown great courage in difficult times.',
  },
  {
    base: 'shrink',
    past: 'shrank',
    participle: 'shrunk',
    serbian: 'skupiti se',
    level: 'B1',
    example: 'Wool jumpers shrink if you wash them in hot water.',
    pastExample: 'The wool sweater shrank in the dryer.',
    participleExample: 'The company\'s profits have shrunk this quarter.',
  },
  {
    base: 'shut',
    past: 'shut',
    participle: 'shut',
    serbian: 'zatvoriti',
    level: 'B1',
    example: 'I shut my laptop when I finish working.',
    pastExample: 'She shut the door quietly behind her.',
    participleExample: 'The office has shut early today.',
  },
  {
    base: 'sing',
    past: 'sang',
    participle: 'sung',
    serbian: 'pjevati',
    level: 'B1',
    example: 'She sings in the school choir every week.',
    pastExample: 'He sang a beautiful song at the wedding.',
    participleExample: 'The national anthem has been sung before every match.',
  },
  {
    base: 'sink',
    past: 'sank',
    participle: 'sunk',
    serbian: 'potonuti',
    level: 'B1',
    example: 'Heavy objects sink in water.',
    pastExample: 'The old ship sank during the storm.',
    participleExample: 'Several boats have sunk in this area.',
  },
  {
    base: 'sit',
    past: 'sat',
    participle: 'sat',
    serbian: 'sjediti',
    level: 'B1',
    example: 'I sit by the window to read.',
    pastExample: 'She sat next to me during the lecture.',
    participleExample: 'He has sat in that chair for hours.',
  },
  {
    base: 'sleep',
    past: 'slept',
    participle: 'slept',
    serbian: 'spavati',
    level: 'B1',
    example: 'I sleep for eight hours every night.',
    pastExample: 'She slept through her alarm this morning.',
    participleExample: 'He has slept very badly this week.',
  },
  {
    base: 'slide',
    past: 'slid',
    participle: 'slid',
    serbian: 'kliziti',
    level: 'B1',
    example: 'Children slide on the ice in winter.',
    pastExample: 'She slid across the polished floor in her socks.',
    participleExample: 'The box has slid to the back of the shelf.',
  },
  {
    base: 'smell',
    past: 'smelt',
    participle: 'smelt',
    serbian: 'mirisati',
    level: 'B1',
    example: 'These roses smell absolutely wonderful.',
    pastExample: 'The kitchen smelt of fresh bread this morning.',
    participleExample: 'It has smelt strange in here all day.',
  },
  {
    base: 'spend',
    past: 'spent',
    participle: 'spent',
    serbian: 'potrošiti/provesti',
    level: 'B1',
    example: 'I spend weekends with my family.',
    pastExample: 'She spent a lot of money on the renovation.',
    participleExample: 'He has spent three years working abroad.',
  },
  {
    base: 'spin',
    past: 'spun',
    participle: 'spun',
    serbian: 'vrtjeti se',
    level: 'B1',
    example: 'The wheels spin very fast on this car.',
    pastExample: 'She spun around to see who called her name.',
    participleExample: 'The top has spun for nearly a minute.',
  },
  {
    base: 'stand',
    past: 'stood',
    participle: 'stood',
    serbian: 'stajati',
    level: 'B1',
    example: 'I stand at my desk for part of the day.',
    pastExample: 'She stood in the queue for an hour.',
    participleExample: 'He has stood by his decision from the beginning.',
  },
  {
    base: 'steal',
    past: 'stole',
    participle: 'stolen',
    serbian: 'ukrasti',
    level: 'B1',
    example: 'Thieves steal when no one is watching.',
    pastExample: 'Someone stole her bicycle from outside the shop.',
    participleExample: 'My phone has been stolen on the train.',
  },
  {
    base: 'stick',
    past: 'stuck',
    participle: 'stuck',
    serbian: 'prilijepiti',
    level: 'B1',
    example: 'I stick notes on the fridge to remember things.',
    pastExample: 'She stuck a stamp on the envelope.',
    participleExample: 'The label has stuck firmly to the box.',
  },
  {
    base: 'sting',
    past: 'stung',
    participle: 'stung',
    serbian: 'žariti',
    level: 'B1',
    example: 'Bees sting when they feel threatened.',
    pastExample: 'A wasp stung him on the arm.',
    participleExample: 'She has been stung by a jellyfish.',
  },
  {
    base: 'strike',
    past: 'struck',
    participle: 'struck',
    serbian: 'udariti',
    level: 'B1',
    example: 'Lightning often strikes tall buildings.',
    pastExample: 'The clock struck midnight.',
    participleExample: 'An idea has struck me just now.',
  },
  {
    base: 'swear',
    past: 'swore',
    participle: 'sworn',
    serbian: 'psovati/zakleti se',
    level: 'B1',
    example: 'He swears he is telling the truth.',
    pastExample: 'She swore to keep the secret forever.',
    participleExample: 'He has sworn an oath to protect the people.',
  },
  {
    base: 'sweep',
    past: 'swept',
    participle: 'swept',
    serbian: 'pomesti',
    level: 'B1',
    example: 'I sweep the kitchen floor every evening.',
    pastExample: 'She swept the leaves off the patio.',
    participleExample: 'He has swept every room in the house.',
  },
  {
    base: 'swing',
    past: 'swung',
    participle: 'swung',
    serbian: 'ljuljati',
    level: 'B1',
    example: 'Children swing on the playground equipment.',
    pastExample: 'She swung the door open excitedly.',
    participleExample: 'The pendulum has swung back and forth for hours.',
  },
  {
    base: 'teach',
    past: 'taught',
    participle: 'taught',
    serbian: 'učiti/podučavati',
    level: 'B1',
    example: 'She teaches English at the local school.',
    pastExample: 'He taught me how to ride a bike.',
    participleExample: 'She has taught many students over the years.',
  },
  {
    base: 'tear',
    past: 'tore',
    participle: 'torn',
    serbian: 'trgati',
    level: 'B1',
    example: 'She tears pages out of old magazines for her art.',
    pastExample: 'He tore the letter in half.',
    participleExample: 'The flag has been torn by the strong wind.',
  },
  {
    base: 'throw',
    past: 'threw',
    participle: 'thrown',
    serbian: 'baciti',
    level: 'B1',
    example: 'I throw old papers in the recycling bin.',
    pastExample: 'She threw the ball to her dog.',
    participleExample: 'He has thrown away all the old documents.',
  },
  {
    base: 'understand',
    past: 'understood',
    participle: 'understood',
    serbian: 'razumjeti',
    level: 'B1',
    example: 'I understand how to use this software.',
    pastExample: 'She understood the instructions immediately.',
    participleExample: 'He has understood the importance of the project.',
  },
  {
    base: 'wake',
    past: 'woke',
    participle: 'woken',
    serbian: 'probuditi se',
    level: 'B1',
    example: 'I wake up at six every morning.',
    pastExample: 'She woke up in the middle of the night.',
    participleExample: 'He has woken up early every day this week.',
  },
  {
    base: 'win',
    past: 'won',
    participle: 'won',
    serbian: 'pobijediti',
    level: 'B1',
    example: 'Our team wins most of its matches.',
    pastExample: 'She won first prize at the competition.',
    participleExample: 'He has won three gold medals in his career.',
  },

  // B2 verbs (30)
  {
    base: 'arise',
    past: 'arose',
    participle: 'arisen',
    serbian: 'nastati',
    level: 'B2',
    example: 'Problems arise when communication fails.',
    pastExample: 'A new difficulty arose during the project.',
    participleExample: 'Several issues have arisen since the changes were made.',
  },
  {
    base: 'bear',
    past: 'bore',
    participle: 'born',
    serbian: 'nositi/roditi',
    level: 'B2',
    example: 'These trees bear fruit every autumn.',
    pastExample: 'She bore the responsibility with great dignity.',
    participleExample: 'He has borne the weight of the family for years.',
  },
  {
    base: 'beat',
    past: 'beat',
    participle: 'beaten',
    serbian: 'pobijediti/tući',
    level: 'B2',
    example: 'Our team beat every opponent this season.',
    pastExample: 'She beat her personal best in the race.',
    participleExample: 'He has beaten the world record twice.',
  },
  {
    base: 'become',
    past: 'became',
    participle: 'become',
    serbian: 'postati',
    level: 'B2',
    example: 'I want to become a doctor one day.',
    pastExample: 'She became the youngest manager in the company.',
    participleExample: 'He has become very interested in photography.',
  },
  {
    base: 'begin',
    past: 'began',
    participle: 'begun',
    serbian: 'početi',
    level: 'B2',
    example: 'I begin work at nine every morning.',
    pastExample: 'She began learning French three years ago.',
    participleExample: 'He has begun a new chapter in his life.',
  },
  {
    base: 'bend',
    past: 'bent',
    participle: 'bent',
    serbian: 'saviti',
    level: 'B2',
    example: 'You need to bend your knees when lifting.',
    pastExample: 'She bent the wire into a circle.',
    participleExample: 'The metal rod has been bent out of shape.',
  },
  {
    base: 'bet',
    past: 'bet',
    participle: 'bet',
    serbian: 'kladiti se',
    level: 'B2',
    example: 'He rarely bets on sports.',
    pastExample: 'She bet all her money on the wrong horse.',
    participleExample: 'He has bet heavily on that investment.',
  },
  {
    base: 'bind',
    past: 'bound',
    participle: 'bound',
    serbian: 'vezati',
    level: 'B2',
    example: 'These rules bind all members of the organisation.',
    pastExample: 'She bound the documents together with string.',
    participleExample: 'The contract has bound both parties to the agreement.',
  },
  {
    base: 'bite',
    past: 'bit',
    participle: 'bitten',
    serbian: 'gristi',
    level: 'B2',
    example: 'Dogs bite when they feel threatened.',
    pastExample: 'She bit into the apple hungrily.',
    participleExample: 'He has been bitten by a mosquito.',
  },
  {
    base: 'bleed',
    past: 'bled',
    participle: 'bled',
    serbian: 'krvariti',
    level: 'B2',
    example: 'The wound bleeds every time she removes the bandage.',
    pastExample: 'His hand bled after the accident.',
    participleExample: 'The cut has bled through the bandage.',
  },
  {
    base: 'blow',
    past: 'blew',
    participle: 'blown',
    serbian: 'puhati',
    level: 'B2',
    example: 'The wind blows strongly here in winter.',
    pastExample: 'She blew out all the candles on the birthday cake.',
    participleExample: 'The storm has blown the tiles off the roof.',
  },
  {
    base: 'burst',
    past: 'burst',
    participle: 'burst',
    serbian: 'pući',
    level: 'B2',
    example: 'Balloons burst when you poke them with a pin.',
    pastExample: 'A water pipe burst during the cold night.',
    participleExample: 'Several tyres have burst on that rough road.',
  },
  {
    base: 'cast',
    past: 'cast',
    participle: 'cast',
    serbian: 'baciti/glumiti',
    level: 'B2',
    example: 'The director casts the actors very carefully.',
    pastExample: 'She cast a long shadow in the evening sun.',
    participleExample: 'He has cast doubt on the accuracy of the report.',
  },
  {
    base: 'creep',
    past: 'crept',
    participle: 'crept',
    serbian: 'puzati',
    level: 'B2',
    example: 'The cat creeps quietly through the garden.',
    pastExample: 'She crept downstairs so as not to wake anyone.',
    participleExample: 'Doubt has crept into his mind.',
  },
  {
    base: 'deal',
    past: 'dealt',
    participle: 'dealt',
    serbian: 'baviti se',
    level: 'B2',
    example: 'He deals with customer complaints every day.',
    pastExample: 'She dealt with the difficult situation calmly.',
    participleExample: 'The company has dealt with many challenges recently.',
  },
  {
    base: 'dig',
    past: 'dug',
    participle: 'dug',
    serbian: 'kopati',
    level: 'B2',
    example: 'Gardeners dig the soil in spring.',
    pastExample: 'She dug a hole to plant the new tree.',
    participleExample: 'The workers have dug a trench across the road.',
  },
  {
    base: 'forbid',
    past: 'forbade',
    participle: 'forbidden',
    serbian: 'zabraniti',
    level: 'B2',
    example: 'The rules forbid smoking inside the building.',
    pastExample: 'She forbade her children from playing on the road.',
    participleExample: 'It has been forbidden to park here.',
  },
  {
    base: 'freeze',
    past: 'froze',
    participle: 'frozen',
    serbian: 'zamrznuti',
    level: 'B2',
    example: 'Water freezes at zero degrees Celsius.',
    pastExample: 'She froze when she saw the spider on the wall.',
    participleExample: 'The lake has frozen over for the first time in years.',
  },
  {
    base: 'grind',
    past: 'ground',
    participle: 'ground',
    serbian: 'mljeti',
    level: 'B2',
    example: 'They grind coffee beans fresh every morning.',
    pastExample: 'She ground the spices with a mortar and pestle.',
    participleExample: 'The machine has ground the grain into flour.',
  },
  {
    base: 'kneel',
    past: 'knelt',
    participle: 'knelt',
    serbian: 'klečati',
    level: 'B2',
    example: 'Athletes kneel before beginning the race.',
    pastExample: 'She knelt down to speak to the child.',
    participleExample: 'He has knelt before the altar in prayer.',
  },
  {
    base: 'lay',
    past: 'laid',
    participle: 'laid',
    serbian: 'položiti',
    level: 'B2',
    example: 'Hens lay eggs every day.',
    pastExample: 'She laid the baby gently in the cot.',
    participleExample: 'The workers have laid the foundation of the building.',
  },
  {
    base: 'lend',
    past: 'lent',
    participle: 'lent',
    serbian: 'posuditi',
    level: 'B2',
    example: 'I often lend books to my colleagues.',
    pastExample: 'She lent him money when he was in difficulty.',
    participleExample: 'He has lent his car to a friend for the weekend.',
  },
  {
    base: 'lie',
    past: 'lay',
    participle: 'lain',
    serbian: 'ležati',
    level: 'B2',
    example: 'I lie on the sofa to rest after lunch.',
    pastExample: 'She lay awake all night thinking about the problem.',
    participleExample: 'The documents have lain untouched for months.',
  },
  {
    base: 'light',
    past: 'lit',
    participle: 'lit',
    serbian: 'upaliti',
    level: 'B2',
    example: 'She lights candles every evening.',
    pastExample: 'He lit the fireplace to warm the room.',
    participleExample: 'The candles have been lit for the ceremony.',
  },
  {
    base: 'mistake',
    past: 'mistook',
    participle: 'mistaken',
    serbian: 'pogriješiti',
    level: 'B2',
    example: 'People often mistake me for my brother.',
    pastExample: 'She mistook the street and got lost.',
    participleExample: 'He has mistaken the instructions from the beginning.',
  },
  {
    base: 'overcome',
    past: 'overcame',
    participle: 'overcome',
    serbian: 'savladati',
    level: 'B2',
    example: 'She overcomes every obstacle with determination.',
    pastExample: 'He overcame his fear of public speaking.',
    participleExample: 'She has overcome many difficulties in her life.',
  },
  {
    base: 'prove',
    past: 'proved',
    participle: 'proven',
    serbian: 'dokazati',
    level: 'B2',
    example: 'Scientists prove theories through experimentation.',
    pastExample: 'She proved that her idea would work.',
    participleExample: 'His loyalty has been proven beyond any doubt.',
  },
  {
    base: 'seek',
    past: 'sought',
    participle: 'sought',
    serbian: 'tražiti',
    level: 'B2',
    example: 'They seek new opportunities every day.',
    pastExample: 'She sought advice from her mentor.',
    participleExample: 'He has sought help from various specialists.',
  },
  {
    base: 'spread',
    past: 'spread',
    participle: 'spread',
    serbian: 'širiti',
    level: 'B2',
    example: 'I spread butter on my toast every morning.',
    pastExample: 'The news spread quickly through the village.',
    participleExample: 'The fire has spread to the neighbouring building.',
  },
  {
    base: 'withdraw',
    past: 'withdrew',
    participle: 'withdrawn',
    serbian: 'povući se',
    level: 'B2',
    example: 'She withdraws money from the bank every week.',
    pastExample: 'He withdrew his application at the last moment.',
    participleExample: 'The army has withdrawn from the region.',
  },
];

export const PHRASAL_VERBS = [
  // give
  {
    verb: 'give up',
    meaning: 'to stop trying or doing something',
    serbian: 'odustati',
    level: 'A2',
    example: 'Don\'t give up — you are almost there!',
    separable: false,
    category: 'general',
  },
  {
    verb: 'give in',
    meaning: 'to stop resisting; to yield',
    serbian: 'popustiti',
    level: 'B1',
    example: 'After hours of arguing, he finally gave in.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'give away',
    meaning: 'to give something for free; to reveal a secret',
    serbian: 'pokloniti',
    level: 'B1',
    example: 'She gave away all her old clothes to charity.',
    separable: true,
    category: 'general',
  },

  // take
  {
    verb: 'take off',
    meaning: 'to remove clothing; (of a plane) to leave the ground',
    serbian: 'skinuti/poletjeti',
    level: 'A2',
    example: 'The plane took off two hours late.',
    separable: true,
    category: 'movement',
  },
  {
    verb: 'take over',
    meaning: 'to assume control or responsibility',
    serbian: 'preuzeti',
    level: 'B1',
    example: 'A larger company took over our business.',
    separable: true,
    category: 'work',
  },
  {
    verb: 'take on',
    meaning: 'to accept a responsibility or task',
    serbian: 'prihvatiti',
    level: 'B1',
    example: 'She took on extra duties at work.',
    separable: true,
    category: 'work',
  },

  // look
  {
    verb: 'look up',
    meaning: 'to search for information',
    serbian: 'potražiti',
    level: 'A2',
    example: 'I looked up the word in the dictionary.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'look after',
    meaning: 'to take care of someone or something',
    serbian: 'brinuti se',
    level: 'A2',
    example: 'She looks after her younger siblings every day.',
    separable: false,
    category: 'relationships',
  },
  {
    verb: 'look into',
    meaning: 'to investigate or examine',
    serbian: 'istražiti',
    level: 'B1',
    example: 'The manager agreed to look into the complaint.',
    separable: false,
    category: 'work',
  },

  // put
  {
    verb: 'put off',
    meaning: 'to postpone or delay something',
    serbian: 'odgoditi',
    level: 'B1',
    example: 'He kept putting off the difficult conversation.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'put on',
    meaning: 'to dress oneself in clothing',
    serbian: 'obući',
    level: 'A2',
    example: 'Put on your coat — it is cold outside.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'put up with',
    meaning: 'to tolerate something unpleasant',
    serbian: 'trpjeti',
    level: 'B1',
    example: 'She can\'t put up with his bad attitude any longer.',
    separable: false,
    category: 'relationships',
  },

  // turn
  {
    verb: 'turn on',
    meaning: 'to switch something on',
    serbian: 'uključiti',
    level: 'A2',
    example: 'Turn on the lights when you enter the room.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'turn off',
    meaning: 'to switch something off',
    serbian: 'isključiti',
    level: 'A2',
    example: 'Please turn off the TV before you go to bed.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'turn up',
    meaning: 'to arrive or appear unexpectedly',
    serbian: 'pojaviti se',
    level: 'B1',
    example: 'He turned up at the party without an invitation.',
    separable: false,
    category: 'general',
  },

  // run
  {
    verb: 'run out of',
    meaning: 'to use all of something so none is left',
    serbian: 'ponestati',
    level: 'B1',
    example: 'We ran out of milk this morning.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'run into',
    meaning: 'to meet someone unexpectedly',
    serbian: 'slučajno sresti',
    level: 'B1',
    example: 'I ran into my old teacher at the supermarket.',
    separable: false,
    category: 'relationships',
  },
  {
    verb: 'run away',
    meaning: 'to flee or escape from a place',
    serbian: 'pobjeći',
    level: 'A2',
    example: 'The dog ran away when it heard the thunder.',
    separable: false,
    category: 'movement',
  },

  // come
  {
    verb: 'come up with',
    meaning: 'to think of an idea or a solution',
    serbian: 'smisliti',
    level: 'B1',
    example: 'She came up with a brilliant solution.',
    separable: false,
    category: 'work',
  },
  {
    verb: 'come across',
    meaning: 'to find or encounter something by chance',
    serbian: 'naići na',
    level: 'B1',
    example: 'I came across an old photo album in the attic.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'come back',
    meaning: 'to return to a place',
    serbian: 'vratiti se',
    level: 'A2',
    example: 'What time will you come back tonight?',
    separable: false,
    category: 'movement',
  },

  // get
  {
    verb: 'get on',
    meaning: 'to board transport; to have a good relationship',
    serbian: 'ući/slagati se',
    level: 'A2',
    example: 'They get on really well with their neighbours.',
    separable: false,
    category: 'relationships',
  },
  {
    verb: 'get off',
    meaning: 'to leave transport; to remove something',
    serbian: 'izaći/skinuti se',
    level: 'A2',
    example: 'Get off the bus at the third stop.',
    separable: true,
    category: 'movement',
  },
  {
    verb: 'get over',
    meaning: 'to recover from an illness or difficulty',
    serbian: 'preboljeti',
    level: 'B1',
    example: 'It took her months to get over the breakup.',
    separable: false,
    category: 'relationships',
  },

  // go
  {
    verb: 'go on',
    meaning: 'to continue doing something',
    serbian: 'nastaviti',
    level: 'A2',
    example: 'Please go on — I am listening carefully.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'go off',
    meaning: 'to explode or to go bad (food)',
    serbian: 'eksplodirati/pokvariti se',
    level: 'B1',
    example: 'The alarm went off at six in the morning.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'go through',
    meaning: 'to experience something difficult; to examine',
    serbian: 'proći kroz',
    level: 'B1',
    example: 'She went through a very difficult period last year.',
    separable: false,
    category: 'general',
  },

  // bring
  {
    verb: 'bring up',
    meaning: 'to raise a child; to mention a topic',
    serbian: 'odgojiti/pokrenuti temu',
    level: 'B1',
    example: 'He brought up an interesting point during the meeting.',
    separable: true,
    category: 'communication',
  },
  {
    verb: 'bring out',
    meaning: 'to highlight or reveal a quality',
    serbian: 'istaknuti',
    level: 'B1',
    example: 'Travel brings out the best in people.',
    separable: true,
    category: 'communication',
  },
  {
    verb: 'bring back',
    meaning: 'to return something; to recall a memory',
    serbian: 'vratiti',
    level: 'B1',
    example: 'That song brings back happy memories of my childhood.',
    separable: true,
    category: 'general',
  },

  // call
  {
    verb: 'call off',
    meaning: 'to cancel a planned event',
    serbian: 'otkazati',
    level: 'B1',
    example: 'They called off the meeting because of the storm.',
    separable: true,
    category: 'work',
  },
  {
    verb: 'call back',
    meaning: 'to return a phone call',
    serbian: 'uzvratiti poziv',
    level: 'A2',
    example: 'I missed your call — I will call you back later.',
    separable: true,
    category: 'communication',
  },
  {
    verb: 'call on',
    meaning: 'to ask someone to speak or to visit',
    serbian: 'pozvati/tražiti',
    level: 'B1',
    example: 'The teacher called on me to answer the question.',
    separable: false,
    category: 'communication',
  },

  // set
  {
    verb: 'set up',
    meaning: 'to arrange or establish something',
    serbian: 'postaviti',
    level: 'B1',
    example: 'They set up a new office in the city centre.',
    separable: true,
    category: 'work',
  },
  {
    verb: 'set off',
    meaning: 'to begin a journey',
    serbian: 'krenuti',
    level: 'B1',
    example: 'We set off early to avoid the traffic.',
    separable: false,
    category: 'movement',
  },
  {
    verb: 'set aside',
    meaning: 'to reserve time, money, or resources for a purpose',
    serbian: 'odložiti',
    level: 'B2',
    example: 'She sets aside money every month for emergencies.',
    separable: true,
    category: 'work',
  },

  // break
  {
    verb: 'break down',
    meaning: 'to stop functioning; to lose emotional control',
    serbian: 'pokvariti se',
    level: 'B1',
    example: 'The car broke down on the motorway.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'break up',
    meaning: 'to end a romantic relationship',
    serbian: 'raskinuti',
    level: 'B1',
    example: 'They broke up after three years together.',
    separable: false,
    category: 'relationships',
  },
  {
    verb: 'break into',
    meaning: 'to enter a building by force',
    serbian: 'provaliti',
    level: 'B1',
    example: 'Thieves broke into the shop overnight.',
    separable: false,
    category: 'general',
  },

  // pick
  {
    verb: 'pick up',
    meaning: 'to lift something; to collect someone; to learn casually',
    serbian: 'pokupiti/naučiti',
    level: 'A2',
    example: 'She picked up some Spanish while living in Madrid.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'pick out',
    meaning: 'to choose or select',
    serbian: 'odabrati',
    level: 'B1',
    example: 'He picked out a tie to match his shirt.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'pick on',
    meaning: 'to bully or treat unfairly',
    serbian: 'zadirkivati',
    level: 'B1',
    example: 'The older kids were picking on him at school.',
    separable: false,
    category: 'relationships',
  },

  // hold
  {
    verb: 'hold on',
    meaning: 'to wait; to grip tightly',
    serbian: 'čekati',
    level: 'A2',
    example: 'Hold on a moment — I will be right with you.',
    separable: false,
    category: 'communication',
  },
  {
    verb: 'hold back',
    meaning: 'to restrain or prevent progress',
    serbian: 'zadržati',
    level: 'B1',
    example: 'Fear of failure held him back for years.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'hold up',
    meaning: 'to delay; to rob at gunpoint',
    serbian: 'kasniti/pljačkati',
    level: 'B2',
    example: 'Traffic held us up and we arrived late.',
    separable: true,
    category: 'general',
  },

  // work
  {
    verb: 'work out',
    meaning: 'to exercise; to find a solution',
    serbian: 'vježbati/riješiti',
    level: 'B1',
    example: 'I work out at the gym three times a week.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'work on',
    meaning: 'to spend time improving or doing something',
    serbian: 'raditi na',
    level: 'B1',
    example: 'She is working on her English pronunciation.',
    separable: false,
    category: 'work',
  },

  // figure / find / fall
  {
    verb: 'figure out',
    meaning: 'to understand or solve something',
    serbian: 'shvatiti',
    level: 'B1',
    example: 'Can you figure out how this device works?',
    separable: true,
    category: 'general',
  },
  {
    verb: 'find out',
    meaning: 'to discover information',
    serbian: 'saznati',
    level: 'A2',
    example: 'I need to find out what time the train leaves.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'fall out',
    meaning: 'to argue and stop being friendly',
    serbian: 'posvađati se',
    level: 'B1',
    example: 'They fell out over a misunderstanding.',
    separable: false,
    category: 'relationships',
  },
  {
    verb: 'fall for',
    meaning: 'to fall in love; to be deceived by something',
    serbian: 'zaljubiti se/nasjednuti',
    level: 'B1',
    example: 'She fell for him the moment they met.',
    separable: false,
    category: 'relationships',
  },
  {
    verb: 'fall behind',
    meaning: 'to fail to keep up with a schedule or standard',
    serbian: 'zaostati',
    level: 'B1',
    example: 'He fell behind with his coursework after getting ill.',
    separable: false,
    category: 'work',
  },
  {
    verb: 'fall apart',
    meaning: 'to break into pieces; to lose control emotionally',
    serbian: 'raspasti se',
    level: 'B1',
    example: 'The old chair fell apart when he sat on it.',
    separable: false,
    category: 'general',
  },

  // make
  {
    verb: 'make up',
    meaning: 'to reconcile; to invent a story',
    serbian: 'pomiriti se/izmisliti',
    level: 'B1',
    example: 'They argued but made up the next day.',
    separable: true,
    category: 'relationships',
  },
  {
    verb: 'make out',
    meaning: 'to manage to see or hear; to claim',
    serbian: 'razabrati/tvrditi',
    level: 'B2',
    example: 'I couldn\'t make out what he was saying in the noise.',
    separable: true,
    category: 'communication',
  },
  {
    verb: 'make up for',
    meaning: 'to compensate for something',
    serbian: 'nadoknaditi',
    level: 'B2',
    example: 'She worked extra hours to make up for her absence.',
    separable: false,
    category: 'general',
  },

  // cut
  {
    verb: 'cut down',
    meaning: 'to reduce the amount of something',
    serbian: 'smanjiti',
    level: 'B1',
    example: 'He has cut down on sugar to improve his health.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'cut off',
    meaning: 'to interrupt; to disconnect',
    serbian: 'prekinuti/odsjeci',
    level: 'B1',
    example: 'The storm cut off the electricity for three hours.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'cut out',
    meaning: 'to remove by cutting; to stop doing something',
    serbian: 'izrezati/prestati',
    level: 'B1',
    example: 'Cut out the article and paste it in your notebook.',
    separable: true,
    category: 'general',
  },

  // end / add / blow / calm / carry
  {
    verb: 'end up',
    meaning: 'to eventually reach a state or place',
    serbian: 'završiti/naći se',
    level: 'B1',
    example: 'We took the wrong road and ended up in the village.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'add up',
    meaning: 'to calculate; to make sense',
    serbian: 'sabrati/imati smisla',
    level: 'B1',
    example: 'The figures don\'t add up — something is wrong.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'blow up',
    meaning: 'to explode; to enlarge a photo',
    serbian: 'eksplodirati/uvećati',
    level: 'B1',
    example: 'They had to blow up the photograph to see the details.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'calm down',
    meaning: 'to become or make less upset or excited',
    serbian: 'smiriti se',
    level: 'A2',
    example: 'Please calm down and tell me what happened.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'carry on',
    meaning: 'to continue doing something',
    serbian: 'nastaviti',
    level: 'B1',
    example: 'Carry on with your work — I will be back soon.',
    separable: false,
    category: 'general',
  },

  // check / clean / count / deal
  {
    verb: 'check in',
    meaning: 'to register on arrival at a hotel or airport',
    serbian: 'prijaviti se',
    level: 'A2',
    example: 'We need to check in at least two hours before the flight.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'check out',
    meaning: 'to leave a hotel; to look at something interesting',
    serbian: 'odjaviti se/pogledati',
    level: 'A2',
    example: 'Check out this amazing new restaurant in town!',
    separable: true,
    category: 'general',
  },
  {
    verb: 'clean up',
    meaning: 'to tidy and clean a place',
    serbian: 'počistiti',
    level: 'A2',
    example: 'We need to clean up the kitchen after the party.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'count on',
    meaning: 'to rely or depend on someone',
    serbian: 'računati na',
    level: 'B1',
    example: 'You can always count on her in a crisis.',
    separable: false,
    category: 'relationships',
  },
  {
    verb: 'deal with',
    meaning: 'to handle or manage a problem',
    serbian: 'baviti se',
    level: 'B1',
    example: 'She deals with difficult customers every day.',
    separable: false,
    category: 'work',
  },

  // dress / drop / fill / fix / follow
  {
    verb: 'dress up',
    meaning: 'to wear smart or fancy clothes',
    serbian: 'dotjerati se',
    level: 'B1',
    example: 'Everyone dressed up for the company dinner.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'drop off',
    meaning: 'to fall asleep; to leave someone at a place',
    serbian: 'odspavati/ostaviti',
    level: 'B1',
    example: 'Can you drop me off at the station on your way?',
    separable: true,
    category: 'general',
  },
  {
    verb: 'fill in',
    meaning: 'to complete a form with information',
    serbian: 'ispuniti',
    level: 'B1',
    example: 'Please fill in the application form carefully.',
    separable: true,
    category: 'work',
  },
  {
    verb: 'fix up',
    meaning: 'to repair; to arrange a meeting',
    serbian: 'popraviti/dogovoriti',
    level: 'B1',
    example: 'They are fixing up the old cottage by the lake.',
    separable: true,
    category: 'work',
  },
  {
    verb: 'follow up',
    meaning: 'to pursue or check on something further',
    serbian: 'pratiti/nastaviti',
    level: 'B1',
    example: 'I will follow up with you after the meeting.',
    separable: true,
    category: 'work',
  },

  // hand / hang / join / keep
  {
    verb: 'hand in',
    meaning: 'to submit work or an object officially',
    serbian: 'predati',
    level: 'B1',
    example: 'Please hand in your essays by Friday.',
    separable: true,
    category: 'work',
  },
  {
    verb: 'hand out',
    meaning: 'to distribute to several people',
    serbian: 'podijeliti',
    level: 'B1',
    example: 'The teacher handed out the exam papers.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'hang out',
    meaning: 'to spend time relaxing with others',
    serbian: 'provoditi vrijeme',
    level: 'A2',
    example: 'We hang out at the café every Saturday.',
    separable: false,
    category: 'relationships',
  },
  {
    verb: 'join in',
    meaning: 'to participate in an activity with others',
    serbian: 'pridružiti se',
    level: 'A2',
    example: 'Everyone joined in the singing around the fire.',
    separable: false,
    category: 'relationships',
  },
  {
    verb: 'keep on',
    meaning: 'to continue doing something persistently',
    serbian: 'nastaviti',
    level: 'B1',
    example: 'Keep on practising and you will improve.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'keep up with',
    meaning: 'to maintain the same pace or standard as others',
    serbian: 'pratiti korak',
    level: 'B1',
    example: 'It is hard to keep up with all the latest news.',
    separable: false,
    category: 'work',
  },

  // knock / lay / leave / let
  {
    verb: 'knock out',
    meaning: 'to make someone unconscious by hitting them',
    serbian: 'nokautirati',
    level: 'B2',
    example: 'The boxer knocked out his opponent in the third round.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'lay off',
    meaning: 'to dismiss employees due to budget cuts',
    serbian: 'otpustiti',
    level: 'B2',
    example: 'The company laid off fifty workers last month.',
    separable: true,
    category: 'work',
  },
  {
    verb: 'leave out',
    meaning: 'to not include someone or something',
    serbian: 'izostaviti',
    level: 'B1',
    example: 'Don\'t leave out any important details in your report.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'let down',
    meaning: 'to disappoint someone',
    serbian: 'razočarati',
    level: 'B1',
    example: 'I promised to be there — I don\'t want to let you down.',
    separable: true,
    category: 'relationships',
  },

  // mix / move / pass / pay / point
  {
    verb: 'mix up',
    meaning: 'to confuse two or more things',
    serbian: 'pobrkati',
    level: 'B1',
    example: 'I always mix up the twins — they look identical.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'move on',
    meaning: 'to progress; to stop dwelling on the past',
    serbian: 'nastaviti dalje',
    level: 'B1',
    example: 'After the loss, it took her a long time to move on.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'pass out',
    meaning: 'to faint or lose consciousness',
    serbian: 'onesvijestiti se',
    level: 'B1',
    example: 'She passed out from the heat during the outdoor event.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'pay back',
    meaning: 'to repay money owed to someone',
    serbian: 'vratiti dug',
    level: 'B1',
    example: 'I will pay you back as soon as I get my salary.',
    separable: true,
    category: 'relationships',
  },
  {
    verb: 'point out',
    meaning: 'to draw attention to something',
    serbian: 'istaknuti',
    level: 'B1',
    example: 'She pointed out several errors in the document.',
    separable: true,
    category: 'communication',
  },

  // rule / show / sign / sort / stand
  {
    verb: 'rule out',
    meaning: 'to eliminate a possibility',
    serbian: 'isključiti',
    level: 'B2',
    example: 'The doctors have ruled out anything serious.',
    separable: true,
    category: 'work',
  },
  {
    verb: 'show off',
    meaning: 'to display one\'s abilities in an ostentatious way',
    serbian: 'hvaliti se',
    level: 'B1',
    example: 'He was showing off his new car to all his friends.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'show up',
    meaning: 'to arrive or appear somewhere',
    serbian: 'pojaviti se',
    level: 'B1',
    example: 'Only half the guests showed up to the event.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'sign up',
    meaning: 'to register for something',
    serbian: 'prijaviti se',
    level: 'A2',
    example: 'Sign up for the course before the deadline.',
    separable: false,
    category: 'general',
  },
  {
    verb: 'sort out',
    meaning: 'to resolve a problem or organise something',
    serbian: 'srediti',
    level: 'B1',
    example: 'We need to sort out the schedule for next week.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'stand up',
    meaning: 'to rise from a seated position; to fail to keep an appointment',
    serbian: 'ustati/iznevjeriti',
    level: 'B1',
    example: 'He stood her up and she waited for an hour.',
    separable: true,
    category: 'relationships',
  },

  // step / sum / take away / take back / throw away / try on / use up
  {
    verb: 'step up',
    meaning: 'to increase effort or take on more responsibility',
    serbian: 'pojačati',
    level: 'B2',
    example: 'The team needed to step up their performance in the second half.',
    separable: false,
    category: 'work',
  },
  {
    verb: 'sum up',
    meaning: 'to summarise the main points',
    serbian: 'sažeti',
    level: 'B1',
    example: 'Let me sum up the key points of the presentation.',
    separable: true,
    category: 'communication',
  },
  {
    verb: 'take away',
    meaning: 'to remove or carry something from a place',
    serbian: 'odnijeti',
    level: 'A2',
    example: 'The waiter took away our empty plates.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'take back',
    meaning: 'to retract a statement; to return an item',
    serbian: 'povući',
    level: 'B1',
    example: 'I want to take back everything I said in anger.',
    separable: true,
    category: 'communication',
  },
  {
    verb: 'throw away',
    meaning: 'to discard something in the rubbish',
    serbian: 'baciti',
    level: 'A2',
    example: 'Don\'t throw away the receipt — you may need it.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'try on',
    meaning: 'to put on clothing to see if it fits',
    serbian: 'isprobati',
    level: 'A2',
    example: 'She tried on five dresses before choosing one.',
    separable: true,
    category: 'general',
  },
  {
    verb: 'use up',
    meaning: 'to consume the entire supply of something',
    serbian: 'potrošiti',
    level: 'B1',
    example: 'We have used up all the printer paper.',
    separable: true,
    category: 'general',
  },
];
