export const GRAMMAR_DATA = {
  tenses: {
    lessons: [
      {
        id: 'present-simple',
        title: 'Present Simple',
        duration: '5 min',
        explanation: 'Used for habits, facts, and routines. It describes things that are generally true or happen regularly.',
        rules: [
          'Subject + base verb (I/you/we/they)',
          'Subject + verb+s/es (he/she/it)',
          'Negative: don\'t / doesn\'t + base verb',
          'Question: Do/Does + subject + base verb?',
        ],
        examples: [
          { sentence: 'She works at a hospital.', highlight: 'works', note: 'regular habit' },
          { sentence: 'Water boils at 100°C.', highlight: 'boils', note: 'general fact' },
          { sentence: 'He doesn\'t like coffee.', highlight: 'doesn\'t like', note: 'negative form' },
          { sentence: 'Do they speak English?', highlight: 'Do speak', note: 'question form' },
        ],
        commonMistakes: [
          { wrong: 'She work every day.', correct: 'She works every day.', explanation: 'Add -s for he/she/it' },
          { wrong: 'He don\'t know.', correct: 'He doesn\'t know.', explanation: 'Use doesn\'t for he/she/it' },
        ],
        tips: 'Remember: he/she/it always gets an -s. When in doubt, say it out loud!',
      },
      {
        id: 'present-continuous',
        title: 'Present Continuous',
        duration: '5 min',
        explanation: 'Used for actions happening right now or temporary situations. Shows something is in progress at the moment of speaking.',
        rules: [
          'Subject + am/is/are + verb+ing',
          'I am, He/She/It is, You/We/They are',
          'Negative: am/is/are + not + verb+ing',
          'Cannot use with state verbs: know, love, want, understand',
        ],
        examples: [
          { sentence: 'I am studying English right now.', highlight: 'am studying', note: 'happening now' },
          { sentence: 'She is working from home this week.', highlight: 'is working', note: 'temporary situation' },
          { sentence: 'They aren\'t watching TV.', highlight: 'aren\'t watching', note: 'negative' },
          { sentence: 'Is he coming to the party?', highlight: 'Is coming', note: 'question' },
        ],
        commonMistakes: [
          { wrong: 'I am knowing the answer.', correct: 'I know the answer.', explanation: 'Know is a state verb — no -ing' },
          { wrong: 'She working now.', correct: 'She is working now.', explanation: 'Never forget the am/is/are' },
        ],
        tips: 'If you can say "in the middle of doing", use continuous. State verbs (know, like, want) never use -ing.',
      },
      {
        id: 'present-perfect',
        title: 'Present Perfect',
        duration: '6 min',
        explanation: 'Connects past actions to the present. Used for experiences, recent events, or unfinished situations. No specific time mentioned.',
        rules: [
          'Subject + have/has + past participle',
          'I/You/We/They have — He/She/It has',
          'Key words: already, yet, ever, never, just, since, for',
          'No specific time mentioned (not: yesterday, last week)',
        ],
        examples: [
          { sentence: 'I have visited Paris three times.', highlight: 'have visited', note: 'life experience' },
          { sentence: 'She has just finished the report.', highlight: 'has just finished', note: 'very recent action' },
          { sentence: 'Have you ever eaten sushi?', highlight: 'Have eaten', note: 'experience question' },
          { sentence: 'He hasn\'t called yet.', highlight: 'hasn\'t called', note: 'expected but not done' },
        ],
        commonMistakes: [
          { wrong: 'I have seen him yesterday.', correct: 'I saw him yesterday.', explanation: 'Yesterday = specific time → use Past Simple' },
          { wrong: 'She have finished.', correct: 'She has finished.', explanation: 'He/she/it uses HAS' },
        ],
        tips: 'No time word = Present Perfect. Specific time word (yesterday, in 2020) = Past Simple.',
      },
      {
        id: 'past-simple',
        title: 'Past Simple',
        duration: '5 min',
        explanation: 'Used for completed actions at a specific time in the past. The most common and important past tense.',
        rules: [
          'Regular verbs: add -ed (walked, talked, worked)',
          'Irregular verbs: learn them (go→went, see→saw, buy→bought)',
          'Negative: didn\'t + base verb (same for all persons)',
          'Question: Did + subject + base verb?',
        ],
        examples: [
          { sentence: 'We visited Rome last summer.', highlight: 'visited', note: 'specific time in past' },
          { sentence: 'She didn\'t go to the party.', highlight: 'didn\'t go', note: 'negative — base verb after didn\'t' },
          { sentence: 'Did you see that movie?', highlight: 'Did see', note: 'question form' },
          { sentence: 'He bought a new car yesterday.', highlight: 'bought', note: 'irregular verb' },
        ],
        commonMistakes: [
          { wrong: 'I didn\'t went there.', correct: 'I didn\'t go there.', explanation: 'After did/didn\'t always use base verb' },
          { wrong: 'Did she went?', correct: 'Did she go?', explanation: 'Base verb after Did, not past form' },
        ],
        tips: 'Learn the top 50 irregular verbs by heart. They appear in 80% of all conversations.',
      },
      {
        id: 'past-continuous',
        title: 'Past Continuous',
        duration: '5 min',
        explanation: 'Describes an action in progress at a specific past moment, often interrupted by another action.',
        rules: [
          'Subject + was/were + verb+ing',
          'I/He/She/It was — You/We/They were',
          'Often used with Past Simple: was doing (when) something happened',
          'Negative: was/were + not + verb+ing',
        ],
        examples: [
          { sentence: 'I was sleeping when the phone rang.', highlight: 'was sleeping', note: 'interrupted action' },
          { sentence: 'They were playing football all afternoon.', highlight: 'were playing', note: 'in progress in past' },
          { sentence: 'What were you doing at 8pm?', highlight: 'were you doing', note: 'question about past moment' },
          { sentence: 'She wasn\'t listening to me.', highlight: 'wasn\'t listening', note: 'negative' },
        ],
        commonMistakes: [
          { wrong: 'I was play when you called.', correct: 'I was playing when you called.', explanation: 'Must add -ing in continuous' },
          { wrong: 'They was working.', correct: 'They were working.', explanation: 'They/you/we = were, not was' },
        ],
        tips: 'Think of it like a movie scene — Past Continuous is the background, Past Simple is the interruption.',
      },
      {
        id: 'future-simple',
        title: 'Future Simple (will)',
        duration: '5 min',
        explanation: 'Used for predictions, spontaneous decisions, promises and offers. Will is the same for all persons.',
        rules: [
          'Subject + will + base verb (all persons same)',
          'Negative: will not / won\'t + base verb',
          'Question: Will + subject + base verb?',
          'Contractions: I\'ll, you\'ll, he\'ll, she\'ll, we\'ll, they\'ll',
        ],
        examples: [
          { sentence: 'I will call you tomorrow.', highlight: 'will call', note: 'promise' },
          { sentence: 'It will rain this afternoon.', highlight: 'will rain', note: 'prediction' },
          { sentence: 'I\'ll help you with that.', highlight: '\'ll help', note: 'spontaneous offer' },
          { sentence: 'Will you come to the meeting?', highlight: 'Will come', note: 'question' },
        ],
        commonMistakes: [
          { wrong: 'I will to go there.', correct: 'I will go there.', explanation: 'Never use "to" after will' },
          { wrong: 'He wills come.', correct: 'He will come.', explanation: 'Will never changes — no -s for he/she/it' },
        ],
        tips: 'Will = decision made at the moment of speaking. Going to = plan made before speaking.',
      },
      {
        id: 'future-going-to',
        title: 'Future: Going To',
        duration: '5 min',
        explanation: 'Used for plans already decided before speaking, and predictions based on visible evidence right now.',
        rules: [
          'Subject + am/is/are + going to + base verb',
          'Negative: am/is/are + not + going to + verb',
          'Question: Am/Is/Are + subject + going to + verb?',
          'Evidence-based: Look! It\'s going to rain! (clouds visible now)',
        ],
        examples: [
          { sentence: 'We are going to visit Paris next month.', highlight: 'are going to visit', note: 'pre-made plan' },
          { sentence: 'Look out! She is going to fall!', highlight: 'is going to fall', note: 'evidence-based prediction' },
          { sentence: 'I\'m not going to eat fast food anymore.', highlight: '\'m not going to eat', note: 'decision already made' },
          { sentence: 'Are they going to move to London?', highlight: 'going to move', note: 'question about plan' },
        ],
        commonMistakes: [
          { wrong: 'I going to call him.', correct: 'I am going to call him.', explanation: 'Never forget am/is/are before going to' },
          { wrong: 'She is going to goes.', correct: 'She is going to go.', explanation: 'Always base verb after going to' },
        ],
        tips: 'Will = in the moment. Going to = already planned. Both are correct, just different situations.',
      },
      {
        id: 'future-continuous',
        title: 'Future Continuous',
        duration: '6 min',
        explanation: 'Describes an action that will be in progress at a specific moment in the future. Also used for polite questions.',
        rules: [
          'Subject + will be + verb+ing',
          'Used for: action in progress at future time, polite questions',
          'Negative: will not be + verb+ing',
          'Question: Will + subject + be + verb+ing?',
        ],
        examples: [
          { sentence: 'At 8pm tomorrow I will be watching the game.', highlight: 'will be watching', note: 'in progress at future moment' },
          { sentence: 'Will you be using the car tonight?', highlight: 'Will be using', note: 'polite question' },
          { sentence: 'This time next week we\'ll be lying on the beach.', highlight: 'will be lying', note: 'future in progress' },
          { sentence: 'She won\'t be working on Sunday.', highlight: 'won\'t be working', note: 'negative' },
        ],
        commonMistakes: [
          { wrong: 'I will being work.', correct: 'I will be working.', explanation: 'will + be (not being) + verb+ing' },
          { wrong: 'He will be work.', correct: 'He will be working.', explanation: 'Must add -ing' },
        ],
        tips: 'Future Continuous for polite questions sounds more natural: "Will you be needing anything else?" vs "Will you need?"',
      },
      {
        id: 'present-perfect-continuous',
        title: 'Present Perfect Continuous',
        duration: '6 min',
        explanation: 'Emphasises the duration of an activity that started in the past and continues now, or recently stopped with a visible result.',
        rules: [
          'Subject + have/has + been + verb+ing',
          'Key words: for, since, how long, all day, lately, recently',
          'Focuses on DURATION, not the result',
          'Cannot use with state verbs (know, love, want)',
        ],
        examples: [
          { sentence: 'I have been studying for 3 hours.', highlight: 'have been studying', note: 'started past, still doing it' },
          { sentence: 'She has been crying — her eyes are red.', highlight: 'has been crying', note: 'visible result' },
          { sentence: 'How long have you been waiting?', highlight: 'have been waiting', note: 'duration question' },
          { sentence: 'They haven\'t been sleeping well lately.', highlight: 'haven\'t been sleeping', note: 'negative' },
        ],
        commonMistakes: [
          { wrong: 'I have been know him for years.', correct: 'I have known him for years.', explanation: 'Know = state verb, no continuous' },
          { wrong: 'She has been work here since 2020.', correct: 'She has been working here since 2020.', explanation: 'Must add -ing' },
        ],
        tips: 'FOR = duration (for 2 hours). SINCE = starting point (since Monday). Both go with this tense.',
      },
      {
        id: 'past-perfect',
        title: 'Past Perfect',
        duration: '6 min',
        explanation: 'Describes an action completed BEFORE another past action. It\'s the "past of the past" — the earlier event.',
        rules: [
          'Subject + had + past participle (same for ALL persons)',
          'Negative: had not (hadn\'t) + past participle',
          'Key words: before, after, when, already, by the time, never',
          'Shows which past action happened FIRST',
        ],
        examples: [
          { sentence: 'When I arrived, she had already left.', highlight: 'had already left', note: 'left before I arrived' },
          { sentence: 'He had never seen snow before that day.', highlight: 'had never seen', note: 'first experience ever' },
          { sentence: 'They had finished dinner before the guests arrived.', highlight: 'had finished', note: 'sequence of past events' },
          { sentence: 'I hadn\'t eaten all day.', highlight: 'hadn\'t eaten', note: 'negative' },
        ],
        commonMistakes: [
          { wrong: 'When I came, she already left.', correct: 'When I came, she had already left.', explanation: 'The earlier action needs had + pp' },
          { wrong: 'He had went there.', correct: 'He had gone there.', explanation: 'Had always uses past participle, not past simple' },
        ],
        tips: 'Draw a timeline. Past Perfect = the event further left (earlier). Past Simple = the event closer to now.',
      },
      {
        id: 'mixed-tenses',
        title: 'Mixed Tenses in Context',
        duration: '7 min',
        explanation: 'Real English uses multiple tenses together. Learn to choose the right tense based on context and time expressions.',
        rules: [
          'Read the time expressions: yesterday=Past, just=Present Perfect, at 8pm tomorrow=Future Continuous',
          'Look for sequence: had done (first) → did (second) → is doing (now)',
          'Context clues: already, still, yet, ever, never, ago, since, for',
          'Ask: When? Completed? Duration? Result?',
        ],
        examples: [
          { sentence: 'I was walking home when I saw him — he had been waiting for an hour.', highlight: 'was walking', note: '3 tenses: background / event / duration' },
          { sentence: 'She has lived here since she was born.', highlight: 'has lived', note: 'Present Perfect + Past Simple' },
          { sentence: 'He said he had already eaten.', highlight: 'had already eaten', note: 'reported speech — earlier past' },
          { sentence: 'By the time you arrive, I will have finished.', highlight: 'will have finished', note: 'Future Perfect — before a future point' },
        ],
        commonMistakes: [
          { wrong: 'I have seen him yesterday.', correct: 'I saw him yesterday.', explanation: 'Specific past time = Past Simple' },
          { wrong: 'By tomorrow I finish.', correct: 'By tomorrow I will have finished.', explanation: 'Deadline in future = Future Perfect' },
        ],
        tips: 'When stuck: identify the TIME, identify if the action is COMPLETE or IN PROGRESS, then choose.',
      },
      {
        id: 'tenses-review',
        title: 'Tenses — Full Review',
        duration: '8 min',
        explanation: 'A comprehensive overview of all English tenses and when to use each one. Use this as your reference sheet.',
        rules: [
          'Present Simple: habits, facts → I work',
          'Present Continuous: now, temporary → I am working',
          'Present Perfect: experience, result → I have worked',
          'Past Simple: specific past → I worked (yesterday)',
          'Past Continuous: in progress past → I was working (when...)',
          'Past Perfect: before another past → I had worked (before...)',
          'Future will: prediction, decision → I will work',
          'Future going to: plan, evidence → I am going to work',
        ],
        examples: [
          { sentence: 'She works, is working, has worked, worked, was working, had worked, will work, is going to work.', highlight: 'works', note: 'same verb across 8 tenses' },
          { sentence: 'I usually wake up at 7, but today I woke up late because I had been working until midnight.', highlight: 'had been working', note: 'natural mixed tense usage' },
        ],
        commonMistakes: [
          { wrong: 'Mixing tenses randomly in one paragraph.', correct: 'Be consistent with your time frame.', explanation: 'Decide: are you talking about past, present or future?' },
        ],
        tips: 'Print a tense chart and put it on your wall. After 2 weeks you\'ll stop needing it.',
      },
    ],
  },

  articles: {
    lessons: [
      {
        id: 'article-a',
        title: 'Using "A"',
        duration: '4 min',
        explanation: 'Use "a" before words starting with a consonant SOUND. It introduces a singular countable noun for the first time.',
        rules: [
          'A + consonant sound: a car, a book, a university (u = consonant sound!)',
          'First mention of something not previously discussed',
          'One of many — not specific',
          'Jobs and descriptions: She is a doctor.',
        ],
        examples: [
          { sentence: 'I saw a dog in the park.', highlight: 'a dog', note: 'first mention, not specific' },
          { sentence: 'He is a teacher.', highlight: 'a teacher', note: 'job description' },
          { sentence: 'She has a university degree.', highlight: 'a university', note: '"u" sounds like "yoo" = consonant sound' },
          { sentence: 'Can I have a coffee please?', highlight: 'a coffee', note: 'one of many' },
        ],
        commonMistakes: [
          { wrong: 'I want an university degree.', correct: 'I want a university degree.', explanation: 'University starts with consonant SOUND "yoo"' },
          { wrong: 'She is doctor.', correct: 'She is a doctor.', explanation: 'Always use article before job titles' },
        ],
        tips: 'Listen to the SOUND, not the letter. "A hour" is wrong (silent h = vowel sound) → "An hour" is correct.',
      },
      {
        id: 'article-an',
        title: 'Using "An"',
        duration: '4 min',
        explanation: 'Use "an" before words starting with a vowel SOUND (a, e, i, o, u sounds). It makes the sentence flow smoothly.',
        rules: [
          'An + vowel sound: an apple, an hour, an honest man',
          'Silent H = vowel sound: an hour, an heir, an honour',
          'Letters by name: an MBA, an X-ray (M = em, X = ex = vowel sound)',
          'Never use "an" before consonant sounds',
        ],
        examples: [
          { sentence: 'I waited for an hour.', highlight: 'an hour', note: 'h is silent → vowel sound' },
          { sentence: 'She is an honest person.', highlight: 'an honest', note: 'silent h' },
          { sentence: 'He has an MBA.', highlight: 'an MBA', note: 'M = "em" = vowel sound' },
          { sentence: 'It was an amazing experience.', highlight: 'an amazing', note: 'a = vowel sound' },
        ],
        commonMistakes: [
          { wrong: 'a apple', correct: 'an apple', explanation: 'Apple starts with vowel sound "a"' },
          { wrong: 'an historic event', correct: 'a historic event', explanation: 'In most English, h in historic is pronounced' },
        ],
        tips: 'Say the word out loud. Does it start with a vowel sound? Then use "an". Trust your ear.',
      },
      {
        id: 'article-the',
        title: 'Using "The"',
        duration: '5 min',
        explanation: 'Use "the" when both speaker and listener know exactly which specific thing is being talked about.',
        rules: [
          'Second mention: I saw a dog. The dog was friendly.',
          'Only one exists: the sun, the moon, the internet',
          'Superlatives: the best, the biggest, the most',
          'Specific places known to both: the cinema, the bank',
        ],
        examples: [
          { sentence: 'I bought a shirt. The shirt is blue.', highlight: 'The shirt', note: 'second mention — now specific' },
          { sentence: 'The sun rises in the east.', highlight: 'The sun', note: 'unique thing' },
          { sentence: 'She is the best student in the class.', highlight: 'the best', note: 'superlative' },
          { sentence: 'Can you close the window?', highlight: 'the window', note: 'both know which one' },
        ],
        commonMistakes: [
          { wrong: 'I love the nature.', correct: 'I love nature.', explanation: 'General concepts = no article' },
          { wrong: 'She is best student.', correct: 'She is the best student.', explanation: 'Superlatives need "the"' },
        ],
        tips: 'The = "you know which one I mean". If there\'s no shared understanding of which one, don\'t use "the".',
      },
      {
        id: 'no-article',
        title: 'No Article (Zero Article)',
        duration: '4 min',
        explanation: 'Some nouns need no article — general concepts, most proper nouns, uncountable nouns used generally, and fixed phrases.',
        rules: [
          'General plural nouns: Dogs are friendly. (= dogs in general)',
          'Uncountable nouns generally: Water is essential. Love is blind.',
          'Most proper nouns: I live in Serbia. (not "the Serbia")',
          'Meals, sports, languages: breakfast, football, English',
        ],
        examples: [
          { sentence: 'I love music.', highlight: 'music', note: 'general uncountable noun' },
          { sentence: 'She speaks French.', highlight: 'French', note: 'language — no article' },
          { sentence: 'We played football after school.', highlight: 'football', note: 'sport — no article' },
          { sentence: 'Life is beautiful.', highlight: 'Life', note: 'general abstract noun' },
        ],
        commonMistakes: [
          { wrong: 'The love is important.', correct: 'Love is important.', explanation: 'Abstract nouns in general = no article' },
          { wrong: 'I play the tennis.', correct: 'I play tennis.', explanation: 'Sports = no article' },
        ],
        tips: 'Talking about things IN GENERAL (all dogs, all love, all water) = NO article.',
      },
      {
        id: 'articles-places',
        title: 'Articles with Places',
        duration: '5 min',
        explanation: 'Whether to use "the" or no article with geographical names follows specific patterns worth memorising.',
        rules: [
          'Countries: no article (Serbia, France) EXCEPT: the USA, the UK, the Netherlands',
          'Oceans, seas, rivers: the Atlantic, the Nile, the Thames',
          'Single mountains: no article (Everest) — mountain ranges: the Alps',
          'Cities: no article (London, Paris, Belgrade)',
        ],
        examples: [
          { sentence: 'I visited the United States last year.', highlight: 'the United States', note: 'plural country name = the' },
          { sentence: 'The Amazon is the longest river in South America.', highlight: 'The Amazon', note: 'rivers = the' },
          { sentence: 'She climbed Mont Blanc.', highlight: 'Mont Blanc', note: 'single mountain = no article' },
          { sentence: 'The Alps are beautiful in winter.', highlight: 'The Alps', note: 'mountain range = the' },
        ],
        commonMistakes: [
          { wrong: 'I live in the France.', correct: 'I live in France.', explanation: 'Most country names = no article' },
          { wrong: 'She swam in Atlantic.', correct: 'She swam in the Atlantic.', explanation: 'Oceans always use "the"' },
        ],
        tips: 'If the name is plural or contains a common noun (Kingdom, States, Republic) → use "the".',
      },
      {
        id: 'articles-review',
        title: 'Articles — Full Review',
        duration: '6 min',
        explanation: 'Master all article rules with a comprehensive review and tricky edge cases that catch even advanced learners.',
        rules: [
          'a = one of many, first mention, consonant sound',
          'an = one of many, first mention, vowel sound',
          'the = specific, both know which, unique thing',
          'no article = general concepts, proper nouns, sports, languages, meals',
        ],
        examples: [
          { sentence: 'A dog is a loyal animal. The dog I have is called Max.', highlight: 'A dog', note: 'general → specific with "the"' },
          { sentence: 'I had an egg for breakfast. The egg was fresh.', highlight: 'an egg', note: 'first mention → second mention' },
          { sentence: 'Life is short, but the life I\'ve lived has been amazing.', highlight: 'the life', note: 'general "life" vs specific "the life I lived"' },
        ],
        commonMistakes: [
          { wrong: 'She gave me an useful tip.', correct: 'She gave me a useful tip.', explanation: 'Useful = "yoo-seful" = consonant sound = a' },
          { wrong: 'He is best player.', correct: 'He is the best player.', explanation: 'Superlatives always need "the"' },
        ],
        tips: 'Articles are one of the hardest parts of English for non-native speakers. Practice daily — it becomes automatic.',
      },
    ],
  },

  prepositions: {
    lessons: [
      {
        id: 'prep-time-in-on-at',
        title: 'Time: in, on, at',
        duration: '5 min',
        explanation: 'In, on, and at are the three main prepositions of time. Each is used for a different level of time specificity.',
        rules: [
          'AT — precise time: at 7pm, at midnight, at noon, at the weekend',
          'ON — days and dates: on Monday, on 5th June, on Christmas Day',
          'IN — longer periods: in the morning, in March, in 2024, in winter',
          'No preposition before: last, next, this, every (last Monday, next year)',
        ],
        examples: [
          { sentence: 'The meeting is at 3pm on Friday.', highlight: 'at 3pm on Friday', note: 'time + day' },
          { sentence: 'She was born in March 1995.', highlight: 'in March', note: 'month = in' },
          { sentence: 'We always eat together on Sundays.', highlight: 'on Sundays', note: 'day = on' },
          { sentence: 'I\'ll see you next Monday — no preposition needed.', highlight: 'next Monday', note: 'next/last/this = no prep' },
        ],
        commonMistakes: [
          { wrong: 'I was born on 1995.', correct: 'I was born in 1995.', explanation: 'Years use "in"' },
          { wrong: 'See you at Monday.', correct: 'See you on Monday.', explanation: 'Days use "on"' },
        ],
        tips: 'Think of it as zooming in: IN (big period) → ON (day) → AT (exact moment).',
      },
      {
        id: 'prep-place-in-on-at',
        title: 'Place: in, on, at',
        duration: '5 min',
        explanation: 'The same three prepositions are used for place, but with different rules based on type and size of location.',
        rules: [
          'AT — specific point/location: at the bus stop, at the corner, at school',
          'ON — surface or line: on the table, on the wall, on the street',
          'IN — enclosed space: in the box, in the room, in the city',
          'AT = address point, IN = inside a city/country',
        ],
        examples: [
          { sentence: 'She is at the airport.', highlight: 'at the airport', note: 'specific location point' },
          { sentence: 'The book is on the shelf.', highlight: 'on the shelf', note: 'on a surface' },
          { sentence: 'He lives in Belgrade.', highlight: 'in Belgrade', note: 'inside a city' },
          { sentence: 'I left my phone in the car.', highlight: 'in the car', note: 'enclosed space' },
        ],
        commonMistakes: [
          { wrong: 'She is on the hospital.', correct: 'She is in the hospital.', explanation: 'Enclosed space = in' },
          { wrong: 'I live at Paris.', correct: 'I live in Paris.', explanation: 'Cities use "in"' },
        ],
        tips: 'AT = where you are (point). IN = what surrounds you. ON = what you\'re touching/resting on.',
      },
      {
        id: 'prep-movement',
        title: 'Prepositions of Movement',
        duration: '5 min',
        explanation: 'Movement prepositions show direction and path. They are used with action verbs like go, walk, run, drive, fly.',
        rules: [
          'To: destination — go to school, travel to Spain',
          'From: origin/starting point — come from, fly from London',
          'Into/out of: entering or leaving an enclosed space',
          'Through: movement from one side to the other',
        ],
        examples: [
          { sentence: 'She walked to the shop.', highlight: 'to the shop', note: 'destination' },
          { sentence: 'He came from Italy.', highlight: 'from Italy', note: 'origin' },
          { sentence: 'They drove through the tunnel.', highlight: 'through the tunnel', note: 'movement from one side to other' },
          { sentence: 'She jumped into the pool.', highlight: 'into the pool', note: 'entering enclosed space' },
        ],
        commonMistakes: [
          { wrong: 'I go to home.', correct: 'I go home.', explanation: 'Home is used without "to" — it\'s an adverb here' },
          { wrong: 'She entered into the room.', correct: 'She entered the room.', explanation: '"Enter" already includes the meaning of "into"' },
        ],
        tips: '"Go to" needs a place noun. "Go home / go there / go somewhere" — these special words don\'t need "to".',
      },
      {
        id: 'prep-direction',
        title: 'Direction Prepositions',
        duration: '5 min',
        explanation: 'Direction prepositions describe where something is pointing, moving, or facing relative to a reference point.',
        rules: [
          'Towards: moving in the direction of (not necessarily reaching)',
          'Away from: moving in the opposite direction',
          'Along: following the length of something',
          'Past: going beyond a point without stopping',
        ],
        examples: [
          { sentence: 'She walked towards me.', highlight: 'towards me', note: 'moving in my direction' },
          { sentence: 'He ran away from the noise.', highlight: 'away from the noise', note: 'opposite direction' },
          { sentence: 'We strolled along the river.', highlight: 'along the river', note: 'following the river\'s path' },
          { sentence: 'Turn right just past the bank.', highlight: 'past the bank', note: 'beyond the bank' },
        ],
        commonMistakes: [
          { wrong: 'Go toward the left.', correct: 'Go to the left / turn left.', explanation: '"Towards" is for a target, not a direction instruction' },
          { wrong: 'Walk along to the bridge.', correct: 'Walk along the river to the bridge.', explanation: '"Along" needs the path object, then "to" for destination' },
        ],
        tips: 'Towards = moving in that direction but may not arrive. To = arriving at the destination.',
      },
      {
        id: 'prep-transport',
        title: 'Prepositions with Transport',
        duration: '4 min',
        explanation: 'Different transport types use different prepositions. The rules are mostly consistent and learnable.',
        rules: [
          'BY + vehicle (general method): by car, by train, by plane, by bus',
          'ON + public/group transport: on the bus, on the train, on the plane',
          'IN + private/small vehicle: in the car, in a taxi, in a helicopter',
          'No article for method: travel by car (not by a car)',
        ],
        examples: [
          { sentence: 'I usually travel by train.', highlight: 'by train', note: 'method of transport' },
          { sentence: 'I met her on the bus.', highlight: 'on the bus', note: 'specific vehicle' },
          { sentence: 'They arrived in a taxi.', highlight: 'in a taxi', note: 'small private vehicle' },
          { sentence: 'She flew to Rome by plane.', highlight: 'by plane', note: 'method = no article' },
        ],
        commonMistakes: [
          { wrong: 'I came by the car.', correct: 'I came by car.', explanation: '"By + vehicle" as method uses no article' },
          { wrong: 'She is in the bus.', correct: 'She is on the bus.', explanation: 'Public transport (bus, train, plane) = on' },
        ],
        tips: 'Quick rule: on = public transport (can stand up inside). in = private vehicle (you\'re enclosed, usually seated in a car).',
      },
      {
        id: 'prep-adjectives',
        title: 'Prepositions after Adjectives',
        duration: '5 min',
        explanation: 'Many adjectives are always followed by specific prepositions. These combinations must be memorised.',
        rules: [
          'OF: afraid of, proud of, tired of, ashamed of, capable of, full of',
          'AT: good at, bad at, surprised at, shocked at, amazed at',
          'WITH: happy with, satisfied with, pleased with, bored with, angry with',
          'ABOUT: worried about, excited about, enthusiastic about, sorry about',
        ],
        examples: [
          { sentence: 'She is afraid of spiders.', highlight: 'afraid of', note: 'fixed combination' },
          { sentence: 'He is very good at maths.', highlight: 'good at', note: 'skill = at' },
          { sentence: 'I\'m really excited about the trip.', highlight: 'excited about', note: 'feeling about something' },
          { sentence: 'Are you satisfied with the result?', highlight: 'satisfied with', note: 'fixed phrase' },
        ],
        commonMistakes: [
          { wrong: 'I am good in English.', correct: 'I am good at English.', explanation: 'Skills use "good at", not "good in"' },
          { wrong: 'She is afraid from dogs.', correct: 'She is afraid of dogs.', explanation: 'Afraid is always followed by "of"' },
        ],
        tips: 'When you learn a new adjective, always learn its preposition partner too. Write them as pairs.',
      },
      {
        id: 'prep-verbs',
        title: 'Prepositions after Verbs',
        duration: '5 min',
        explanation: 'Many verbs are always followed by a specific preposition before the object. These are called "prepositional verbs".',
        rules: [
          'FOR: wait for, look for, ask for, apply for, pay for, care for',
          'TO: listen to, talk to, belong to, apologise to, refer to',
          'AT: look at, stare at, aim at, laugh at, shout at',
          'ABOUT: talk about, think about, worry about, dream about, complain about',
        ],
        examples: [
          { sentence: 'She is waiting for the bus.', highlight: 'waiting for', note: 'wait always takes "for"' },
          { sentence: 'Please listen to me.', highlight: 'listen to', note: 'listen always takes "to"' },
          { sentence: 'He applied for the job.', highlight: 'applied for', note: 'apply always takes "for"' },
          { sentence: 'Stop laughing at me!', highlight: 'laughing at', note: 'laugh always takes "at"' },
        ],
        commonMistakes: [
          { wrong: 'I\'m looking for my keys. / I\'m looking at my keys.', correct: 'Look for = search. Look at = observe.', explanation: 'Different prepositions = different meanings' },
          { wrong: 'Please listen me.', correct: 'Please listen to me.', explanation: 'Listen always needs "to" before the object' },
        ],
        tips: 'Look FOR = search/find. Look AT = observe. Look AFTER = take care of. One verb, three meanings from prepositions!',
      },
      {
        id: 'prep-review',
        title: 'Prepositions — Full Review',
        duration: '6 min',
        explanation: 'Quick reference for the most important preposition rules across time, place, movement, and fixed combinations.',
        rules: [
          'Time: AT (exact) → ON (day) → IN (period/month/year)',
          'Place: AT (point) → ON (surface) → IN (enclosed space)',
          'Movement: to (destination), from (origin), through (across), into (entering)',
          'Method: by + transport (no article): by car, by train',
        ],
        examples: [
          { sentence: 'I arrived at the airport on Monday morning. My flight left in the afternoon.', highlight: 'at the airport', note: 'place + time prepositions together' },
          { sentence: 'She is good at listening to people and caring for others.', highlight: 'good at', note: 'adjective + verb prepositions' },
        ],
        commonMistakes: [
          { wrong: 'See you in Monday at the morning.', correct: 'See you on Monday in the morning.', explanation: 'Days = ON, parts of day = IN' },
        ],
        tips: 'Prepositions have no perfect logic — they must be learned in context. Read widely and note which prepositions follow which words.',
      },
    ],
  },

  conditionals: {
    lessons: [
      {
        id: 'zero-conditional',
        title: 'Zero Conditional',
        duration: '4 min',
        explanation: 'Used for universal truths, scientific facts, and things that are always true. Both clauses use Present Simple.',
        rules: [
          'If + Present Simple, Present Simple',
          'Expresses facts and laws — always true',
          'Can use "when" instead of "if" — same meaning',
          'No time restriction — always happens',
        ],
        examples: [
          { sentence: 'If you heat water to 100°C, it boils.', highlight: 'If you heat', note: 'scientific fact' },
          { sentence: 'When it rains, the ground gets wet.', highlight: 'When it rains', note: '"when" for certain events' },
          { sentence: 'If you don\'t water plants, they die.', highlight: 'If you don\'t water', note: 'always true consequence' },
          { sentence: 'If I eat too much, I feel sick.', highlight: 'If I eat', note: 'personal fact/habit' },
        ],
        commonMistakes: [
          { wrong: 'If you will heat water, it boils.', correct: 'If you heat water, it boils.', explanation: 'Zero conditional = Present Simple in both clauses' },
        ],
        tips: 'Zero conditional = law of nature or personal truth. Swap "if" for "when" — if the meaning stays the same, it\'s zero conditional.',
      },
      {
        id: 'first-conditional',
        title: 'First Conditional',
        duration: '5 min',
        explanation: 'Used for real and possible future situations. The condition is likely to happen.',
        rules: [
          'If + Present Simple, will + base verb',
          'The condition is realistic and possible',
          'Can use unless (= if not): Unless you hurry, you\'ll miss the train.',
          'Modal alternatives: might, can, may instead of will',
        ],
        examples: [
          { sentence: 'If it rains tomorrow, we\'ll stay inside.', highlight: 'If it rains', note: 'real future possibility' },
          { sentence: 'If you study hard, you will pass the exam.', highlight: 'you will pass', note: 'likely result' },
          { sentence: 'Unless you call her, she won\'t know.', highlight: 'Unless you call', note: 'unless = if not' },
          { sentence: 'If he comes early, we can start sooner.', highlight: 'we can start', note: 'can instead of will' },
        ],
        commonMistakes: [
          { wrong: 'If it will rain, we\'ll stay inside.', correct: 'If it rains, we\'ll stay inside.', explanation: 'Never use will in the if-clause' },
          { wrong: 'If you will study, you will pass.', correct: 'If you study, you will pass.', explanation: 'Present Simple in the condition' },
        ],
        tips: 'NEVER use "will" in the if-clause. If + Present Simple — always. This is the most common conditional mistake.',
      },
      {
        id: 'second-conditional',
        title: 'Second Conditional',
        duration: '5 min',
        explanation: 'Used for hypothetical or unlikely situations in the present or future. The speaker doesn\'t expect it to happen.',
        rules: [
          'If + Past Simple, would + base verb',
          'The condition is imaginary or unlikely',
          'Were used for all persons: If I were you...',
          'Could/might instead of would for less certainty',
        ],
        examples: [
          { sentence: 'If I had more money, I would travel the world.', highlight: 'If I had', note: 'hypothetical — I don\'t have money now' },
          { sentence: 'If she were here, she would know what to do.', highlight: 'If she were', note: 'were for all persons in formal use' },
          { sentence: 'If I were you, I wouldn\'t do that.', highlight: 'If I were you', note: 'giving advice with second conditional' },
          { sentence: 'What would you do if you won the lottery?', highlight: 'would you do', note: 'question form' },
        ],
        commonMistakes: [
          { wrong: 'If I would have money, I would travel.', correct: 'If I had money, I would travel.', explanation: 'Never use would in the if-clause' },
          { wrong: 'If I was you.', correct: 'If I were you.', explanation: '"Were" preferred for all persons in second conditional' },
        ],
        tips: '"If I were you" is the most useful second conditional phrase. Learn it first — you\'ll use it constantly for giving advice.',
      },
      {
        id: 'third-conditional',
        title: 'Third Conditional',
        duration: '6 min',
        explanation: 'Used for imaginary situations in the past — things that didn\'t happen. Often expresses regret or criticism.',
        rules: [
          'If + Past Perfect, would have + past participle',
          'Describes an UNREAL past — it didn\'t actually happen',
          'Expresses: regret, criticism, missed opportunities',
          'Could have / might have instead of would have',
        ],
        examples: [
          { sentence: 'If I had studied harder, I would have passed.', highlight: 'If I had studied', note: 'I didn\'t study → I didn\'t pass' },
          { sentence: 'She would have come if she had known about it.', highlight: 'would have come', note: 'she didn\'t know → she didn\'t come' },
          { sentence: 'If he hadn\'t been late, he might have got the job.', highlight: 'might have got', note: 'might instead of would' },
          { sentence: 'Would you have helped if I had asked?', highlight: 'Would you have helped', note: 'question form' },
        ],
        commonMistakes: [
          { wrong: 'If I would have studied, I would have passed.', correct: 'If I had studied, I would have passed.', explanation: 'Never would in the if-clause — use Past Perfect' },
          { wrong: 'I would have went.', correct: 'I would have gone.', explanation: 'Always past participle after would have' },
        ],
        tips: 'Third conditional = looking back with regret. "If only I had..." is the same idea in a shorter form.',
      },
      {
        id: 'mixed-conditionals',
        title: 'Mixed Conditionals',
        duration: '6 min',
        explanation: 'Mix past and present conditionals to show how a past event affects the present, or vice versa.',
        rules: [
          'Past condition → present result: If + Past Perfect, would + base verb',
          'Present condition → past result: If + Past Simple, would have + pp',
          'Mixed conditionals express cross-time relationships',
          'Very common in natural conversation',
        ],
        examples: [
          { sentence: 'If I had studied medicine, I would be a doctor now.', highlight: 'would be a doctor now', note: 'past action → present result' },
          { sentence: 'If she were more careful, she wouldn\'t have made that mistake.', highlight: 'wouldn\'t have made', note: 'present character → past result' },
          { sentence: 'If I hadn\'t met him, I wouldn\'t be living here.', highlight: 'wouldn\'t be living', note: 'past event → present situation' },
          { sentence: 'If I were better at saving money, I could have bought that house.', highlight: 'could have bought', note: 'present habit → past missed opportunity' },
        ],
        commonMistakes: [
          { wrong: 'Avoiding mixed conditionals — only using pure 2nd or 3rd.', correct: 'Use mixed when the time frames genuinely differ.', explanation: 'Real speech often crosses time frames' },
        ],
        tips: 'If the condition and result are in different time frames, you need a mixed conditional. Ask: is the condition past or present? Is the result past or present?',
      },
    ],
  },

  'modal-verbs': {
    lessons: [
      {
        id: 'can-could',
        title: 'Can & Could',
        duration: '5 min',
        explanation: 'Can = present ability or permission. Could = past ability, polite request, or possibility.',
        rules: [
          'Can + base verb: I can swim. (present ability)',
          'Could + base verb: I could swim when I was young. (past ability)',
          'Polite request: Could you help me? (more polite than "Can")',
          'Possibility: It could be true. (maybe)',
        ],
        examples: [
          { sentence: 'She can speak 3 languages.', highlight: 'can speak', note: 'present ability' },
          { sentence: 'Could you pass the salt, please?', highlight: 'Could you', note: 'polite request' },
          { sentence: 'He could run fast when he was young.', highlight: 'could run', note: 'past ability' },
          { sentence: 'It could rain later.', highlight: 'could rain', note: 'possibility' },
        ],
        commonMistakes: [
          { wrong: 'I can to swim.', correct: 'I can swim.', explanation: 'Modal verbs never followed by "to"' },
          { wrong: 'She cans drive.', correct: 'She can drive.', explanation: 'Modals never take -s for he/she/it' },
        ],
        tips: 'Could is almost always more polite than can. Use could in formal situations and with strangers.',
      },
      {
        id: 'should-ought',
        title: 'Should & Ought To',
        duration: '5 min',
        explanation: 'Both express advice and recommendation. Should is more common; ought to is slightly more formal.',
        rules: [
          'Should + base verb: advice or recommendation',
          'Ought to + base verb: same meaning, slightly more formal',
          'Negative: shouldn\'t (you should not do this)',
          'Past form: should have + past participle (regret about past)',
        ],
        examples: [
          { sentence: 'You should see a doctor.', highlight: 'should see', note: 'advice' },
          { sentence: 'You shouldn\'t eat so much sugar.', highlight: 'shouldn\'t eat', note: 'negative advice' },
          { sentence: 'I should have called earlier. Sorry.', highlight: 'should have called', note: 'regret about past action' },
          { sentence: 'We ought to leave now.', highlight: 'ought to leave', note: 'mild obligation' },
        ],
        commonMistakes: [
          { wrong: 'You should to go.', correct: 'You should go.', explanation: 'Should + base verb, no "to"' },
          { wrong: 'I should have went.', correct: 'I should have gone.', explanation: 'Always past participle after should have' },
        ],
        tips: '"Should have + past participle" = regret. This is one of the most common structures in spoken English.',
      },
      {
        id: 'must-have-to',
        title: 'Must & Have To',
        duration: '5 min',
        explanation: 'Both express strong obligation, but must comes from the speaker while have to comes from external rules or authority.',
        rules: [
          'Must + base verb: strong internal obligation (speaker decides)',
          'Have to + base verb: external obligation (rules, laws, boss)',
          'Must not = prohibition (don\'t do this!)',
          'Don\'t have to = no obligation (optional)',
        ],
        examples: [
          { sentence: 'I must finish this report today.', highlight: 'must finish', note: 'self-imposed obligation' },
          { sentence: 'You have to wear a seatbelt by law.', highlight: 'have to wear', note: 'external law' },
          { sentence: 'You must not smoke here.', highlight: 'must not', note: 'prohibition' },
          { sentence: 'You don\'t have to come if you\'re busy.', highlight: 'don\'t have to', note: 'no obligation — optional' },
        ],
        commonMistakes: [
          { wrong: 'Must not = Don\'t have to', correct: 'Must not ≠ Don\'t have to', explanation: 'Must not = forbidden. Don\'t have to = optional.' },
          { wrong: 'I must to go.', correct: 'I must go.', explanation: 'Must + base verb, no "to"' },
        ],
        tips: 'MUST NOT = forbidden (dangerous if confused). DON\'T HAVE TO = your choice. This distinction is critical.',
      },
      {
        id: 'may-might',
        title: 'May & Might',
        duration: '5 min',
        explanation: 'Both express possibility. May = more likely (~50%). Might = less certain (~30%). May also used for formal permission.',
        rules: [
          'May + base verb: ~50% possibility or formal permission',
          'Might + base verb: less than 50% possibility',
          'May I...? = formal permission request',
          'Might have + pp = past possibility',
        ],
        examples: [
          { sentence: 'It may rain this afternoon.', highlight: 'may rain', note: 'possible, roughly 50%' },
          { sentence: 'I might go to the party — not sure yet.', highlight: 'might go', note: 'uncertain, less likely' },
          { sentence: 'May I leave early today?', highlight: 'May I', note: 'formal permission request' },
          { sentence: 'She might have missed the bus.', highlight: 'might have missed', note: 'past possibility' },
        ],
        commonMistakes: [
          { wrong: 'I might to call you.', correct: 'I might call you.', explanation: 'Modal + base verb, no "to"' },
          { wrong: 'May be I\'ll go.', correct: 'Maybe I\'ll go. / I may go.', explanation: 'Maybe (one word) = adverb. May be (two words) = verb phrase.' },
        ],
        tips: '"May be" (two words) = verb. "Maybe" (one word) = adverb meaning perhaps. Don\'t confuse them!',
      },
      {
        id: 'will-would',
        title: 'Will & Would',
        duration: '5 min',
        explanation: 'Will = future certainty and spontaneous decisions. Would = conditional situations, polite requests, and hypothetical ideas.',
        rules: [
          'Will: predictions, promises, instant decisions',
          'Would: conditional sentences, polite requests, hypothetical',
          'Would like = polite want: Would you like some tea?',
          'Would have = unreal past: I would have helped.',
        ],
        examples: [
          { sentence: 'I will call you back in 5 minutes.', highlight: 'will call', note: 'promise' },
          { sentence: 'Would you like some tea?', highlight: 'Would you like', note: 'polite offer' },
          { sentence: 'If I had money, I would travel the world.', highlight: 'would travel', note: 'hypothetical' },
          { sentence: 'I would have helped if I had known.', highlight: 'would have helped', note: 'unreal past' },
        ],
        commonMistakes: [
          { wrong: 'I would go there yesterday.', correct: 'I would have gone there.', explanation: 'Past hypothetical needs would have + pp' },
          { wrong: 'Would you like to would come?', correct: 'Would you like to come?', explanation: 'Would like to + base verb — not two modals' },
        ],
        tips: '"Would you like...?" is always more polite than "Do you want...?" Always use it in formal situations.',
      },
      {
        id: 'modals-passive',
        title: 'Modals in Passive Voice',
        duration: '6 min',
        explanation: 'Modal verbs can combine with passive voice for rules, instructions, and formal writing. Very common in official contexts.',
        rules: [
          'Modal + be + past participle: It must be done. It can be fixed.',
          'Past passive modal: modal + have been + pp: It should have been reported.',
          'Common in formal writing, instructions, signs, legal texts',
          'All modals work: can, must, should, will, may, might',
        ],
        examples: [
          { sentence: 'This form must be completed in full.', highlight: 'must be completed', note: 'formal instruction' },
          { sentence: 'The problem can be solved easily.', highlight: 'can be solved', note: 'possibility passive' },
          { sentence: 'Mistakes could have been avoided.', highlight: 'could have been avoided', note: 'past passive modal' },
          { sentence: 'It should be noted that results may vary.', highlight: 'should be noted', note: 'formal writing phrase' },
        ],
        commonMistakes: [
          { wrong: 'It must be solve.', correct: 'It must be solved.', explanation: 'Always past participle in passive' },
          { wrong: 'Should been done.', correct: 'Should have been done.', explanation: 'Modal + have been + pp for past' },
        ],
        tips: 'Modal passives are everywhere in academic writing, legal texts and formal instructions. Learn to spot them.',
      },
      {
        id: 'modals-review',
        title: 'Modal Verbs — Full Review',
        duration: '7 min',
        explanation: 'Quick reference guide for all modal verbs, their meanings, and key usage patterns.',
        rules: [
          'Can/Could: ability, possibility, permission, polite request',
          'Should/Ought to: advice, recommendation, mild obligation',
          'Must/Have to: strong obligation, prohibition (must not)',
          'May/Might: possibility, formal permission',
          'Will/Would: future, conditional, polite offers',
          'Golden rule: Modal + BASE VERB. No -s, no -ed, no "to".',
        ],
        examples: [
          { sentence: 'You should see a doctor — you might be seriously ill, and it could get worse.', highlight: 'should', note: '3 modals in one sentence' },
          { sentence: 'Visitors must not take photos. Flash can damage the artwork.', highlight: 'must not', note: 'prohibition + explanation' },
        ],
        commonMistakes: [
          { wrong: 'I must to go. / She cans sing. / He should to call.', correct: 'I must go. / She can sing. / He should call.', explanation: 'NEVER use "to" after modals, NEVER add -s' },
        ],
        tips: 'Modal verb + BASE VERB. No to. No -s. No -ed. No exceptions. Tattoo this on your brain.',
      },
    ],
  },

  'passive-voice': {
    lessons: [
      {
        id: 'passive-intro',
        title: 'What Is Passive Voice?',
        duration: '5 min',
        explanation: 'In active voice the subject does the action. In passive voice the subject receives the action. We use passive when the doer is unknown, unimportant, or obvious.',
        rules: [
          'Active: Subject + verb + object (The chef cooked the meal.)',
          'Passive: Object becomes subject + be + past participle (The meal was cooked.)',
          'By + agent: optional — only mention if important (by the chef)',
          'The verb "be" changes tense; the past participle stays the same',
        ],
        examples: [
          { sentence: 'Active: The police arrested the thief.', highlight: 'arrested', note: 'active — police is the doer' },
          { sentence: 'Passive: The thief was arrested (by the police).', highlight: 'was arrested', note: 'passive — thief is the focus' },
          { sentence: 'English is spoken in many countries.', highlight: 'is spoken', note: 'agent unknown/unimportant' },
          { sentence: 'The report will be published tomorrow.', highlight: 'will be published', note: 'doer not mentioned' },
        ],
        commonMistakes: [
          { wrong: 'The house was build in 1990.', correct: 'The house was built in 1990.', explanation: 'Must use past participle — not past simple' },
          { wrong: 'The book is writed by Tolkien.', correct: 'The book was written by Tolkien.', explanation: 'Irregular past participle: write → written' },
        ],
        tips: 'Use passive when what happened matters more than who did it. Don\'t overuse it — active is clearer in most cases.',
      },
      {
        id: 'passive-present',
        title: 'Passive: Present Tenses',
        duration: '5 min',
        explanation: 'Present Simple and Present Continuous passive are used for current states, ongoing situations, and general facts.',
        rules: [
          'Present Simple passive: am/is/are + past participle',
          'Present Continuous passive: am/is/are + being + past participle',
          'Simple = general state; Continuous = happening right now',
          'Present Perfect passive: have/has + been + past participle',
        ],
        examples: [
          { sentence: 'This product is made in Germany.', highlight: 'is made', note: 'present simple passive — general fact' },
          { sentence: 'The road is being repaired at the moment.', highlight: 'is being repaired', note: 'present continuous passive — in progress now' },
          { sentence: 'The results have been announced.', highlight: 'have been announced', note: 'present perfect passive' },
          { sentence: 'English is taught in schools worldwide.', highlight: 'is taught', note: 'general present fact' },
        ],
        commonMistakes: [
          { wrong: 'The car is been repaired.', correct: 'The car is being repaired.', explanation: 'Continuous passive = is + BEING + pp' },
          { wrong: 'It has been announce.', correct: 'It has been announced.', explanation: 'Always past participle after been' },
        ],
        tips: 'Is + being + pp = happening now. Is + pp = general fact. Have/has + been + pp = just completed.',
      },
      {
        id: 'passive-past',
        title: 'Passive: Past Tenses',
        duration: '5 min',
        explanation: 'Past passive is used to describe events where the focus is on what happened, not who did it. Very common in news and history.',
        rules: [
          'Past Simple passive: was/were + past participle',
          'Past Continuous passive: was/were + being + past participle',
          'Past Perfect passive: had been + past participle',
          'Common in news: "The building was destroyed..." ',
        ],
        examples: [
          { sentence: 'The Eiffel Tower was built in 1889.', highlight: 'was built', note: 'past simple passive' },
          { sentence: 'The suspect was being questioned when he escaped.', highlight: 'was being questioned', note: 'past continuous passive' },
          { sentence: 'By the time we arrived, the decision had been made.', highlight: 'had been made', note: 'past perfect passive' },
          { sentence: 'Three people were injured in the accident.', highlight: 'were injured', note: 'news-style past passive' },
        ],
        commonMistakes: [
          { wrong: 'The building was destroy.', correct: 'The building was destroyed.', explanation: 'Was/were always needs past participle' },
          { wrong: 'It were built in 1900.', correct: 'It was built in 1900.', explanation: 'Singular subjects use was, not were' },
        ],
        tips: 'Read BBC News or any newspaper — almost every other sentence uses past passive. It\'s the language of facts and events.',
      },
      {
        id: 'passive-modals',
        title: 'Passive with Modal Verbs',
        duration: '5 min',
        explanation: 'Passive forms combine with modal verbs to express rules, obligations, possibilities and formal instructions.',
        rules: [
          'Modal + be + past participle: It must be done.',
          'Past: Modal + have been + past participle: It should have been fixed.',
          'All modals work: can, must, should, will, may, might, could',
          'Very common in formal writing, signs, manuals',
        ],
        examples: [
          { sentence: 'This door must be kept closed at all times.', highlight: 'must be kept', note: 'rule/obligation' },
          { sentence: 'The error could have been prevented.', highlight: 'could have been prevented', note: 'past possibility passive' },
          { sentence: 'All applications should be submitted online.', highlight: 'should be submitted', note: 'instruction' },
          { sentence: 'The files will be sent to you shortly.', highlight: 'will be sent', note: 'future passive' },
        ],
        commonMistakes: [
          { wrong: 'It must be fix.', correct: 'It must be fixed.', explanation: 'Past participle after be, not base verb' },
          { wrong: 'Should been reported.', correct: 'Should have been reported.', explanation: 'Past: should + have + been + pp' },
        ],
        tips: 'Modal + be + pp for present/future. Modal + have been + pp for past. Keep this pattern clear.',
      },
      {
        id: 'causative-have-get',
        title: 'Causative: Have & Get',
        duration: '6 min',
        explanation: 'The causative form means you arrange for someone else to do something for you — you don\'t do it yourself.',
        rules: [
          'Have + object + past participle: I had my hair cut. (someone cuts it for you)',
          'Get + object + past participle: I got my car fixed. (slightly more informal)',
          'Get + someone + to + base verb: I got him to fix it. (convince someone)',
          'Have/get changes tense; the past participle stays the same',
        ],
        examples: [
          { sentence: 'I had my hair cut yesterday.', highlight: 'had my hair cut', note: 'someone cut it for me' },
          { sentence: 'She got her phone repaired at the shop.', highlight: 'got her phone repaired', note: 'informal causative' },
          { sentence: 'We\'re having the house painted next week.', highlight: 'having the house painted', note: 'future arrangement' },
          { sentence: 'Can you get the documents signed today?', highlight: 'get the documents signed', note: 'request to arrange' },
        ],
        commonMistakes: [
          { wrong: 'I had my hair cut by myself.', correct: 'I cut my hair myself.', explanation: 'Causative implies someone else does it — not you' },
          { wrong: 'I had my car fix.', correct: 'I had my car fixed.', explanation: 'Always past participle in causative' },
        ],
        tips: '"Have/get something done" = you arrange it, someone else does it. Very natural in spoken English: "I\'m getting my eyes tested."',
      },
    ],
  },
}
