export const GRAMMAR_DATA = {
  tenses: {
    lessons: [
      {
        id: 'present-simple',
        title: 'Present Simple',
        duration: '5 min',
        explanation: 'Used for habits, facts, and routines. It describes things that are generally true or happen regularly.',
        rules: [
          'Subject + base verb (I/you/we/they)',
          'Subject + verb+s/es (he/she/it)',
          'Negative: don\'t / doesn\'t + base verb',
          'Question: Do/Does + subject + base verb?',
        ],
        examples: [
          { sentence: 'She works at a hospital.', highlight: 'works', note: 'regular habit' },
          { sentence: 'Water boils at 100°C.', highlight: 'boils', note: 'general fact' },
          { sentence: 'He doesn\'t like coffee.', highlight: 'doesn\'t like', note: 'negative form' },
          { sentence: 'Do they speak English?', highlight: 'Do speak', note: 'question form' },
        ],
        commonMistakes: [
          { wrong: 'She work every day.', correct: 'She works every day.', explanation: 'Add -s for he/she/it' },
          { wrong: 'He don\'t know.', correct: 'He doesn\'t know.', explanation: 'Use doesn\'t for he/she/it' },
        ],
        tips: 'Remember: he/she/it always gets an -s. When in doubt, say it out loud!',
      },
      {
        id: 'present-continuous',
        title: 'Present Continuous',
        duration: '5 min',
        explanation: 'Used for actions happening right now or temporary situations. Shows something is in progress at the moment of speaking.',
        rules: [
          'Subject + am/is/are + verb+ing',
          'I am, He/She/It is, You/We/They are',
          'Negative: am/is/are + not + verb+ing',
          'Cannot use with state verbs: know, love, want, understand',
        ],
        examples: [
          { sentence: 'I am studying English right now.', highlight: 'am studying', note: 'happening now' },
          { sentence: 'She is working from home this week.', highlight: 'is working', note: 'temporary situation' },
          { sentence: 'They aren\'t watching TV.', highlight: 'aren\'t watching', note: 'negative' },
          { sentence: 'Is he coming to the party?', highlight: 'Is coming', note: 'question' },
        ],
        commonMistakes: [
          { wrong: 'I am knowing the answer.', correct: 'I know the answer.', explanation: 'Know is a state verb — no -ing' },
          { wrong: 'She working now.', correct: 'She is working now.', explanation: 'Never forget the am/is/are' },
        ],
        tips: 'If you can say "in the middle of doing", use continuous. State verbs (know, like, want) never use -ing.',
      },
      {
        id: 'present-perfect',
        title: 'Present Perfect',
        duration: '6 min',
        explanation: 'Connects past actions to the present. Used for experiences, recent events, or unfinished situations. No specific time mentioned.',
        rules: [
          'Subject + have/has + past participle',
          'I/You/We/They have — He/She/It has',
          'Key words: already, yet, ever, never, just, since, for',
          'No specific time mentioned (not: yesterday, last week)',
        ],
        examples: [
          { sentence: 'I have visited Paris three times.', highlight: 'have visited', note: 'life experience' },
          { sentence: 'She has just finished the report.', highlight: 'has just finished', note: 'very recent action' },
          { sentence: 'Have you ever eaten sushi?', highlight: 'Have eaten', note: 'experience question' },
          { sentence: 'He hasn\'t called yet.', highlight: 'hasn\'t called', note: 'expected but not done' },
        ],
        commonMistakes: [
          { wrong: 'I have seen him yesterday.', correct: 'I saw him yesterday.', explanation: 'Yesterday = specific time → use Past Simple' },
          { wrong: 'She have finished.', correct: 'She has finished.', explanation: 'He/she/it uses HAS' },
        ],
        tips: 'No time word = Present Perfect. Specific time word (yesterday, in 2020) = Past Simple.',
      },
      {
        id: 'past-simple',
        title: 'Past Simple',
        duration: '5 min',
        explanation: 'Used for completed actions at a specific time in the past. The most common and important past tense.',
        rules: [
          'Regular verbs: add -ed (walked, talked, worked)',
          'Irregular verbs: learn them (go→went, see→saw, buy→bought)',
          'Negative: didn\'t + base verb (same for all persons)',
          'Question: Did + subject + base verb?',
        ],
        examples: [
          { sentence: 'We visited Rome last summer.', highlight: 'visited', note: 'specific time in past' },
          { sentence: 'She didn\'t go to the party.', highlight: 'didn\'t go', note: 'negative — base verb after didn\'t' },
          { sentence: 'Did you see that movie?', highlight: 'Did see', note: 'question form' },
          { sentence: 'He bought a new car yesterday.', highlight: 'bought', note: 'irregular verb' },
        ],
        commonMistakes: [
          { wrong: 'I didn\'t went there.', correct: 'I didn\'t go there.', explanation: 'After did/didn\'t always use base verb' },
          { wrong: 'Did she went?', correct: 'Did she go?', explanation: 'Base verb after Did, not past form' },
        ],
        tips: 'Learn the top 50 irregular verbs by heart. They appear in 80% of all conversations.',
      },
      {
        id: 'past-continuous',
        title: 'Past Continuous',
        duration: '5 min',
        explanation: 'Describes an action in progress at a specific past moment, often interrupted by another action.',
        rules: [
          'Subject + was/were + verb+ing',
          'I/He/She/It was — You/We/They were',
          'Often used with Past Simple: was doing (when) something happened',
          'Negative: was/were + not + verb+ing',
        ],
        examples: [
          { sentence: 'I was sleeping when the phone rang.', highlight: 'was sleeping', note: 'interrupted action' },
          { sentence: 'They were playing football all afternoon.', highlight: 'were playing', note: 'in progress in past' },
          { sentence: 'What were you doing at 8pm?', highlight: 'were you doing', note: 'question about past moment' },
          { sentence: 'She wasn\'t listening to me.', highlight: 'wasn\'t listening', note: 'negative' },
        ],
        commonMistakes: [
          { wrong: 'I was play when you called.', correct: 'I was playing when you called.', explanation: 'Must add -ing in continuous' },
          { wrong: 'They was working.', correct: 'They were working.', explanation: 'They/you/we = were, not was' },
        ],
        tips: 'Think of it like a movie scene — Past Continuous is the background, Past Simple is the interruption.',
      },
      {
        id: 'future-simple',
        title: 'Future Simple (will)',
        duration: '5 min',
        explanation: 'Used for predictions, spontaneous decisions, promises and offers. Will is the same for all persons.',
        rules: [
          'Subject + will + base verb (all persons same)',
          'Negative: will not / won\'t + base verb',
          'Question: Will + subject + base verb?',
          'Contractions: I\'ll, you\'ll, he\'ll, she\'ll, we\'ll, they\'ll',
        ],
        examples: [
          { sentence: 'I will call you tomorrow.', highlight: 'will call', note: 'promise' },
          { sentence: 'It will rain this afternoon.', highlight: 'will rain', note: 'prediction' },
          { sentence: 'I\'ll help you with that.', highlight: '\'ll help', note: 'spontaneous offer' },
          { sentence: 'Will you come to the meeting?', highlight: 'Will come', note: 'question' },
        ],
        commonMistakes: [
          { wrong: 'I will to go there.', correct: 'I will go there.', explanation: 'Never use "to" after will' },
          { wrong: 'He wills come.', correct: 'He will come.', explanation: 'Will never changes — no -s for he/she/it' },
        ],
        tips: 'Will = decision made at the moment of speaking. Going to = plan made before speaking.',
      },
      {
        id: 'future-going-to',
        title: 'Future: Going To',
        duration: '5 min',
        explanation: 'Used for plans already decided before speaking, and predictions based on visible evidence right now.',
        rules: [
          'Subject + am/is/are + going to + base verb',
          'Negative: am/is/are + not + going to + verb',
          'Question: Am/Is/Are + subject + going to + verb?',
          'Evidence-based: Look! It\'s going to rain! (clouds visible now)',
        ],
        examples: [
          { sentence: 'We are going to visit Paris next month.', highlight: 'are going to visit', note: 'pre-made plan' },
          { sentence: 'Look out! She is going to fall!', highlight: 'is going to fall', note: 'evidence-based prediction' },
          { sentence: 'I\'m not going to eat fast food anymore.', highlight: '\'m not going to eat', note: 'decision already made' },
          { sentence: 'Are they going to move to London?', highlight: 'going to move', note: 'question about plan' },
        ],
        commonMistakes: [
          { wrong: 'I going to call him.', correct: 'I am going to call him.', explanation: 'Never forget am/is/are before going to' },
          { wrong: 'She is going to goes.', correct: 'She is going to go.', explanation: 'Always base verb after going to' },
        ],
        tips: 'Will = in the moment. Going to = already planned. Both are correct, just different situations.',
      },
      {
        id: 'future-continuous',
        title: 'Future Continuous',
        duration: '6 min',
        explanation: 'Describes an action that will be in progress at a specific moment in the future. Also used for polite questions.',
        rules: [
          'Subject + will be + verb+ing',
          'Used for: action in progress at future time, polite questions',
          'Negative: will not be + verb+ing',
          'Question: Will + subject + be + verb+ing?',
        ],
        examples: [
          { sentence: 'At 8pm tomorrow I will be watching the game.', highlight: 'will be watching', note: 'in progress at future moment' },
          { sentence: 'Will you be using the car tonight?', highlight: 'Will be using', note: 'polite question' },
          { sentence: 'This time next week we\'ll be lying on the beach.', highlight: 'will be lying', note: 'future in progress' },
          { sentence: 'She won\'t be working on Sunday.', highlight: 'won\'t be working', note: 'negative' },
        ],
        commonMistakes: [
          { wrong: 'I will being work.', correct: 'I will be working.', explanation: 'will + be (not being) + verb+ing' },
          { wrong: 'He will be work.', correct: 'He will be working.', explanation: 'Must add -ing' },
        ],
        tips: 'Future Continuous for polite questions sounds more natural: "Will you be needing anything else?" vs "Will you need?"',
      },
      {
        id: 'present-perfect-continuous',
        title: 'Present Perfect Continuous',
        duration: '6 min',
        explanation: 'Emphasises the duration of an activity that started in the past and continues now, or recently stopped with a visible result.',
        rules: [
          'Subject + have/has + been + verb+ing',
          'Key words: for, since, how long, all day, lately, recently',
          'Focuses on DURATION, not the result',
          'Cannot use with state verbs (know, love, want)',
        ],
        examples: [
          { sentence: 'I have been studying for 3 hours.', highlight: 'have been studying', note: 'started past, still doing it' },
          { sentence: 'She has been crying — her eyes are red.', highlight: 'has been crying', note: 'visible result' },
          { sentence: 'How long have you been waiting?', highlight: 'have been waiting', note: 'duration question' },
          { sentence: 'They haven\'t been sleeping well lately.', highlight: 'haven\'t been sleeping', note: 'negative' },
        ],
        commonMistakes: [
          { wrong: 'I have been know him for years.', correct: 'I have known him for years.', explanation: 'Know = state verb, no continuous' },
          { wrong: 'She has been work here since 2020.', correct: 'She has been working here since 2020.', explanation: 'Must add -ing' },
        ],
        tips: 'FOR = duration (for 2 hours). SINCE = starting point (since Monday). Both go with this tense.',
      },
      {
        id: 'past-perfect',
        title: 'Past Perfect',
        duration: '6 min',
        explanation: 'Describes an action completed BEFORE another past action. It\'s the "past of the past" — the earlier event.',
        rules: [
          'Subject + had + past participle (same for ALL persons)',
          'Negative: had not (hadn\'t) + past participle',
          'Key words: before, after, when, already, by the time, never',
          'Shows which past action happened FIRST',
        ],
        examples: [
          { sentence: 'When I arrived, she had already left.', highlight: 'had already left', note: 'left before I arrived' },
          { sentence: 'He had never seen snow before that day.', highlight: 'had never seen', note: 'first experience ever' },
          { sentence: 'They had finished dinner before the guests arrived.', highlight: 'had finished', note: 'sequence of past events' },
          { sentence: 'I hadn\'t eaten all day.', highlight: 'hadn\'t eaten', note: 'negative' },
        ],
        commonMistakes: [
          { wrong: 'When I came, she already left.', correct: 'When I came, she had already left.', explanation: 'The earlier action needs had + pp' },
          { wrong: 'He had went there.', correct: 'He had gone there.', explanation: 'Had always uses past participle, not past simple' },
        ],
        tips: 'Draw a timeline. Past Perfect = the event further left (earlier). Past Simple = the event closer to now.',
      },
      {
        id: 'mixed-tenses',
        title: 'Mixed Tenses in Context',
        duration: '7 min',
        explanation: 'Real English uses multiple tenses together. Learn to choose the right tense based on context and time expressions.',
        rules: [
          'Read the time expressions: yesterday=Past, just=Present Perfect, at 8pm tomorrow=Future Continuous',
          'Look for sequence: had done (first) → did (second) → is doing (now)',
          'Context clues: already, still, yet, ever, never, ago, since, for',
          'Ask: When? Completed? Duration? Result?',
        ],
        examples: [
          { sentence: 'I was walking home when I saw him — he had been waiting for an hour.', highlight: 'was walking', note: '3 tenses: background / event / duration' },
          { sentence: 'She has lived here since she was born.', highlight: 'has lived', note: 'Present Perfect + Past Simple' },
          { sentence: 'He said he had already eaten.', highlight: 'had already eaten', note: 'reported speech — earlier past' },
          { sentence: 'By the time you arrive, I will have finished.', highlight: 'will have finished', note: 'Future Perfect — before a future point' },
        ],
        commonMistakes: [
          { wrong: 'I have seen him yesterday.', correct: 'I saw him yesterday.', explanation: 'Specific past time = Past Simple' },
          { wrong: 'By tomorrow I finish.', correct: 'By tomorrow I will have finished.', explanation: 'Deadline in future = Future Perfect' },
        ],
        tips: 'When stuck: identify the TIME, identify if the action is COMPLETE or IN PROGRESS, then choose.',
      },
      {
        id: 'tenses-review',
        title: 'Tenses — Full Review',
        duration: '8 min',
        explanation: 'A comprehensive overview of all English tenses and when to use each one. Use this as your reference sheet.',
        rules: [
          'Present Simple: habits, facts → I work',
          'Present Continuous: now, temporary → I am working',
          'Present Perfect: experience, result → I have worked',
          'Past Simple: specific past → I worked (yesterday)',
          'Past Continuous: in progress past → I was working (when...)',
          'Past Perfect: before another past → I had worked (before...)',
          'Future will: prediction, decision → I will work',
          'Future going to: plan, evidence → I am going to work',
        ],
        examples: [
          { sentence: 'She works, is working, has worked, worked, was working, had worked, will work, is going to work.', highlight: 'works', note: 'same verb across 8 tenses' },
          { sentence: 'I usually wake up at 7, but today I woke up late because I had been working until midnight.', highlight: 'had been working', note: 'natural mixed tense usage' },
        ],
        commonMistakes: [
          { wrong: 'Mixing tenses randomly in one paragraph.', correct: 'Be consistent with your time frame.', explanation: 'Decide: are you talking about past, present or future?' },
        ],
        tips: 'Print a tense chart and put it on your wall. After 2 weeks you\'ll stop needing it.',
      },
    ],
  },

  articles: {
    lessons: [
      {
        id: 'article-a',
        title: 'Using "A"',
        duration: '4 min',
        explanation: 'Use "a" before words starting with a consonant SOUND. It introduces a singular countable noun for the first time.',
        rules: [
          'A + consonant sound: a car, a book, a university (u = consonant sound!)',
          'First mention of something not previously discussed',
          'One of many — not specific',
          'Jobs and descriptions: She is a doctor.',
        ],
        examples: [
          { sentence: 'I saw a dog in the park.', highlight: 'a dog', note: 'first mention, not specific' },
          { sentence: 'He is a teacher.', highlight: 'a teacher', note: 'job description' },
          { sentence: 'She has a university degree.', highlight: 'a university', note: '"u" sounds like "yoo" = consonant sound' },
          { sentence: 'Can I have a coffee please?', highlight: 'a coffee', note: 'one of many' },
        ],
        commonMistakes: [
          { wrong: 'I want an university degree.', correct: 'I want a university degree.', explanation: 'University starts with consonant SOUND "yoo"' },
          { wrong: 'She is doctor.', correct: 'She is a doctor.', explanation: 'Always use article before job titles' },
        ],
        tips: 'Listen to the SOUND, not the letter. "A hour" is wrong (silent h = vowel sound) → "An hour" is correct.',
      },
      {
        id: 'article-an',
        title: 'Using "An"',
        duration: '4 min',
        explanation: 'Use "an" before words starting with a vowel SOUND (a, e, i, o, u sounds). It makes the sentence flow smoothly.',
        rules: [
          'An + vowel sound: an apple, an hour, an honest man',
          'Silent H = vowel sound: an hour, an heir, an honour',
          'Letters by name: an MBA, an X-ray (M = em, X = ex = vowel sound)',
          'Never use "an" before consonant sounds',
        ],
        examples: [
          { sentence: 'I waited for an hour.', highlight: 'an hour', note: 'h is silent → vowel sound' },
          { sentence: 'She is an honest person.', highlight: 'an honest', note: 'silent h' },
          { sentence: 'He has an MBA.', highlight: 'an MBA', note: 'M = "em" = vowel sound' },
          { sentence: 'It was an amazing experience.', highlight: 'an amazing', note: 'a = vowel sound' },
        ],
        commonMistakes: [
          { wrong: 'a apple', correct: 'an apple', explanation: 'Apple starts with vowel sound "a"' },
          { wrong: 'an historic event', correct: 'a historic event', explanation: 'In most English, h in historic is pronounced' },
        ],
        tips: 'Say the word out loud. Does it start with a vowel sound? Then use "an". Trust your ear.',
      },
      {
        id: 'article-the',
        title: 'Using "The"',
        duration: '5 min',
        explanation: 'Use "the" when both speaker and listener know exactly which specific thing is being talked about.',
        rules: [
          'Second mention: I saw a dog. The dog was friendly.',
          'Only one exists: the sun, the moon, the internet',
          'Superlatives: the best, the biggest, the most',
          'Specific places known to both: the cinema, the bank',
        ],
        examples: [
          { sentence: 'I bought a shirt. The shirt is blue.', highlight: 'The shirt', note: 'second mention — now specific' },
          { sentence: 'The sun rises in the east.', highlight: 'The sun', note: 'unique thing' },
          { sentence: 'She is the best student in the class.', highlight: 'the best', note: 'superlative' },
          { sentence: 'Can you close the window?', highlight: 'the window', note: 'both know which one' },
        ],
        commonMistakes: [
          { wrong: 'I love the nature.', correct: 'I love nature.', explanation: 'General concepts = no article' },
          { wrong: 'She is best student.', correct: 'She is the best student.', explanation: 'Superlatives need "the"' },
        ],
        tips: 'The = "you know which one I mean". If there\'s no shared understanding of which one, don\'t use "the".',
      },
      {
        id: 'no-article',
        title: 'No Article (Zero Article)',
        duration: '4 min',
        explanation: 'Some nouns need no article — general concepts, most proper nouns, uncountable nouns used generally, and fixed phrases.',
        rules: [
          'General plural nouns: Dogs are friendly. (= dogs in general)',
          'Uncountable nouns generally: Water is essential. Love is blind.',
          'Most proper nouns: I live in Serbia. (not "the Serbia")',
          'Meals, sports, languages: breakfast, football, English',
        ],
        examples: [
          { sentence: 'I love music.', highlight: 'music', note: 'general uncountable noun' },
          { sentence: 'She speaks French.', highlight: 'French', note: 'language — no article' },
          { sentence: 'We played football after school.', highlight: 'football', note: 'sport — no article' },
          { sentence: 'Life is beautiful.', highlight: 'Life', note: 'general abstract noun' },
        ],
        commonMistakes: [
          { wrong: 'The love is important.', correct: 'Love is important.', explanation: 'Abstract nouns in general = no article' },
          { wrong: 'I play the tennis.', correct: 'I play tennis.', explanation: 'Sports = no article' },
        ],
        tips: 'Talking about things IN GENERAL (all dogs, all love, all water) = NO article.',
      },
      {
        id: 'articles-places',
        title: 'Articles with Places',
        duration: '5 min',
        explanation: 'Whether to use "the" or no article with geographical names follows specific patterns worth memorising.',
        rules: [
          'Countries: no article (Serbia, France) EXCEPT: the USA, the UK, the Netherlands',
          'Oceans, seas, rivers: the Atlantic, the Nile, the Thames',
          'Single mountains: no article (Everest) — mountain ranges: the Alps',
          'Cities: no article (London, Paris, Belgrade)',
        ],
        examples: [
          { sentence: 'I visited the United States last year.', highlight: 'the United States', note: 'plural country name = the' },
          { sentence: 'The Amazon is the longest river in South America.', highlight: 'The Amazon', note: 'rivers = the' },
          { sentence: 'She climbed Mont Blanc.', highlight: 'Mont Blanc', note: 'single mountain = no article' },
          { sentence: 'The Alps are beautiful in winter.', highlight: 'The Alps', note: 'mountain range = the' },
        ],
        commonMistakes: [
          { wrong: 'I live in the France.', correct: 'I live in France.', explanation: 'Most country names = no article' },
          { wrong: 'She swam in Atlantic.', correct: 'She swam in the Atlantic.', explanation: 'Oceans always use "the"' },
        ],
        tips: 'If the name is plural or contains a common noun (Kingdom, States, Republic) → use "the".',
      },
      {
        id: 'articles-review',
        title: 'Articles — Full Review',
        duration: '6 min',
        explanation: 'Master all article rules with a comprehensive review and tricky edge cases that catch even advanced learners.',
        rules: [
          'a = one of many, first mention, consonant sound',
          'an = one of many, first mention, vowel sound',
          'the = specific, both know which, unique thing',
          'no article = general concepts, proper nouns, sports, languages, meals',
        ],
        examples: [
          { sentence: 'A dog is a loyal animal. The dog I have is called Max.', highlight: 'A dog', note: 'general → specific with "the"' },
          { sentence: 'I had an egg for breakfast. The egg was fresh.', highlight: 'an egg', note: 'first mention → second mention' },
          { sentence: 'Life is short, but the life I\'ve lived has been amazing.', highlight: 'the life', note: 'general "life" vs specific "the life I lived"' },
        ],
        commonMistakes: [
          { wrong: 'She gave me an useful tip.', correct: 'She gave me a useful tip.', explanation: 'Useful = "yoo-seful" = consonant sound = a' },
          { wrong: 'He is best player.', correct: 'He is the best player.', explanation: 'Superlatives always need "the"' },
        ],
        tips: 'Articles are one of the hardest parts of English for non-native speakers. Practice daily — it becomes automatic.',
      },
    ],
  },

  prepositions: {
    lessons: [
      {
        id: 'prep-time-at-on-in',
        title: 'Time: at, on, in',
        duration: '5 min',
        explanation: 'At, on, and in are the three main prepositions of time. Each is used for different time expressions.',
        rules: [
          'AT: exact times, specific points → at 8pm, at noon, at midnight, at Christmas',
          'ON: days and dates → on Monday, on July 4th, on my birthday',
          'IN: longer periods → in the morning, in July, in 2024, in the 21st century',
        ],
        examples: [
          { sentence: 'The meeting is at 3pm.', highlight: 'at 3pm', note: 'exact time' },
          { sentence: 'She was born on March 15th.', highlight: 'on March 15th', note: 'specific date' },
          { sentence: 'It\'s cold in January.', highlight: 'in January', note: 'month' },
          { sentence: 'I\'ll see you in the morning.', highlight: 'in the morning', note: 'part of day' },
        ],
        commonMistakes: [
          { wrong: 'See you on the morning.', correct: 'See you in the morning.', explanation: 'Morning/afternoon/evening = in' },
          { wrong: 'I arrived in Monday.', correct: 'I arrived on Monday.', explanation: 'Days of week = on' },
        ],
        tips: 'Think: AT = a point (like a pin on a map). ON = a surface (a day spread out). IN = inside a container (a month, year, century).',
      },
      {
        id: 'prep-place-at-on-in',
        title: 'Place: at, on, in',
        duration: '5 min',
        explanation: 'The same three prepositions work for place too, but with different logic based on how we see the space.',
        rules: [
          'IN: enclosed space, inside something → in the room, in the box, in London',
          'ON: surface, or a line/road → on the table, on the wall, on the bus, on Oxford Street',
          'AT: specific point or location → at the door, at the station, at school, at home',
        ],
        examples: [
          { sentence: 'She is in the kitchen.', highlight: 'in the kitchen', note: 'enclosed space' },
          { sentence: 'The book is on the shelf.', highlight: 'on the shelf', note: 'surface' },
          { sentence: 'I\'ll meet you at the cinema.', highlight: 'at the cinema', note: 'meeting point' },
          { sentence: 'We live on Baker Street.', highlight: 'on Baker Street', note: 'street/road' },
        ],
        commonMistakes: [
          { wrong: 'I am at the bed.', correct: 'I am in bed.', explanation: 'In bed = fixed expression, no article' },
          { wrong: 'She is in the bus.', correct: 'She is on the bus.', explanation: 'Public transport = on (bus, train, plane)' },
        ],
        tips: 'Transport rule: ON a bus/train/plane (you can walk around). IN a car/taxi (enclosed, personal).',
      },
      {
        id: 'prep-movement',
        title: 'Movement Prepositions',
        duration: '5 min',
        explanation: 'These prepositions describe direction and movement from one place to another.',
        rules: [
          'TO: movement toward a destination → go to school, travel to Paris',
          'INTO: movement inside something → walk into the room, get into the car',
          'ONTO: movement to a surface → jump onto the bed, climb onto the roof',
          'FROM: origin/starting point → come from Serbia, fly from London',
        ],
        examples: [
          { sentence: 'She walked into the building.', highlight: 'into', note: 'entering enclosed space' },
          { sentence: 'He drove to the airport.', highlight: 'to', note: 'destination' },
          { sentence: 'The cat jumped onto the table.', highlight: 'onto', note: 'onto a surface' },
          { sentence: 'I come from Belgrade.', highlight: 'from', note: 'origin' },
        ],
        commonMistakes: [
          { wrong: 'She went to home.', correct: 'She went home.', explanation: 'Home never takes "to" — it\'s an adverb' },
          { wrong: 'He entered into the room.', correct: 'He entered the room.', explanation: 'Enter already means "go into" — don\'t double up' },
        ],
        tips: 'Home, here, there, abroad, downtown — these are adverbs, never use "to" before them.',
      },
      {
        id: 'prep-by-with-without',
        title: 'By, With & Without',
        duration: '5 min',
        explanation: 'By shows how something is done or who did it. With shows accompaniment or tools. Without shows absence.',
        rules: [
          'BY: method, agent in passive, deadline → by car, written by Tolstoy, finish by Friday',
          'WITH: accompaniment, tools, ingredients → with a knife, coffee with milk, she came with me',
          'WITHOUT: absence of something → without sugar, without hesitation',
        ],
        examples: [
          { sentence: 'I travel to work by train.', highlight: 'by train', note: 'method of transport' },
          { sentence: 'The book was written by Hemingway.', highlight: 'by Hemingway', note: 'agent in passive' },
          { sentence: 'Please finish the report by Monday.', highlight: 'by Monday', note: 'deadline' },
          { sentence: 'She drinks her coffee without sugar.', highlight: 'without sugar', note: 'absence' },
        ],
        commonMistakes: [
          { wrong: 'I go with car.', correct: 'I go by car.', explanation: 'Transport method = by, not with' },
          { wrong: 'Send it until Friday.', correct: 'Send it by Friday.', explanation: 'Deadline = by, not until' },
        ],
        tips: 'BY Friday = deadline (must be done before). UNTIL Friday = continuous action up to that point. Very different!',
      },
      {
        id: 'prep-about-of-for',
        title: 'About, Of & For',
        duration: '5 min',
        explanation: 'These three prepositions are often confused because they can all relate to subjects, topics and purposes.',
        rules: [
          'ABOUT: topic, concerning → talk about, think about, a book about history',
          'OF: belonging, part of whole, origin → a cup of tea, the end of the story, a friend of mine',
          'FOR: purpose, duration, recipient → this is for you, study for an hour, what is it for?',
        ],
        examples: [
          { sentence: 'We talked about the project.', highlight: 'about', note: 'topic' },
          { sentence: 'Give me a glass of water.', highlight: 'of water', note: 'content/belonging' },
          { sentence: 'This gift is for you.', highlight: 'for you', note: 'recipient' },
          { sentence: 'I\'ve been waiting for 2 hours.', highlight: 'for 2 hours', note: 'duration' },
        ],
        commonMistakes: [
          { wrong: 'What is this about for?', correct: 'What is this about? / What is this for?', explanation: 'About = topic. For = purpose. Not both.' },
          { wrong: 'A cup from tea.', correct: 'A cup of tea.', explanation: 'Contents/ingredients = of' },
        ],
        tips: 'FOR + time duration (for 3 hours). SINCE + starting point (since Monday). Don\'t mix them up!',
      },
      {
        id: 'prep-phrasal',
        title: 'Prepositions in Phrasal Verbs',
        duration: '6 min',
        explanation: 'Many English verbs change meaning completely when combined with a preposition. These are called phrasal verbs.',
        rules: [
          'Look UP (search), Look AFTER (care for), Look INTO (investigate)',
          'Take OFF (remove/fly), Take OVER (control), Take ON (accept responsibility)',
          'Put OFF (postpone), Put ON (wear/start), Put Up WITH (tolerate)',
          'The preposition changes the entire meaning — learn them as vocabulary!',
        ],
        examples: [
          { sentence: 'Can you look after my dog this weekend?', highlight: 'look after', note: 'take care of' },
          { sentence: 'The plane took off two hours late.', highlight: 'took off', note: 'became airborne' },
          { sentence: 'I can\'t put up with this noise.', highlight: 'put up with', note: 'tolerate' },
          { sentence: 'Let\'s put off the meeting until Friday.', highlight: 'put off', note: 'postpone' },
        ],
        commonMistakes: [
          { wrong: 'Can you look for my cat? (meaning care for)', correct: 'Can you look after my cat?', explanation: 'Look for = search. Look after = care for.' },
          { wrong: 'I\'ll think about it over.', correct: 'I\'ll think it over.', explanation: 'Separable phrasal verbs: object goes in the middle.' },
        ],
        tips: 'There are 5,000+ phrasal verbs in English. Focus on the 100 most common. They\'ll cover 95% of daily conversations.',
      },
      {
        id: 'prep-adjective-collocations',
        title: 'Prepositions After Adjectives',
        duration: '5 min',
        explanation: 'Many adjectives are always followed by a specific preposition. These must be memorized as fixed combinations.',
        rules: [
          'Afraid OF, aware OF, capable OF, fond OF, proud OF, tired OF',
          'Good AT, bad AT, surprised AT, amazed AT',
          'Interested IN, involved IN, successful IN',
          'Happy WITH, satisfied WITH, familiar WITH, bored WITH',
        ],
        examples: [
          { sentence: 'She is very good at languages.', highlight: 'good at', note: 'fixed collocation' },
          { sentence: 'I\'m not interested in politics.', highlight: 'interested in', note: 'fixed collocation' },
          { sentence: 'He is proud of his children.', highlight: 'proud of', note: 'fixed collocation' },
          { sentence: 'Are you familiar with this software?', highlight: 'familiar with', note: 'fixed collocation' },
        ],
        commonMistakes: [
          { wrong: 'She is good in math.', correct: 'She is good at math.', explanation: 'Good at — always at, never in' },
          { wrong: 'I\'m interested about history.', correct: 'I\'m interested in history.', explanation: 'Interested in — always in' },
        ],
        tips: 'Make a personal list of adjective + preposition combinations you use most. Review it weekly.',
      },
      {
        id: 'prep-review',
        title: 'Prepositions — Full Review',
        duration: '7 min',
        explanation: 'A complete overview of preposition rules with focus on the most common errors.',
        rules: [
          'Time: AT (exact), ON (day/date), IN (month/year/period)',
          'Place: IN (inside), ON (surface), AT (point/location)',
          'Transport: BY car/bus/plane (method), ON the bus/train (riding)',
          'Deadline: BY Monday. Duration: FOR 3 hours. Since: SINCE Monday.',
        ],
        examples: [
          { sentence: 'At 9am on Monday, we met in the conference room at the office.', highlight: 'At / on / in / at', note: '4 prepositions in one sentence' },
          { sentence: 'She traveled from London to Paris by train, arriving at noon on Tuesday.', highlight: 'from/to/by/at/on', note: 'movement + time + method' },
        ],
        commonMistakes: [
          { wrong: 'I\'ll see you in Friday at the morning.', correct: 'I\'ll see you on Friday in the morning.', explanation: 'Days = on. Morning/afternoon/evening = in.' },
        ],
        tips: 'Prepositions are best learned in context, not in isolation. Read English daily and notice which prepositions native speakers use.',
      },
    ],
  },

  conditionals: {
    lessons: [
      {
        id: 'zero-conditional',
        title: 'Zero Conditional',
        duration: '4 min',
        explanation: 'Used for facts, scientific truths, and things that are always true. Both clauses use Present Simple.',
        rules: [
          'IF + Present Simple + Present Simple',
          'Expresses: general truth, scientific fact, habitual result',
          'IF can be replaced by WHEN (same meaning here)',
          'The result is 100% certain — it always happens',
        ],
        examples: [
          { sentence: 'If you heat water to 100°C, it boils.', highlight: 'heat / boils', note: 'scientific fact' },
          { sentence: 'If I eat too much, I feel sick.', highlight: 'eat / feel', note: 'personal habit' },
          { sentence: 'Plants die if they don\'t get water.', highlight: 'die / don\'t get', note: 'general truth' },
          { sentence: 'When it rains, the streets get wet.', highlight: 'rains / get', note: 'when = if here' },
        ],
        commonMistakes: [
          { wrong: 'If you will heat water, it boils.', correct: 'If you heat water, it boils.', explanation: 'Zero conditional = no will in if-clause' },
          { wrong: 'If water heated, it boils.', correct: 'If water is heated, it boils.', explanation: 'Present simple or present passive in if-clause' },
        ],
        tips: 'Zero conditional = facts. If this ALWAYS leads to that → zero conditional. No exceptions, no uncertainty.',
      },
      {
        id: 'first-conditional',
        title: 'First Conditional',
        duration: '5 min',
        explanation: 'Used for real, possible situations in the future. The condition is likely or at least possible.',
        rules: [
          'IF + Present Simple + will + base verb',
          'The situation is REAL and POSSIBLE',
          'Can also use: going to, can, may, might in result clause',
          'Never use WILL in the if-clause',
        ],
        examples: [
          { sentence: 'If it rains tomorrow, I will stay home.', highlight: 'rains / will stay', note: 'possible future' },
          { sentence: 'If you study hard, you will pass the exam.', highlight: 'study / will pass', note: 'real possibility' },
          { sentence: 'She will call you if she has time.', highlight: 'will call / has', note: 'if-clause can come second' },
          { sentence: 'If I finish early, I might go to the gym.', highlight: 'finish / might go', note: 'might instead of will' },
        ],
        commonMistakes: [
          { wrong: 'If it will rain, I\'ll stay home.', correct: 'If it rains, I\'ll stay home.', explanation: 'Never will in the if-clause of 1st conditional' },
          { wrong: 'If you will study, you will pass.', correct: 'If you study, you will pass.', explanation: 'If + present simple (no will)' },
        ],
        tips: 'First conditional = real life. You genuinely think this might happen. "If I miss the bus, I\'ll take a taxi."',
      },
      {
        id: 'second-conditional',
        title: 'Second Conditional',
        duration: '5 min',
        explanation: 'Used for hypothetical, imaginary, or unlikely situations in the present or future.',
        rules: [
          'IF + Past Simple + would + base verb',
          'The situation is UNREAL or UNLIKELY',
          'Use WERE (not was) for all persons in formal English: If I were you...',
          'Would can be replaced by could/might for less certainty',
        ],
        examples: [
          { sentence: 'If I had a million dollars, I would travel the world.', highlight: 'had / would travel', note: 'imaginary/unlikely' },
          { sentence: 'If I were you, I would apologize.', highlight: 'were / would apologize', note: 'advice using were' },
          { sentence: 'She would be happier if she lived in the countryside.', highlight: 'would be / lived', note: 'hypothetical' },
          { sentence: 'What would you do if you lost your job?', highlight: 'would do / lost', note: 'hypothetical question' },
        ],
        commonMistakes: [
          { wrong: 'If I would have money, I would travel.', correct: 'If I had money, I would travel.', explanation: 'Never would in the if-clause' },
          { wrong: 'If I was you, I\'d go.', correct: 'If I were you, I\'d go.', explanation: 'Were for all persons in 2nd conditional (formal)' },
        ],
        tips: 'Second conditional = dreams and advice. "If I were a bird, I would fly to you." Pure imagination.',
      },
      {
        id: 'third-conditional',
        title: 'Third Conditional',
        duration: '6 min',
        explanation: 'Used for hypothetical situations in the PAST — things that didn\'t happen. Often expresses regret.',
        rules: [
          'IF + Past Perfect + would have + past participle',
          'The situation is IMPOSSIBLE — it\'s in the past and can\'t be changed',
          'Expresses: regret, criticism, relief about past',
          'Could have / might have instead of would have = less certain result',
        ],
        examples: [
          { sentence: 'If I had studied harder, I would have passed the exam.', highlight: 'had studied / would have passed', note: 'past regret — didn\'t study' },
          { sentence: 'She wouldn\'t have been late if she had left earlier.', highlight: 'wouldn\'t have been / had left', note: 'past criticism' },
          { sentence: 'If he had taken the other road, he wouldn\'t have had an accident.', highlight: 'had taken / wouldn\'t have had', note: 'past unreal' },
          { sentence: 'I might have got the job if I had prepared better.', highlight: 'might have got / had prepared', note: 'past possibility' },
        ],
        commonMistakes: [
          { wrong: 'If I would have known, I would have helped.', correct: 'If I had known, I would have helped.', explanation: 'If-clause = Past Perfect (had known), no would' },
          { wrong: 'I would have went.', correct: 'I would have gone.', explanation: 'Always past participle: gone, not went' },
        ],
        tips: 'Third conditional = past regrets. "If only I had..." Native speakers use it constantly when talking about mistakes.',
      },
      {
        id: 'mixed-conditionals',
        title: 'Mixed Conditionals',
        duration: '7 min',
        explanation: 'Mix of 2nd and 3rd conditional when the time in the if-clause and result clause are different.',
        rules: [
          'Past → Present: If + Past Perfect + would + base verb',
          '"If I had studied medicine, I would be a doctor now."',
          'Present → Past: If + Past Simple + would have + past participle',
          '"If I weren\'t so shy, I would have spoken to her."',
        ],
        examples: [
          { sentence: 'If I had moved to London, I would speak better English now.', highlight: 'had moved / would speak', note: 'past action → present result' },
          { sentence: 'If she weren\'t so stubborn, she would have listened.', highlight: 'weren\'t / would have listened', note: 'present state → past result' },
          { sentence: 'He would be alive today if he had gone to the doctor.', highlight: 'would be / had gone', note: 'past action → present result' },
          { sentence: 'If I didn\'t love her, I wouldn\'t have stayed.', highlight: 'didn\'t love / wouldn\'t have stayed', note: 'present feeling → past result' },
        ],
        commonMistakes: [
          { wrong: 'If I would have moved, I would speak better.', correct: 'If I had moved, I would speak better.', explanation: 'Never would in the if-clause, ever' },
        ],
        tips: 'Mixed conditionals are advanced — native speakers use them naturally. Master the basic 3 first, then mix!',
      },
    ],
  },

  'modal-verbs': {
    lessons: [
      {
        id: 'can-could',
        title: 'Can & Could',
        duration: '5 min',
        explanation: 'Can = present ability or permission. Could = past ability, polite request, or possibility.',
        rules: [
          'Can + base verb: I can swim. (present ability)',
          'Could + base verb: I could swim when I was young. (past ability)',
          'Polite request: Could you help me? (more polite than "Can")',
          'Possibility: It could be true. (maybe)',
        ],
        examples: [
          { sentence: 'She can speak 3 languages.', highlight: 'can speak', note: 'present ability' },
          { sentence: 'Could you pass the salt, please?', highlight: 'Could you', note: 'polite request' },
          { sentence: 'He could run fast when he was young.', highlight: 'could run', note: 'past ability' },
          { sentence: 'It could rain later.', highlight: 'could rain', note: 'possibility' },
        ],
        commonMistakes: [
          { wrong: 'I can to swim.', correct: 'I can swim.', explanation: 'Modal verbs never followed by "to"' },
          { wrong: 'She cans drive.', correct: 'She can drive.', explanation: 'Modals never take -s for he/she/it' },
        ],
        tips: 'Could is almost always more polite than can. Use could in formal situations and with strangers.',
      },
      {
        id: 'should-ought',
        title: 'Should & Ought To',
        duration: '5 min',
        explanation: 'Both express advice and recommendation. Should is more common; ought to is slightly more formal.',
        rules: [
          'Should + base verb: advice or recommendation',
          'Ought to + base verb: same meaning, slightly more formal',
          'Negative: shouldn\'t (you should not do this)',
          'Past form: should have + past participle (regret about past)',
        ],
        examples: [
          { sentence: 'You should see a doctor.', highlight: 'should see', note: 'advice' },
          { sentence: 'You shouldn\'t eat so much sugar.', highlight: 'shouldn\'t eat', note: 'negative advice' },
          { sentence: 'I should have called earlier. Sorry.', highlight: 'should have called', note: 'regret about past action' },
          { sentence: 'We ought to leave now.', highlight: 'ought to leave', note: 'mild obligation' },
        ],
        commonMistakes: [
          { wrong: 'You should to go.', correct: 'You should go.', explanation: 'Should + base verb, no "to"' },
          { wrong: 'I should have went.', correct: 'I should have gone.', explanation: 'Always past participle after should have' },
        ],
        tips: '"Should have + past participle" = regret. This is one of the most common structures in spoken English.',
      },
      {
        id: 'must-have-to',
        title: 'Must & Have To',
        duration: '5 min',
        explanation: 'Both express strong obligation, but must comes from the speaker while have to comes from external rules or authority.',
        rules: [
          'Must + base verb: strong internal obligation (speaker decides)',
          'Have to + base verb: external obligation (rules, laws, boss)',
          'Must not = prohibition (don\'t do this!)',
          'Don\'t have to = no obligation (optional)',
        ],
        examples: [
          { sentence: 'I must finish this report today.', highlight: 'must finish', note: 'self-imposed obligation' },
          { sentence: 'You have to wear a seatbelt by law.', highlight: 'have to wear', note: 'external law' },
          { sentence: 'You must not smoke here.', highlight: 'must not', note: 'prohibition' },
          { sentence: 'You don\'t have to come if you\'re busy.', highlight: 'don\'t have to', note: 'no obligation — optional' },
        ],
        commonMistakes: [
          { wrong: 'Must not = Don\'t have to', correct: 'Must not ≠ Don\'t have to', explanation: 'Must not = forbidden. Don\'t have to = optional.' },
          { wrong: 'I must to go.', correct: 'I must go.', explanation: 'Must + base verb, no "to"' },
        ],
        tips: 'MUST NOT = forbidden (dangerous if confused). DON\'T HAVE TO = your choice. This distinction is critical.',
      },
      {
        id: 'may-might',
        title: 'May & Might',
        duration: '5 min',
        explanation: 'Both express possibility. May = more likely (~50%). Might = less certain (~30%). May also used for formal permission.',
        rules: [
          'May + base verb: ~50% possibility or formal permission',
          'Might + base verb: less than 50% possibility',
          'May I...? = formal permission request',
          'Might have + pp = past possibility',
        ],
        examples: [
          { sentence: 'It may rain this afternoon.', highlight: 'may rain', note: 'possible, roughly 50%' },
          { sentence: 'I might go to the party — not sure yet.', highlight: 'might go', note: 'uncertain, less likely' },
          { sentence: 'May I leave early today?', highlight: 'May I', note: 'formal permission request' },
          { sentence: 'She might have missed the bus.', highlight: 'might have missed', note: 'past possibility' },
        ],
        commonMistakes: [
          { wrong: 'I might to call you.', correct: 'I might call you.', explanation: 'Modal + base verb, no "to"' },
          { wrong: 'May be I\'ll go.', correct: 'Maybe I\'ll go. / I may go.', explanation: 'Maybe (one word) = adverb. May be (two words) = verb phrase.' },
        ],
        tips: '"May be" (two words) = verb. "Maybe" (one word) = adverb meaning perhaps. Don\'t confuse them!',
      },
      {
        id: 'will-would',
        title: 'Will & Would',
        duration: '5 min',
        explanation: 'Will = future certainty and spontaneous decisions. Would = conditional situations, polite requests, and hypothetical ideas.',
        rules: [
          'Will: predictions, promises, instant decisions',
          'Would: conditional sentences, polite requests, hypothetical',
          'Would like = polite want: Would you like some tea?',
          'Would have = unreal past: I would have helped.',
        ],
        examples: [
          { sentence: 'I will call you back in 5 minutes.', highlight: 'will call', note: 'promise' },
          { sentence: 'Would you like some tea?', highlight: 'Would you like', note: 'polite offer' },
          { sentence: 'If I had money, I would travel the world.', highlight: 'would travel', note: 'hypothetical' },
          { sentence: 'I would have helped if I had known.', highlight: 'would have helped', note: 'unreal past' },
        ],
        commonMistakes: [
          { wrong: 'I would go there yesterday.', correct: 'I would have gone there.', explanation: 'Past hypothetical needs would have + pp' },
          { wrong: 'Would you like to would come?', correct: 'Would you like to come?', explanation: 'Would like to + base verb — not two modals' },
        ],
        tips: '"Would you like...?" is always more polite than "Do you want...?" Always use it in formal situations.',
      },
      {
        id: 'modals-passive',
        title: 'Modals in Passive Voice',
        duration: '6 min',
        explanation: 'Modal verbs can combine with passive voice for rules, instructions, and formal writing. Very common in official contexts.',
        rules: [
          'Modal + be + past participle: It must be done. It can be fixed.',
          'Past passive modal: modal + have been + pp: It should have been reported.',
          'Common in formal writing, instructions, signs, legal texts',
          'All modals work: can, must, should, will, may, might',
        ],
        examples: [
          { sentence: 'This form must be completed in full.', highlight: 'must be completed', note: 'formal instruction' },
          { sentence: 'The problem can be solved easily.', highlight: 'can be solved', note: 'possibility passive' },
          { sentence: 'Mistakes could have been avoided.', highlight: 'could have been avoided', note: 'past passive modal' },
          { sentence: 'It should be noted that results may vary.', highlight: 'should be noted', note: 'formal writing phrase' },
        ],
        commonMistakes: [
          { wrong: 'It must be solve.', correct: 'It must be solved.', explanation: 'Always past participle in passive' },
          { wrong: 'Should been done.', correct: 'Should have been done.', explanation: 'Modal + have been + pp for past' },
        ],
        tips: 'Modal passives are everywhere in academic writing, legal texts and formal instructions. Learn to spot them.',
      },
      {
        id: 'modals-review',
        title: 'Modal Verbs — Full Review',
        duration: '7 min',
        explanation: 'Quick reference guide for all modal verbs, their meanings, and key usage patterns.',
        rules: [
          'Can/Could: ability, possibility, permission, polite request',
          'Should/Ought to: advice, recommendation, mild obligation',
          'Must/Have to: strong obligation, prohibition (must not)',
          'May/Might: possibility, formal permission',
          'Will/Would: future, conditional, polite offers',
          'Golden rule: Modal + BASE VERB. No -s, no -ed, no "to".',
        ],
        examples: [
          { sentence: 'You should see a doctor — you might be seriously ill, and it could get worse.', highlight: 'should', note: '3 modals in one sentence' },
          { sentence: 'Visitors must not take photos. Flash can damage the artwork.', highlight: 'must not', note: 'prohibition + explanation' },
        ],
        commonMistakes: [
          { wrong: 'I must to go. / She cans sing. / He should to call.', correct: 'I must go. / She can sing. / He should call.', explanation: 'NEVER use "to" after modals, NEVER add -s' },
        ],
        tips: 'Modal verb + BASE VERB. No to. No -s. No -ed. No exceptions. Tattoo this on your brain.',
      },
    ],
  },

  'passive-voice': {
    lessons: [
      {
        id: 'passive-intro',
        title: 'What is Passive Voice?',
        duration: '5 min',
        explanation: 'In active voice, the subject does the action. In passive voice, the subject receives the action. We use passive when the doer is unknown, unimportant, or obvious.',
        rules: [
          'Active: Subject + verb + object → The chef cooked the meal.',
          'Passive: Object becomes subject + be + past participle → The meal was cooked (by the chef).',
          'BY + agent: only include when the doer is important or unknown',
          'Passive is common in: news, science, formal writing, instructions',
        ],
        examples: [
          { sentence: 'The window was broken by the children.', highlight: 'was broken', note: 'past passive' },
          { sentence: 'English is spoken all over the world.', highlight: 'is spoken', note: 'present passive, agent obvious' },
          { sentence: 'The report will be submitted tomorrow.', highlight: 'will be submitted', note: 'future passive' },
          { sentence: 'The Mona Lisa was painted by Leonardo da Vinci.', highlight: 'was painted by', note: 'agent important' },
        ],
        commonMistakes: [
          { wrong: 'The window was broke.', correct: 'The window was broken.', explanation: 'Always use PAST PARTICIPLE in passive (broken, not broke)' },
          { wrong: 'It is write in the book.', correct: 'It is written in the book.', explanation: 'write → written (irregular past participle)' },
        ],
        tips: 'If you can ask "by whom?" about the action, consider passive. If the answer is obvious or unimportant, drop the "by" phrase.',
      },
      {
        id: 'passive-present-past',
        title: 'Passive: Present & Past',
        duration: '5 min',
        explanation: 'The most common passive forms are Present Simple and Past Simple passive. Master these two first.',
        rules: [
          'Present Simple Passive: am/is/are + past participle',
          'Past Simple Passive: was/were + past participle',
          'Singular: is/was. Plural: are/were.',
          'The past participle never changes (eaten, made, written)',
        ],
        examples: [
          { sentence: 'Coffee is grown in Brazil.', highlight: 'is grown', note: 'present passive — fact' },
          { sentence: 'These shoes are made in Italy.', highlight: 'are made', note: 'present passive — plural' },
          { sentence: 'The thief was arrested last night.', highlight: 'was arrested', note: 'past passive — singular' },
          { sentence: 'Many buildings were destroyed in the earthquake.', highlight: 'were destroyed', note: 'past passive — plural' },
        ],
        commonMistakes: [
          { wrong: 'The cars is made in Germany.', correct: 'The cars are made in Germany.', explanation: 'Plural subject = are (not is)' },
          { wrong: 'He was arrest by police.', correct: 'He was arrested by police.', explanation: 'Must use full past participle: arrested' },
        ],
        tips: 'News headlines love passive voice: "Three arrested in drug raid." "New law passed by parliament." Read news in English to practice.',
      },
      {
        id: 'passive-other-tenses',
        title: 'Passive in Other Tenses',
        duration: '6 min',
        explanation: 'Every tense can be made passive. The structure is always: correct form of BE + past participle.',
        rules: [
          'Present Continuous: is/are being + pp → The road is being repaired.',
          'Present Perfect: has/have been + pp → It has been cancelled.',
          'Future will: will be + pp → The results will be announced.',
          'Going to: is/are going to be + pp → It\'s going to be fixed.',
        ],
        examples: [
          { sentence: 'The road is being repaired right now.', highlight: 'is being repaired', note: 'present continuous passive' },
          { sentence: 'My car has been stolen!', highlight: 'has been stolen', note: 'present perfect passive' },
          { sentence: 'The winner will be announced tomorrow.', highlight: 'will be announced', note: 'future passive' },
          { sentence: 'The meeting is going to be postponed.', highlight: 'is going to be postponed', note: 'going to passive' },
        ],
        commonMistakes: [
          { wrong: 'It has been stole.', correct: 'It has been stolen.', explanation: 'steal → stolen (irregular pp)' },
          { wrong: 'The road is been repaired.', correct: 'The road is being repaired.', explanation: 'Continuous passive = is BEING, not is been' },
        ],
        tips: 'Quick check: any passive form = some form of BE + past participle. Count the words between: is [being] repaired = continuous.',
      },
      {
        id: 'passive-reporting',
        title: 'Passive Reporting Verbs',
        duration: '6 min',
        explanation: 'In news and academic writing, we often use passive with reporting verbs to distance ourselves from claims.',
        rules: [
          'It is said that... / It is believed that... / It is reported that...',
          'He is said to be... / She is believed to have...',
          'Common verbs: say, believe, think, report, claim, consider, know',
          'Very common in journalism and academic writing',
        ],
        examples: [
          { sentence: 'It is believed that he is hiding abroad.', highlight: 'is believed', note: 'formal reporting' },
          { sentence: 'The suspect is said to have fled the country.', highlight: 'is said to have', note: 'passive + infinitive' },
          { sentence: 'It is reported that thousands were affected.', highlight: 'is reported', note: 'news language' },
          { sentence: 'He is known to be dangerous.', highlight: 'is known to be', note: 'warning/fact' },
        ],
        commonMistakes: [
          { wrong: 'It is said that he has fled yesterday.', correct: 'It is said that he fled yesterday.', explanation: 'Reported speech: match the tenses correctly' },
          { wrong: 'He is said to fled.', correct: 'He is said to have fled.', explanation: 'Passive + to have + past participle for past events' },
        ],
        tips: 'These structures appear in every English newspaper. "It is understood that..." "Sources are said to..." Learn to recognize and use them.',
      },
      {
        id: 'passive-review',
        title: 'Passive Voice — Full Review',
        duration: '7 min',
        explanation: 'Master all passive forms and know when to choose passive over active.',
        rules: [
          'Use passive when: doer unknown, unimportant, or obvious',
          'Present: is/are + pp | Past: was/were + pp',
          'Perfect: has/have been + pp | Continuous: is/are being + pp',
          'Future: will be + pp | Modal: must/should/can + be + pp',
        ],
        examples: [
          { sentence: 'The report must be submitted, has been reviewed, and will be published next week.', highlight: 'must be submitted', note: '3 passive forms in sequence' },
          { sentence: 'English is spoken, has been taught, and is being learned by millions worldwide.', highlight: 'is spoken', note: 'different passive tenses, same subject' },
        ],
        commonMistakes: [
          { wrong: 'The cake was being ate when I arrived.', correct: 'The cake was being eaten when I arrived.', explanation: 'eat → eaten (irregular past participle)' },
        ],
        tips: 'Passive voice is not "wrong" or "weak" — it\'s a stylistic choice. Academic and formal English uses it constantly. Master it!',
      },
    ],
  },

  'reported-speech': {
    lessons: [
      {
        id: 'rs-intro',
        title: 'What is Reported Speech?',
        duration: '5 min',
        explanation: 'Reported speech (indirect speech) is used to tell someone what another person said, without using their exact words. The tense usually shifts back one step into the past.',
        rules: [
          "Direct: She said 'I am tired.' → Reported: She said (that) she was tired.",
          "The word 'that' is optional but common",
          'Pronouns change: I→he/she, we→they, you→I/we',
          'Time expressions change: now→then, today→that day, tomorrow→the next day',
        ],
        examples: [
          { sentence: "Direct: 'I love this city.' → Reported: He said he loved that city.", highlight: 'love→loved / this→that', note: 'tense shift + pronoun + demonstrative' },
          { sentence: "Direct: 'We are leaving.' → Reported: They said they were leaving.", highlight: 'are→were / We→They', note: 'continuous tense shifts back' },
          { sentence: "Direct: 'I will call you tomorrow.' → Reported: She said she would call me the next day.", highlight: 'will→would / tomorrow→the next day', note: 'multiple changes' },
          { sentence: "Direct: 'I have finished.' → Reported: He said he had finished.", highlight: 'have finished→had finished', note: 'present perfect→past perfect' },
        ],
        commonMistakes: [
          { wrong: 'She said me that she was tired.', correct: 'She said (that) she was tired. / She told me she was tired.', explanation: "Say + (that). Tell + person + (that). Never 'said me'." },
          { wrong: 'He said he will come.', correct: 'He said he would come.', explanation: 'Will shifts to would in reported speech' },
        ],
        tips: 'The golden rule: tense shifts ONE step back. Present→Past. Past→Past Perfect. Will→Would. Can→Could.',
      },
      {
        id: 'rs-tense-backshift',
        title: 'Tense Backshift Rules',
        duration: '6 min',
        explanation: 'When we report speech, verb tenses shift back one step into the past. This is called backshift.',
        rules: [
          "Present Simple → Past Simple: 'I work' → he said he worked",
          "Present Continuous → Past Continuous: 'I am working' → she said she was working",
          "Present Perfect → Past Perfect: 'I have done' → he said he had done",
          "Past Simple → Past Perfect: 'I did' → she said she had done",
          "Will → Would: 'I will go' → he said he would go",
          "Can → Could: 'I can help' → she said she could help",
          "May → Might: 'It may rain' → he said it might rain",
        ],
        examples: [
          { sentence: "'I work in London.' → She said she worked in London.", highlight: 'work→worked', note: 'present→past' },
          { sentence: "'I have never been to Japan.' → He said he had never been to Japan.", highlight: 'have been→had been', note: 'present perfect→past perfect' },
          { sentence: "'I went to Paris last year.' → She said she had gone to Paris the year before.", highlight: 'went→had gone', note: 'past→past perfect' },
          { sentence: "'I can swim.' → He said he could swim.", highlight: 'can→could', note: 'modal backshift' },
        ],
        commonMistakes: [
          { wrong: 'He said he has finished.', correct: 'He said he had finished.', explanation: 'Present perfect MUST shift to past perfect' },
          { wrong: 'She said she can do it.', correct: 'She said she could do it.', explanation: 'Can shifts to could in reported speech' },
        ],
        tips: "No backshift needed when: reporting something still true ('She said the Earth is round'), or using past perfect already (can't go further back).",
      },
      {
        id: 'rs-say-tell',
        title: 'Say vs Tell',
        duration: '4 min',
        explanation: 'Say and tell are both used in reported speech but with different grammar patterns. Confusing them is one of the most common mistakes.',
        rules: [
          'SAY: say (that) + clause. Never say + person directly.',
          'TELL: tell + person + (that) + clause. Always needs a person.',
          'Say something TO someone (with to): She said something to me.',
          'Common tell phrases: tell the truth, tell a lie, tell a story, tell the time',
        ],
        examples: [
          { sentence: 'He said (that) he was tired.', highlight: 'said (that)', note: 'say + clause, no person' },
          { sentence: 'He told me (that) he was tired.', highlight: 'told me', note: 'tell + person + clause' },
          { sentence: 'She said to him that she would be late.', highlight: 'said to him', note: "say + to + person (with 'to')" },
          { sentence: 'Can you tell me the time?', highlight: 'tell me', note: 'fixed expression: tell the time' },
        ],
        commonMistakes: [
          { wrong: 'She said me she was busy.', correct: 'She told me she was busy. / She said she was busy.', explanation: 'Said me is NEVER correct. Use told me OR said (no person)' },
          { wrong: 'He told that he was tired.', correct: 'He said that he was tired. / He told me that he was tired.', explanation: 'Tell always needs a person after it' },
        ],
        tips: "Simple test: can you add 'me/him/her/us/them' directly after the verb? → use TELL. If not → use SAY.",
      },
      {
        id: 'rs-questions',
        title: 'Reported Questions',
        duration: '6 min',
        explanation: 'Reporting questions is tricky because word order changes — no inversion, no question mark, no auxiliary do/does/did.',
        rules: [
          "Yes/No questions → if/whether: 'Are you ready?' → He asked if I was ready.",
          "Wh-questions → wh-word + normal order: 'Where do you live?' → She asked where I lived.",
          'NO question mark in reported questions',
          "NO auxiliary do/does/did: 'Where does she work?' → He asked where she worked.",
        ],
        examples: [
          { sentence: "'Are you coming?' → She asked if I was coming.", highlight: 'if + normal order', note: 'yes/no → if/whether' },
          { sentence: "'Where do you live?' → He asked where I lived.", highlight: 'where + normal order, no do', note: 'wh-question, no auxiliary' },
          { sentence: "'What time is it?' → She asked what time it was.", highlight: 'what time it was', note: 'inversion removed' },
          { sentence: "'Have you finished?' → He asked if I had finished.", highlight: 'if + had finished', note: 'present perfect→past perfect' },
        ],
        commonMistakes: [
          { wrong: 'She asked where did I live.', correct: 'She asked where I lived.', explanation: 'No inversion and no auxiliary do in reported questions' },
          { wrong: 'He asked if was I ready?', correct: 'He asked if I was ready.', explanation: 'Normal subject-verb order, no question mark' },
        ],
        tips: 'Reported questions = normal sentence order. Remove do/does/did. Remove question mark. Add if/whether for yes/no questions.',
      },
      {
        id: 'rs-commands',
        title: 'Reported Commands & Requests',
        duration: '5 min',
        explanation: 'Commands and requests in reported speech use infinitive forms: told/asked/ordered + object + to + base verb.',
        rules: [
          'Commands: told/ordered + person + to + base verb',
          'Requests: asked + person + to + base verb',
          'Negative commands: told/asked + person + NOT to + base verb',
          'Advice: advised + person + to + base verb',
        ],
        examples: [
          { sentence: "'Sit down!' → The teacher told the students to sit down.", highlight: 'told...to sit', note: 'command → told + to' },
          { sentence: "'Please help me.' → She asked him to help her.", highlight: 'asked...to help', note: 'request → asked + to' },
          { sentence: "'Don't touch that!' → He told me not to touch it.", highlight: 'told...not to touch', note: 'negative command' },
          { sentence: "'You should rest.' → The doctor advised her to rest.", highlight: 'advised...to rest', note: 'advice → advised + to' },
        ],
        commonMistakes: [
          { wrong: 'She told me that sit down.', correct: 'She told me to sit down.', explanation: 'Commands use told + person + TO + base verb' },
          { wrong: "He asked me don't go.", correct: 'He asked me not to go.', explanation: 'Negative: asked/told + person + NOT TO + base verb' },
        ],
        tips: 'Commands and requests always use TO infinitive in reported speech. Never that-clause for commands.',
      },
      {
        id: 'rs-no-backshift',
        title: 'When NOT to Backshift',
        duration: '5 min',
        explanation: "Sometimes we don't change the tense in reported speech — when the situation is still true, or when reporting immediately.",
        rules: [
          "Permanent truths: 'The sun rises in the east.' → He said the sun rises in the east. (still true)",
          "Immediate reporting: 'She says she is coming.' (happening now, no shift needed)",
          "After past perfect: can't go further back → stays past perfect",
          "With 'that' omitted in casual speech: He goes 'I'm tired.' (very informal)",
        ],
        examples: [
          { sentence: 'The teacher said water boils at 100°C.', highlight: 'boils (present)', note: 'scientific fact = no backshift' },
          { sentence: 'She says she will be here at 8.', highlight: 'says...will', note: 'present reporting verb = no backshift' },
          { sentence: 'He said he had already left when it happened.', highlight: 'had left (no change)', note: 'already past perfect = stays' },
          { sentence: 'Scientists say the climate is changing rapidly.', highlight: 'is changing', note: 'ongoing current situation' },
        ],
        commonMistakes: [
          { wrong: 'He said the Earth was round. (as if doubting)', correct: 'He said the Earth is round.', explanation: "Permanent facts don't need backshift" },
        ],
        tips: 'Ask yourself: is this still true right now? If yes — backshift is optional. If it was true only in the past — backshift is needed.',
      },
      {
        id: 'rs-review',
        title: 'Reported Speech — Full Review',
        duration: '8 min',
        explanation: 'Complete overview of all reported speech patterns with the most challenging combinations.',
        rules: [
          'Statements: said/told + (that) + backshifted clause',
          'Questions: asked + if/whether OR wh-word + normal order + backshift',
          'Commands: told/asked/ordered + person + (not) to + base verb',
          'Tense shifts: present→past, past→past perfect, will→would, can→could',
          'Time shifts: now→then, today→that day, tomorrow→next day, yesterday→day before',
        ],
        examples: [
          { sentence: "'I will call you tomorrow.' → She said she would call me the next day.", highlight: 'will→would / tomorrow→next day', note: 'multiple changes' },
          { sentence: "'Where have you been?' → He asked where I had been.", highlight: 'where + had been, no inversion', note: 'wh-question reported' },
          { sentence: "'Don't open that door!' → She told us not to open that door.", highlight: 'told...not to open', note: 'negative command' },
        ],
        commonMistakes: [
          { wrong: 'He said me where did I live.', correct: 'He asked me where I lived.', explanation: 'Ask for questions. No inversion. No did.' },
        ],
        tips: 'Master say vs tell first. Then tense backshift. Then questions (no inversion). Build it up step by step.',
      },
    ],
  },

  'relative-clauses': {
    lessons: [
      {
        id: 'rc-intro',
        title: 'What are Relative Clauses?',
        duration: '5 min',
        explanation: 'Relative clauses give extra information about a noun. They begin with relative pronouns: who, which, that, whose, where, when, why.',
        rules: [
          'WHO: refers to people → The man who called you is my brother.',
          'WHICH: refers to things/animals → The book which I bought was expensive.',
          'THAT: refers to people OR things (informal) → The car that I drive is old.',
          'WHOSE: possession → The girl whose bag was stolen called the police.',
          'WHERE: place → The city where I was born is beautiful.',
          'WHEN: time → The year when I graduated was 2020.',
        ],
        examples: [
          { sentence: 'The woman who lives next door is a doctor.', highlight: 'who lives next door', note: 'person' },
          { sentence: 'The phone which I lost was brand new.', highlight: 'which I lost', note: 'thing' },
          { sentence: 'The student whose essay won the prize was delighted.', highlight: 'whose essay won', note: 'possession' },
          { sentence: "That's the restaurant where we had our first date.", highlight: 'where we had', note: 'place' },
        ],
        commonMistakes: [
          { wrong: 'The man which called me.', correct: 'The man who called me.', explanation: 'WHO for people, WHICH for things' },
          { wrong: 'The woman whose she is a doctor.', correct: 'The woman who is a doctor.', explanation: "Don't repeat the subject after whose/who/which" },
        ],
        tips: 'Quick guide: PERSON → who/that. THING → which/that. POSSESSION → whose. PLACE → where. TIME → when.',
      },
      {
        id: 'rc-defining',
        title: 'Defining Relative Clauses',
        duration: '5 min',
        explanation: 'Defining relative clauses identify WHICH person or thing we mean. Without them the sentence loses its meaning. No commas used.',
        rules: [
          'No commas — the clause is essential to the meaning',
          'That can replace who or which in defining clauses',
          'The relative pronoun can be omitted when it\'s the object',
          "Example: The book (that) I read was great. — 'that' omitted, still correct",
        ],
        examples: [
          { sentence: 'The student who studies hardest will pass.', highlight: 'who studies hardest', note: 'defines WHICH student — essential' },
          { sentence: 'I lost the keys that you gave me.', highlight: 'that you gave me', note: 'defines WHICH keys' },
          { sentence: 'The movie (that) we watched last night was amazing.', highlight: '(that) we watched', note: 'object pronoun — can be omitted' },
          { sentence: 'People who exercise regularly live longer.', highlight: 'who exercise regularly', note: 'defines which people' },
        ],
        commonMistakes: [
          { wrong: 'The man, who I met, is nice. (defining)', correct: 'The man who I met is nice.', explanation: 'Defining clauses = NO commas' },
          { wrong: "That's the man which I told you about.", correct: "That's the man who/that I told you about.", explanation: 'WHICH for things only. People = who or that.' },
        ],
        tips: 'Test: remove the relative clause. Does the sentence still make sense and mean the same? If not → it\'s defining (no commas).',
      },
      {
        id: 'rc-non-defining',
        title: 'Non-Defining Relative Clauses',
        duration: '5 min',
        explanation: 'Non-defining relative clauses add EXTRA information about something already identified. Always use commas. Cannot use \'that\'.',
        rules: [
          'Always use commas before and after the clause',
          "CANNOT use 'that' — only who, which, whose, where, when",
          'The clause can be removed without changing core meaning',
          'Very common in formal and written English',
        ],
        examples: [
          { sentence: 'My brother, who lives in London, is a lawyer.', highlight: ', who lives in London,', note: 'extra info about brother — already identified' },
          { sentence: 'The Eiffel Tower, which was built in 1889, attracts millions of visitors.', highlight: ', which was built in 1889,', note: 'extra fact about tower' },
          { sentence: 'She gave me this book, which I found really useful.', highlight: ', which I found really useful', note: 'comment on whole action' },
          { sentence: 'My father, whose company won an award, is very proud.', highlight: ', whose company won an award,', note: 'possession + extra info' },
        ],
        commonMistakes: [
          { wrong: 'My sister, that is a nurse, works nights.', correct: 'My sister, who is a nurse, works nights.', explanation: "Non-defining: NEVER use 'that', use who/which" },
          { wrong: 'My car which is red is fast. (extra info)', correct: 'My car, which is red, is fast.', explanation: 'Extra info = must use commas' },
        ],
        tips: "Read the sentence without the clause. If it still makes complete sense and you know exactly who/what it is → non-defining (use commas).",
      },
      {
        id: 'rc-whose-where-when',
        title: 'Whose, Where & When',
        duration: '5 min',
        explanation: 'Three relative pronouns that learners often forget or misuse.',
        rules: [
          'WHOSE: possession for people AND things → The house whose roof is red. / The company whose products we use.',
          "WHERE: place — replaces 'in which / at which / on which'",
          "WHEN: time — replaces 'in which / on which / at which' for time",
          "WHY: reason — replaces 'for which' → That's the reason why I left.",
        ],
        examples: [
          { sentence: 'The student whose work impressed me got an A.', highlight: 'whose work', note: 'possession' },
          { sentence: 'The hotel where we stayed was beautiful.', highlight: 'where we stayed', note: '= in which we stayed' },
          { sentence: 'I remember the day when we first met.', highlight: 'when we first met', note: '= on which we first met' },
          { sentence: "That's the reason why she quit.", highlight: 'why she quit', note: '= for which she quit' },
        ],
        commonMistakes: [
          { wrong: 'The city which I was born.', correct: 'The city where I was born. / The city in which I was born.', explanation: 'Place uses WHERE, not which alone' },
          { wrong: "The man who's car was stolen.", correct: 'The man whose car was stolen.', explanation: "Whose = possession. Who's = who is (contraction)" },
        ],
        tips: "Whose vs Who's: WHOSE = possession (whose car). WHO'S = who is (who's coming?). Completely different!",
      },
      {
        id: 'rc-omitting',
        title: 'Omitting the Relative Pronoun',
        duration: '4 min',
        explanation: 'In defining relative clauses, we can often leave out the relative pronoun when it is the object of the clause.',
        rules: [
          'Omit when the pronoun is the OBJECT (not subject) of the relative clause',
          "Subject: 'The man who called me' — who is subject of 'called' → cannot omit",
          "Object: 'The man (who) I called' — I is subject, who is object → CAN omit",
          'WHOSE, WHERE, WHEN cannot be omitted',
        ],
        examples: [
          { sentence: 'The book (that) I bought is great. → The book I bought is great.', highlight: 'that omitted', note: 'I = subject, that = object → omit' },
          { sentence: 'The woman who called me was angry.', highlight: 'who — cannot omit', note: 'who = subject of called → must keep' },
          { sentence: 'The film (which) we watched was boring. → The film we watched was boring.', highlight: 'which omitted', note: 'we = subject → which is object → omit' },
          { sentence: 'Is this the bag (that) you were looking for?', highlight: '(that) omitted', note: 'common in spoken English' },
        ],
        commonMistakes: [
          { wrong: 'The man called me was angry. (omitting subject pronoun)', correct: 'The man who called me was angry.', explanation: 'Cannot omit subject relative pronoun' },
        ],
        tips: "Quick test: if you can answer 'who/what did the action in the clause?' and it's NOT the pronoun → you can omit it.",
      },
      {
        id: 'rc-review',
        title: 'Relative Clauses — Full Review',
        duration: '7 min',
        explanation: 'Master all relative clause types with focus on defining vs non-defining and correct pronoun choice.',
        rules: [
          'WHO: people | WHICH: things | THAT: people or things (defining only)',
          'WHOSE: possession | WHERE: place | WHEN: time | WHY: reason',
          'Defining: no commas, can use that, can omit object pronoun',
          'Non-defining: commas required, no that, cannot omit pronoun',
        ],
        examples: [
          { sentence: 'The teacher who taught me English, whose name I still remember, was the one who inspired me most.', highlight: 'who / whose / who', note: '3 relative pronouns about people' },
          { sentence: 'London, where I lived for 5 years, is a city which never stops moving.', highlight: 'where / which', note: 'non-defining + defining mixed' },
        ],
        commonMistakes: [
          { wrong: 'The place which I was born is beautiful.', correct: 'The place where I was born is beautiful.', explanation: 'Place = where (not which alone)' },
          { wrong: 'My mother, that is a nurse, works hard.', correct: 'My mother, who is a nurse, works hard.', explanation: 'Non-defining = never that' },
        ],
        tips: 'Commas = non-defining = extra info = no that. No commas = defining = essential info = that allowed.',
      },
    ],
  },
}
